### PR TITLE
Fix clobbering of the span context if extraction fails

### LINKED ISSUE #655: api/trace: Neither B3.Extract nor TraceContext.Extract stack properly after other HTTPExtractors
Used on its own, `api/trace.B3` works as an `api/propagation.HTTPExtractor` to consume HTTP headers. However, if nominated for use in a chain after another extractor such as `api/trace.TraceContext`, the `B3` extractor clobbers the context produced by the earlier extractor.

Consider the following configuration:
```go
// Fails for HTTP requests with W3C Trace Context header set
global.SetPropagators(propagation.New(
  propagation.WithExtractors(
    trace.TraceContext{},
    trace.B3{})))
```
If we receive an HTTP request with [the W3C Trace Context "traceparent" header](https://www.w3.org/TR/trace-context/#traceparent-header) and no B3 headers, the `api/trace.TraceContext` extractor reads the header and yields a populated `core.SpanContext`. Next, when [the `api/propagation.ExtractHTTP` function feeds that first context](https://github.com/open-telemetry/opentelemetry-go/blob/v0.4.2/api/propagation/propagation.go#L128-L135) through `api/trace.B3.Extract`, [it ignores the `context.Context` it receives as input](https://github.com/open-telemetry/opentelemetry-go/blob/v0.4.2/api/trace/b3_propagator.go#L79-L87), and yields a `core.EmptySpanContext()`, rather than passing the populated context through.

Note that [`api/trace.TraceContext` does the same](https://github.com/open-telemetry/opentelemetry-go/blob/v0.4.2/api/trace/trace_context_propagator.go#L59-L61). Were we to reverse the arguments in the statement above, and situate the `api/trace.B3` extractor first, we would fail to extract the span context correctly from an HTTP request arriving with B3 headers.
```go
// Fails for HTTP requests with B3 headers set
global.SetPropagators(propagation.New(
  propagation.WithExtractors(
    trace.B3{},
    trace.TraceContext{})))
```

This report follows from [initial discussion in the "opentelemetry/opentelemetry-go" Gitter channel](https://gitter.im/open-telemetry/opentelemetry-go?at=5ea09ff3f8b37f6dac6974df).

### PR DESCRIPTION
**Pull request by krnowak**
Closes #655.

### CODE REVIEW

File: api/trace/testtrace/propagator_test.go [hunk 1]
```diff
@@ -0,0 +1,94 @@
...
+		ctx := propagation.ExtractHTTP(bg, props, ns)
+		sc := trace.RemoteSpanContextFromContext(ctx)
+		require.True(t, sc.IsValid(), "oota prop failed sanity check")
+	}
+	// sanity check for real propagators
+	for _, prop := range testProps {
+		props := propagation.New(propagation.WithExtractors(prop))
+		ctx := propagation.ExtractHTTP(bg, props, ns)
+		sc := trace.RemoteSpanContextFromContext(ctx)
+		require.Falsef(t, sc.IsValid(), "%#v failed sanity check")
```
Comment (MrAlias) [inline api/trace/testtrace/propagator_test.go:86]: Missing a format field value.
```suggestion
		require.Falsef(t, sc.IsValid(), "%#v failed sanity check", props)
```

File: api/trace/trace_context_propagator.go [hunk 2]
```diff
@@ -57,7 +57,11 @@ func (TraceContext) Inject(ctx context.Context, supplier propagation.HTTPSupplie
 }
 
 func (tc TraceContext) Extract(ctx context.Context, supplier propagation.HTTPSupplier) context.Context {
-	return ContextWithRemoteSpanContext(ctx, tc.extract(supplier))
+	sc := tc.extract(supplier)
```
Comment (seh) [inline api/trace/trace_context_propagator.go:60]: If instead we had `TraceContext.extract` return a bool value as a second return value, we could avoid the byte array comparison in `TraceID.IsValid`. Did you consider that alternative?

File: api/trace/b3_propagator.go [hunk 3]
```diff
@@ -82,6 +82,9 @@ func (b3 B3) Extract(ctx context.Context, supplier propagation.HTTPSupplier) con
 	} else {
 		sc = b3.extract(supplier)
 	}
+	if !sc.IsValid() {
```
Comment (seh) [inline api/trace/b3_propagator.go:85]: If instead we had `B3.extractSingleHeader` and `B3.extract` return a bool value as a second return value, we could avoid the byte array comparison in `TraceID.IsValid`. Did you consider that alternative?

File: api/trace/testtrace/propagator_test.go (hunk 1 above)
Comment (seh) [reply api/trace/testtrace/propagator_test.go:86]: I suspect @MrAlias meant `prop` there for that argument.

File: api/trace/testtrace/propagator_test.go [hunk 4]
```diff
@@ -0,0 +1,94 @@
...
+	bg := context.Background()
+	// sanity check of oota propagator
+	{
+		props := propagation.New(propagation.WithExtractors(ootaProp))
+		ctx := propagation.ExtractHTTP(bg, props, ns)
+		sc := trace.RemoteSpanContextFromContext(ctx)
+		require.True(t, sc.IsValid(), "oota prop failed sanity check")
+	}
+	// sanity check for real propagators
+	for _, prop := range testProps {
```
Comment (seh) [inline api/trace/testtrace/propagator_test.go:82]: Consider a comment here that indicates we're confirming that the real propagators fail to extract a valid span context when no HTTP headers are available.

File: api/trace/testtrace/propagator_test.go [hunk 5]
```diff
@@ -0,0 +1,94 @@
...
+		sc := trace.RemoteSpanContextFromContext(ctx)
+		require.Falsef(t, sc.IsValid(), "%#v failed sanity check")
+	}
+	for _, prop := range testProps {
+		props := propagation.New(propagation.WithExtractors(ootaProp, prop))
+		ctx := propagation.ExtractHTTP(bg, props, ns)
+		sc := trace.RemoteSpanContextFromContext(ctx)
+		assert.Truef(t, sc.IsValid(), "%#v clobbers span context", prop)
+	}
+}
```
Comment (seh) [inline api/trace/testtrace/propagator_test.go:94]: Additional test cases, while we're here: permute pairs of the propagator set, including `outOfThinAirPropagator` in each pair, to confirm that they yield the expected result in either order. Since our set is so small, we can expand that permutation by hand.

First Propagator | Second Propagator | Novel
--- | --- | ---
`outOfThinAirPropagator` | `TraceContext` | false
`TraceContext` | `outOfThinAirPropagator` | true
`outOfThinAirPropagator` | `B3` (single) | false
`B3` (single) | `outOfThinAirPropagator` | true
`outOfThinAirPropagator` | `B3` (multiple) | false
`B3` (multiple) | `outOfThinAirPropagator` | true

We could add a second loop that takes the current `prop` and `ootaProp` and puts them in one order, than the other, which covers that whole table.

It's not worth pairing `TraceContext` and `B3` with no `outOfThinAirPropagator` in the chain, because you're not supplying an HTTP headers for them to extract.

File: api/trace/testtrace/propagator_test.go (hunk 1 above)
Comment (MrAlias) [reply api/trace/testtrace/propagator_test.go:86]: derp, :facepalm:, yes `prop`.

File: api/trace/testtrace/propagator_test.go (hunk 5 above)
Comment (seh) [reply api/trace/testtrace/propagator_test.go:94]: Thinking about this more overnight, I withdraw this suggestion. It would only be proving that `outOfThinAirPropagator` works when receiving what should be an empty span context.

I apologize for posting the suggestion before having thought through it more carefully.

File: api/trace/trace_context_propagator.go (hunk 2 above)
Comment (krnowak) [reply api/trace/trace_context_propagator.go:60]: Not really. The bool value would provide a redundant information, together with an invalid span context. And my thinking is that checking `TraceID.IsValid` is not much of a bottleneck - it's likely that golang is basically using some optimized-to-death version of memcmp. At least I haven't profiled it yet. :)

File: api/trace/b3_propagator.go (hunk 3 above)
Comment (krnowak) [reply api/trace/b3_propagator.go:85]: Same here.

File: api/trace/trace_context_propagator.go (hunk 2 above)
Comment (seh) [reply api/trace/trace_context_propagator.go:60]: Fair enough. I appreciate the discussion.

File: api/trace/testtrace/propagator_test.go (hunk 1 above)
Comment (krnowak) [reply api/trace/testtrace/propagator_test.go:86]: Thanks for spotting, the linters we use are not clever enough to spot the formatting issues on functions outside the `fmt` package.

File: api/trace/testtrace/propagator_test.go (hunk 4 above)
Comment (krnowak) [reply api/trace/testtrace/propagator_test.go:82]: Done.

File: api/trace/testtrace/propagator_test.go (hunk 5 above)
Comment (krnowak) [reply api/trace/testtrace/propagator_test.go:94]: It's fine. A bunch of sleep never harmed anyone. :)

**Comment by krnowak** [comment]
Updated and rebased.
