### PR TITLE
Replace recordingSpan attributes implementation with slice of attributes

### LINKED ISSUE #2402: Improve Span benchmarks
### Problem Statement

Span creation is very expensive.

### Proposed Solution

We can significantly reduce the number of allocations needed for a new span in the `sdk/trace` package. In particular:

1. The two `evictedQueue` pointers can be replaced with structs, the extra space used looks far less expensive than two compulsory allocations. I.e., change to structs will reduce two allocations:
```
	events evictedQueue
	links evictedQueue
```
2. The `attributesMap` type is heavyweight and IMO should be discarded. There's no need to dynamically compute the current set of attributes in order to calculate the number of attributes dropped. These can be lazily computed, so that new span construction costs less. It is still necessary to compute the distinct set of attributes, but this can be done using the `attribute.NewSet()` call which is optimized to avoid constructing a map. (It uses a stable sort and linear scan to de-duplicate.) This can eliminate three allocations. See `attribute.NewSetWithSortable`, if the `recordingSpan` stores an `attribute.Sortable` in the first place this avoids another alloc.
3. The fixes described in #2065

#### Alternatives

See how in https://github.com/open-telemetry/opentelemetry-go-contrib/pull/1379 I have trouble with test timeouts for the probability sampler. Instead of improving span creation, we could have slow tests with increased timeouts. With the optimizations described in this issue we should be able to make those tests 4x faster.

### LINKED ISSUE #2554: Span attribute drop logic does not comply with the specification.
### Description

Currently the trace SDK drops attributes based on a least-recently-used algorithm: the most recently unique attributes added are kept and the oldest not updated attributes are dropped when capacity is reached. However, [the specification states](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.8.0/specification/common/common.md):

> for each unique attributes key, addition of which would result in exceeding the limit, SDK MUST discard that key/value pair

Meaning if a user adds an attribute after capacity is reached that attribute (if it has a unique key) should be dropped. This is not the behavior currently implemented.

### Environment

- opentelemetry-go version: v1.3.0

### Steps To Reproduce

```go
package trace // import "go.opentelemetry.io/otel/sdk/trace"

import (
	"context"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/otel/attribute"
)

func TestSpanAttributeCapacityDropOrder(t *testing.T) {
	// The tracing specification states:
	//
	//   For each unique attribute key, addition of which would result in
	//   exceeding the limit, SDK MUST discard that key/value pair
	//
	// Therefore, adding attributes after the capacity is reached should
	// result in those attributes being dropped.

	const (
		instName = "TestSpanAttributeCapacityDropOrder"
		spanName = "test span"
	)

	te := NewTestExporter()
	tp := NewTracerProvider(
		WithSyncer(te),
		WithSpanLimits(SpanLimits{AttributeCountLimit: 1}),
	)
	attrs := []attribute.KeyValue{
		attribute.String("key1", "value1"),
		attribute.String("key2", "value2"),
	}

	_, span := tp.Tracer(instName).Start(context.Background(), spanName)
	span.SetAttributes(attrs[0])
	// These should be dropped based on limits.
	span.SetAttributes(attrs[1])
	span.SetAttributes(attrs...)
	span.End()

	got, ok := te.GetSpan(spanName)
	require.Truef(t, ok, "span %s not exported", spanName)
	assert.Equal(t, attrs[:1], got.attributes)
}
```

### Expected behavior

The included test should pass and the first attributes a user passes should be preserved.

### PR DESCRIPTION
**Pull request by MrAlias**
This is an alternate implementation to https://github.com/open-telemetry/opentelemetry-go/pull/2555. It is preferred to that PR because it realizes similar gains but maintains the order of attributes (in the order the user added them).

Instead of an LRU strategy for cap-ing span attributes, comply with the specification and drop last added. To do this, the attributesmap is replaced with a slice of attributes.

- Resolves #2554
- Is the last item to address and closes #2402

### Testing performance comparison

This looks to have considerable memory and allocation reduction and faster computations when compared to [`main`](https://github.com/open-telemetry/opentelemetry-go/tree/d5292e3cd1c2ff1d759aacc5959243520000ce0a).

```
$ benchstat bench-main-53ead308 bench-recordingSpan-attrs-slice-326b6462

name                                          old time/op    new time/op    delta
SpanProcessor-8                                 14.9µs ±10%    11.3µs ±11%  -24.29%  (p=0.000 n=8+10)
SpanProcessorVerboseLogging-8                   15.5µs ± 3%    12.1µs ± 6%  -22.01%  (p=0.000 n=8+9)
StartEndSpan/AlwaysSample-8                      978ns ±14%     636ns ± 5%  -35.00%  (p=0.000 n=10+10)
StartEndSpan/NeverSample-8                       367ns ± 2%     313ns ± 2%  -14.96%  (p=0.000 n=8+9)
SpanSetAttributesOverCapacity-8                 23.1µs ± 5%     2.2µs ± 3%  -90.29%  (p=0.000 n=10+9)
SpanWithAttributes_4/AlwaysSample-8             1.85µs ± 5%    1.18µs ± 3%  -36.22%  (p=0.000 n=8+9)
SpanWithAttributes_4/NeverSample-8               513ns ± 7%     468ns ± 1%   -8.94%  (p=0.000 n=9+7)
SpanWithAttributes_8/AlwaysSample-8             2.68µs ± 5%    1.62µs ± 4%  -39.66%  (p=0.000 n=8+9)
SpanWithAttributes_8/NeverSample-8               679ns ± 5%     620ns ± 3%   -8.65%  (p=0.000 n=8+9)
SpanWithAttributes_all/AlwaysSample-8           2.09µs ± 7%    1.48µs ± 3%  -29.13%  (p=0.000 n=9+9)
SpanWithAttributes_all/NeverSample-8             566ns ± 5%     507ns ± 6%  -10.57%  (p=0.000 n=8+10)
SpanWithAttributes_all_2x/AlwaysSample-8        3.72µs ±12%    2.11µs ± 4%  -43.20%  (p=0.000 n=10+10)
SpanWithAttributes_all_2x/NeverSample-8          753ns ± 6%     692ns ± 6%   -8.15%  (p=0.000 n=8+10)
SpanWithEvents_4/AlwaysSample-8                 2.04µs ± 7%    1.50µs ± 2%  -26.61%  (p=0.000 n=10+7)
SpanWithEvents_4/NeverSample-8                   386ns ± 3%     322ns ± 3%  -16.46%  (p=0.000 n=9+10)
SpanWithEvents_8/AlwaysSample-8                 3.02µs ± 3%    2.27µs ± 1%  -24.75%  (p=0.000 n=9+8)
SpanWithEvents_8/NeverSample-8                   395ns ± 8%     333ns ± 3%  -15.68%  (p=0.000 n=10+10)
SpanWithEvents_WithStackTrace/AlwaysSample-8    1.26µs ± 8%    0.91µs ± 2%  -28.15%  (p=0.000 n=10+10)
SpanWithEvents_WithStackTrace/NeverSample-8      423ns ±10%     363ns ± 8%  -14.03%  (p=0.000 n=9+10)
SpanWithEvents_WithTimestamp/AlwaysSample-8     1.24µs ± 5%    0.92µs ± 2%  -25.81%  (p=0.000 n=10+8)
SpanWithEvents_WithTimestamp/NeverSample-8       470ns ± 2%     408ns ± 1%  -13.17%  (p=0.000 n=10+9)
TraceID_DotString-8                             82.2ns ± 5%    81.9ns ± 2%     ~     (p=0.897 n=10+8)
SpanID_DotString-8                              62.3ns ± 2%    61.5ns ± 2%     ~     (p=0.052 n=10+10)

name                                          old alloc/op   new alloc/op   delta
SpanProcessor-8                                 12.3kB ± 0%     8.4kB ± 0%  -31.29%  (p=0.000 n=10+10)
SpanProcessorVerboseLogging-8                   13.4kB ± 0%     9.6kB ± 0%  -28.62%  (p=0.000 n=10+9)
StartEndSpan/AlwaysSample-8                       816B ± 0%      432B ± 0%  -47.06%  (p=0.000 n=10+10)
StartEndSpan/NeverSample-8                        224B ± 0%      128B ± 0%  -42.86%  (p=0.000 n=10+10)
SpanSetAttributesOverCapacity-8                 15.4kB ± 0%     0.5kB ± 0%  -96.77%  (p=0.000 n=10+10)
SpanWithAttributes_4/AlwaysSample-8             1.73kB ± 0%    1.14kB ± 0%  -34.26%  (p=0.000 n=10+10)
SpanWithAttributes_4/NeverSample-8                480B ± 0%      384B ± 0%  -20.00%  (p=0.000 n=10+10)
SpanWithAttributes_8/AlwaysSample-8             2.43kB ± 0%    1.90kB ± 0%  -21.71%  (p=0.000 n=10+10)
SpanWithAttributes_8/NeverSample-8                736B ± 0%      640B ± 0%  -13.04%  (p=0.000 n=10+10)
SpanWithAttributes_all/AlwaysSample-8           1.90kB ± 0%    1.71kB ± 0%  -10.08%  (p=0.000 n=10+10)
SpanWithAttributes_all/NeverSample-8              544B ± 0%      448B ± 0%  -17.65%  (p=0.000 n=10+10)
SpanWithAttributes_all_2x/AlwaysSample-8        3.20kB ± 0%    3.06kB ± 0%   -4.62%  (p=0.000 n=10+10)
SpanWithAttributes_all_2x/NeverSample-8           864B ± 0%      768B ± 0%  -11.11%  (p=0.000 n=10+10)
SpanWithEvents_4/AlwaysSample-8                 1.50kB ± 0%    0.86kB ± 0%  -42.55%  (p=0.000 n=10+10)
SpanWithEvents_4/NeverSample-8                    224B ± 0%      128B ± 0%  -42.86%  (p=0.000 n=10+10)
SpanWithEvents_8/AlwaysSample-8                 2.21kB ± 0%    1.31kB ± 0%  -40.58%  (p=0.000 n=10+10)
SpanWithEvents_8/NeverSample-8                    224B ± 0%      128B ± 0%  -42.86%  (p=0.000 n=10+10)
SpanWithEvents_WithStackTrace/AlwaysSample-8      992B ± 0%      544B ± 0%  -45.16%  (p=0.000 n=10+10)
SpanWithEvents_WithStackTrace/NeverSample-8       240B ± 0%      144B ± 0%  -40.00%  (p=0.000 n=10+10)
SpanWithEvents_WithTimestamp/AlwaysSample-8     1.02kB ± 0%    0.57kB ± 0%  -44.09%  (p=0.000 n=10+10)
SpanWithEvents_WithTimestamp/NeverSample-8        264B ± 0%      168B ± 0%  -36.36%  (p=0.000 n=10+10)

name                                          old allocs/op  new allocs/op  delta
SpanProcessor-8                                   85.0 ± 0%      35.0 ± 0%  -58.82%  (p=0.000 n=10+10)
SpanProcessorVerboseLogging-8                     91.0 ± 0%      41.0 ± 0%  -54.95%  (p=0.000 n=10+10)
StartEndSpan/AlwaysSample-8                       7.00 ± 0%      2.00 ± 0%  -71.43%  (p=0.000 n=10+10)
StartEndSpan/NeverSample-8                        3.00 ± 0%      2.00 ± 0%  -33.33%  (p=0.000 n=10+10)
SpanSetAttributesOverCapacity-8                    264 ± 0%         3 ± 0%  -98.86%  (p=0.000 n=10+10)
SpanWithAttributes_4/AlwaysSample-8               17.0 ± 0%       6.0 ± 0%  -64.71%  (p=0.000 n=10+10)
SpanWithAttributes_4/NeverSample-8                4.00 ± 0%      3.00 ± 0%  -25.00%  (p=0.000 n=10+10)
SpanWithAttributes_8/AlwaysSample-8               25.0 ± 0%       7.0 ± 0%  -72.00%  (p=0.000 n=10+10)
SpanWithAttributes_8/NeverSample-8                4.00 ± 0%      3.00 ± 0%  -25.00%  (p=0.000 n=10+10)
SpanWithAttributes_all/AlwaysSample-8             19.0 ± 0%       7.0 ± 0%  -63.16%  (p=0.000 n=10+10)
SpanWithAttributes_all/NeverSample-8              4.00 ± 0%      3.00 ± 0%  -25.00%  (p=0.000 n=10+10)
SpanWithAttributes_all_2x/AlwaysSample-8          30.0 ± 0%       8.0 ± 0%  -73.33%  (p=0.000 n=10+10)
SpanWithAttributes_all_2x/NeverSample-8           4.00 ± 0%      3.00 ± 0%  -25.00%  (p=0.000 n=10+10)
SpanWithEvents_4/AlwaysSample-8                   18.0 ± 0%       9.0 ± 0%  -50.00%  (p=0.000 n=10+10)
SpanWithEvents_4/NeverSample-8                    3.00 ± 0%      2.00 ± 0%  -33.33%  (p=0.000 n=10+10)
SpanWithEvents_8/AlwaysSample-8                   27.0 ± 0%      14.0 ± 0%  -48.15%  (p=0.000 n=10+10)
SpanWithEvents_8/NeverSample-8                    3.00 ± 0%      2.00 ± 0%  -33.33%  (p=0.000 n=10+10)
SpanWithEvents_WithStackTrace/AlwaysSample-8      11.0 ± 0%       5.0 ± 0%  -54.55%  (p=0.000 n=10+10)
SpanWithEvents_WithStackTrace/NeverSample-8       4.00 ± 0%      3.00 ± 0%  -25.00%  (p=0.000 n=10+10)
SpanWithEvents_WithTimestamp/AlwaysSample-8       12.0 ± 0%       6.0 ± 0%  -50.00%  (p=0.000 n=10+10)
SpanWithEvents_WithTimestamp/NeverSample-8        5.00 ± 0%      4.00 ± 0%  -20.00%  (p=0.000 n=10+10)
```

### CODE REVIEW

**Comment by MrAlias** [comment]
Here is a benchmark showing the comparison between main, https://github.com/open-telemetry/opentelemetry-go/pull/2555, and this PR

<table class='benchstat '>
<tr class='configs'><th><th><a href=https://github.com/open-telemetry/opentelemetry-go/tree/d5292e3cd1c2ff1d759aacc5959243520000ce0a><code>main</code></a><th><a href=https://github.com/open-telemetry/opentelemetry-go/pull/2555>#2555</a><th><a href=https://github.com/open-telemetry/opentelemetry-go/pull/2576>this PR</a>


<tbody>
<tr><th><th colspan='3' class='metric'>time/op
<tr><td>AttributesMapToKeyValue-8<td>3.21µs ±12%<td><td>
<tr><td>SpanProcessor-8<td>14.9µs ±10%<td>12.6µs ± 9%<td>11.3µs ±11%
<tr><td>SpanProcessorVerboseLogging-8<td>15.5µs ± 3%<td>12.8µs ±16%<td>12.1µs ± 6%
<tr><td>StartEndSpan/AlwaysSample-8<td>978ns ±14%<td>708ns ±24%<td>636ns ± 5%
<tr><td>StartEndSpan/NeverSample-8<td>367ns ± 2%<td>312ns ± 9%<td>313ns ± 2%
<tr><td>SpanSetAttributesOverCapacity-8<td>23.1µs ± 5%<td>2.3µs ±13%<td>2.2µs ± 3%
<tr><td>SpanWithAttributes_4/AlwaysSample-8<td>1.85µs ± 5%<td>1.28µs ±11%<td>1.18µs ± 3%
<tr><td>SpanWithAttributes_4/NeverSample-8<td>513ns ± 7%<td>481ns ± 5%<td>468ns ± 1%
<tr><td>SpanWithAttributes_8/AlwaysSample-8<td>2.68µs ± 5%<td>1.60µs ± 5%<td>1.62µs ± 4%
<tr><td>SpanWithAttributes_8/NeverSample-8<td>679ns ± 5%<td>644ns ± 7%<td>620ns ± 3%
<tr><td>SpanWithAttributes_all/AlwaysSample-8<td>2.09µs ± 7%<td>1.36µs ± 3%<td>1.48µs ± 3%
<tr><td>SpanWithAttributes_all/NeverSample-8<td>566ns ± 5%<td>508ns ± 7%<td>507ns ± 6%
<tr><td>SpanWithAttributes_all_2x/AlwaysSample-8<td>3.72µs ±12%<td>2.57µs ± 9%<td>2.11µs ± 4%
<tr><td>SpanWithAttributes_all_2x/NeverSample-8<td>753ns ± 6%<td>690ns ± 8%<td>692ns ± 6%
<tr><td>SpanWithEvents_4/AlwaysSample-8<td>2.04µs ± 7%<td>1.55µs ± 9%<td>1.50µs ± 2%
<tr><td>SpanWithEvents_4/NeverSample-8<td>386ns ± 3%<td>324ns ± 7%<td>322ns ± 3%
<tr><td>SpanWithEvents_8/AlwaysSample-8<td>3.02µs ± 3%<td>2.32µs ± 8%<td>2.27µs ± 1%
<tr><td>SpanWithEvents_8/NeverSample-8<td>395ns ± 8%<td>339ns ± 7%<td>333ns ± 3%
<tr><td>SpanWithEvents_WithStackTrace/AlwaysSample-8<td>1.26µs ± 8%<td>1.01µs ±12%<td>0.91µs ± 2%
<tr><td>SpanWithEvents_WithStackTrace/NeverSample-8<td>423ns ±10%<td>378ns ±16%<td>363ns ± 8%
<tr><td>SpanWithEvents_WithTimestamp/AlwaysSample-8<td>1.24µs ± 5%<td>0.98µs ± 9%<td>0.92µs ± 2%
<tr><td>SpanWithEvents_WithTimestamp/NeverSample-8<td>470ns ± 2%<td>418ns ± 8%<td>408ns ± 1%
<tr><td>TraceID_DotString-8<td>82.2ns ± 5%<td>84.2ns ±10%<td>81.9ns ± 2%
<tr><td>SpanID_DotString-8<td>62.3ns ± 2%<td>62.7ns ± 6%<td>61.5ns ± 2%
<tr><td>&nbsp;
</tbody>

<tbody>
<tr><th><th colspan='3' class='metric'>alloc/op
<tr><td>AttributesMapToKeyValue-8<td><td><td>
<tr><td>SpanProcessor-8<td>12.3kB ± 0%<td>8.6kB ± 0%<td>8.4kB ± 0%
<tr><td>SpanProcessorVerboseLogging-8<td>13.4kB ± 0%<td>9.7kB ± 0%<td>9.6kB ± 0%
<tr><td>StartEndSpan/AlwaysSample-8<td>816B ± 0%<td>448B ± 0%<td>432B ± 0%
<tr><td>StartEndSpan/NeverSample-8<td>224B ± 0%<td>128B ± 0%<td>128B ± 0%
<tr><td>SpanSetAttributesOverCapacity-8<td>15.4kB ± 0%<td>1.0kB ± 0%<td>0.5kB ± 0%
<tr><td>SpanWithAttributes_4/AlwaysSample-8<td>1.73kB ± 0%<td>1.28kB ± 0%<td>1.14kB ± 0%
<tr><td>SpanWithAttributes_4/NeverSample-8<td>480B ± 0%<td>384B ± 0%<td>384B ± 0%
<tr><td>SpanWithAttributes_8/AlwaysSample-8<td>2.43kB ± 0%<td>1.54kB ± 0%<td>1.90kB ± 0%
<tr><td>SpanWithAttributes_8/NeverSample-8<td>736B ± 0%<td>640B ± 0%<td>640B ± 0%
<tr><td>SpanWithAttributes_all/AlwaysSample-8<td>1.90kB ± 0%<td>1.34kB ± 0%<td>1.71kB ± 0%
<tr><td>SpanWithAttributes_all/NeverSample-8<td>544B ± 0%<td>448B ± 0%<td>448B ± 0%
<tr><td>SpanWithAttributes_all_2x/AlwaysSample-8<td>3.20kB ± 0%<td>2.83kB ± 0%<td>3.06kB ± 0%
<tr><td>SpanWithAttributes_all_2x/NeverSample-8<td>864B ± 0%<td>768B ± 0%<td>768B ± 0%
<tr><td>SpanWithEvents_4/AlwaysSample-8<td>1.50kB ± 0%<td>0.88kB ± 0%<td>0.86kB ± 0%
<tr><td>SpanWithEvents_4/NeverSample-8<td>224B ± 0%<td>128B ± 0%<td>128B ± 0%
<tr><td>SpanWithEvents_8/AlwaysSample-8<td>2.21kB ± 0%<td>1.33kB ± 0%<td>1.31kB ± 0%
<tr><td>SpanWithEvents_8/NeverSample-8<td>224B ± 0%<td>128B ± 0%<td>128B ± 0%
<tr><td>SpanWithEvents_WithStackTrace/AlwaysSample-8<td>992B ± 0%<td>560B ± 0%<td>544B ± 0%
<tr><td>SpanWithEvents_WithStackTrace/NeverSample-8<td>240B ± 0%<td>144B ± 0%<td>144B ± 0%
<tr><td>SpanWithEvents_WithTimestamp/AlwaysSample-8<td>1.02kB ± 0%<td>0.58kB ± 0%<td>0.57kB ± 0%
<tr><td>SpanWithEvents_WithTimestamp/NeverSample-8<td>264B ± 0%<td>168B ± 0%<td>168B ± 0%
<tr><td>TraceID_DotString-8<td><td><td>
<tr><td>SpanID_DotString-8<td><td><td>
<tr><td>&nbsp;
</tbody>

<tbody>
<tr><th><th colspan='3' class='metric'>allocs/op
<tr><td>AttributesMapToKeyValue-8<td><td><td>
<tr><td>SpanProcessor-8<td>85.0 ± 0%<td>45.0 ± 0%<td>35.0 ± 0%
<tr><td>SpanProcessorVerboseLogging-8<td>91.0 ± 0%<td>51.0 ± 0%<td>41.0 ± 0%
<tr><td>StartEndSpan/AlwaysSample-8<td>7.00 ± 0%<td>3.00 ± 0%<td>2.00 ± 0%
<tr><td>StartEndSpan/NeverSample-8<td>3.00 ± 0%<td>2.00 ± 0%<td>2.00 ± 0%
<tr><td>SpanSetAttributesOverCapacity-8<td>264 ± 0%<td>4 ± 0%<td>3 ± 0%
<tr><td>SpanWithAttributes_4/AlwaysSample-8<td>17.0 ± 0%<td>5.0 ± 0%<td>6.0 ± 0%
<tr><td>SpanWithAttributes_4/NeverSample-8<td>4.00 ± 0%<td>3.00 ± 0%<td>3.00 ± 0%
<tr><td>SpanWithAttributes_8/AlwaysSample-8<td>25.0 ± 0%<td>5.0 ± 0%<td>7.0 ± 0%
<tr><td>SpanWithAttributes_8/NeverSample-8<td>4.00 ± 0%<td>3.00 ± 0%<td>3.00 ± 0%
<tr><td>SpanWithAttributes_all/AlwaysSample-8<td>19.0 ± 0%<td>5.0 ± 0%<td>7.0 ± 0%
<tr><td>SpanWithAttributes_all/NeverSample-8<td>4.00 ± 0%<td>3.00 ± 0%<td>3.00 ± 0%
<tr><td>SpanWithAttributes_all_2x/AlwaysSample-8<td>30.0 ± 0%<td>6.0 ± 0%<td>8.0 ± 0%
<tr><td>SpanWithAttributes_all_2x/NeverSample-8<td>4.00 ± 0%<td>3.00 ± 0%<td>3.00 ± 0%
<tr><td>SpanWithEvents_4/AlwaysSample-8<td>18.0 ± 0%<td>10.0 ± 0%<td>9.0 ± 0%
<tr><td>SpanWithEvents_4/NeverSample-8<td>3.00 ± 0%<td>2.00 ± 0%<td>2.00 ± 0%
<tr><td>SpanWithEvents_8/AlwaysSample-8<td>27.0 ± 0%<td>15.0 ± 0%<td>14.0 ± 0%
<tr><td>SpanWithEvents_8/NeverSample-8<td>3.00 ± 0%<td>2.00 ± 0%<td>2.00 ± 0%
<tr><td>SpanWithEvents_WithStackTrace/AlwaysSample-8<td>11.0 ± 0%<td>6.0 ± 0%<td>5.0 ± 0%
<tr><td>SpanWithEvents_WithStackTrace/NeverSample-8<td>4.00 ± 0%<td>3.00 ± 0%<td>3.00 ± 0%
<tr><td>SpanWithEvents_WithTimestamp/AlwaysSample-8<td>12.0 ± 0%<td>7.0 ± 0%<td>6.0 ± 0%
<tr><td>SpanWithEvents_WithTimestamp/NeverSample-8<td>5.00 ± 0%<td>4.00 ± 0%<td>4.00 ± 0%
<tr><td>TraceID_DotString-8<td><td><td>
<tr><td>SpanID_DotString-8<td><td><td>
<tr><td>&nbsp;
</tbody>

</table>

File: sdk/trace/tracer.go [hunk 1]
```diff
@@ -122,12 +122,19 @@ func (tr *tracer) newRecordingSpan(psc, sc trace.SpanContext, name string, sr Sa
 	}
 
 	s := &recordingSpan{
+		// Do not pre-allocate the attributes slice here! Doing so will
+		// allocate memory that is likely never going to be used, or if used,
+		// will be over-sized. The default Go compiler has been tested to
+		// dynamically allocate needed space very well. Benchmarking has shown
+		// it to be more performant than what we can predetermine here,
+		// especially for the common use case of little to now added
```
Comment (Aneurysm9) [inline sdk/trace/tracer.go:130]:
```suggestion
		// especially for the common use case of few to no added
```

**Review by Aneurysm9 — APPROVED** [review]

**Review by jmacd — APPROVED** [review]
💯
