### PR TITLE
Use port 4318 for otlp*http client default

### LINKED ISSUE #2614: Collector and http client port mismatch
### Description

otlptracehttp client defaults to port 4317, but collector spec says http uses 4318. (4317 is for grpc).

- https://github.com/open-telemetry/opentelemetry-go/blob/bd817df68c274fbace901fab63da2bea267315ab/exporters/otlp/otlptrace/otlptracehttp/options.go#L58
- https://github.com/open-telemetry/opentelemetry-collector/blob/fb1539f7e57b782c2419115c602fff9a356040db/receiver/otlpreceiver/README.md#getting-started
  - `endpoint (default = 0.0.0.0:4317 for grpc protocol, 0.0.0.0:4318 http protocol):`, 

### Environment

```
	go.opentelemetry.io/otel/exporters/otlp/otlptrace v1.4.0
	go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp v1.4.0
	go.opentelemetry.io/otel/sdk v1.4.0
	go.opentelemetry.io/otel/trace v1.4.0
```

### Steps To Reproduce

1. N/A

### Expected behavior

I would expect the http client to default to port 4318, such that it is aligned with the port expected by the collector.

### PR DESCRIPTION
**Pull request by MrAlias**
As per [the specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/exporter.md#configuration-options) and the collector defaults, use port `4318` as the default for HTTP communication.

Fix #2614

### CODE REVIEW

**Review by Aneurysm9 — APPROVED** [review]

File: exporters/otlp/otlpmetric/internal/otlpconfig/options.go [hunk 1]
```diff
@@ -72,24 +74,52 @@ type (
...
+		tmp := strings.TrimSpace(*pathPtr)
+		if tmp == "" {
+			tmp = defaultPath
+		} else {
+			tmp = path.Clean(tmp)
+			if !path.IsAbs(tmp) {
+				tmp = fmt.Sprintf("/%s", tmp)
+			}
+		}
+		*pathPtr = tmp
```
Comment (XSAM) [inline exporters/otlp/otlpmetric/internal/otlpconfig/options.go:106]: I am not sure why to use this strange `range` style to format `cfg.Metrics.URLPath`.

Codes like this can do the same job but clear.

```go
	tmp := strings.TrimSpace(cfg.Metrics.URLPath)
	if tmp == "" {
		tmp = DefaultMetricsPath
	} else {
		tmp = path.Clean(tmp)
		if !path.IsAbs(tmp) {
			tmp = fmt.Sprintf("/%s", tmp)
		}
	}
	cfg.Metrics.URLPath = tmp
```

File: exporters/otlp/otlptrace/internal/otlpconfig/options.go [hunk 2]
```diff
@@ -65,24 +67,52 @@ type (
...
+		if tmp == "" {
+			tmp = defaultPath
+		} else {
+			tmp = path.Clean(tmp)
+			if !path.IsAbs(tmp) {
+				tmp = fmt.Sprintf("/%s", tmp)
+			}
+		}
+		*pathPtr = tmp
+	}
```
Comment (XSAM) [inline exporters/otlp/otlptrace/internal/otlpconfig/options.go:100]: same question here.

File: exporters/otlp/otlpmetric/internal/otlpconfig/options.go (hunk 1 above)
Comment (MrAlias) [reply exporters/otlp/otlpmetric/internal/otlpconfig/options.go:106]: Sure. I was just copying this from the unified location of the `NewClient` code to make it clear the main purpose of this PR, but I can update these as well.

**Review by XSAM — APPROVED** [review]

File: exporters/otlp/otlpmetric/internal/otlpconfig/options.go [hunk 3]
```diff
@@ -72,24 +74,48 @@ type (
...
 		},
 		RetryConfig: retry.DefaultConfig,
 	}
+	cfg = ApplyHTTPEnvConfigs(cfg)
+	for _, opt := range opts {
+		cfg = opt.ApplyHTTPOption(cfg)
+	}
 
-	return c
+	tmp := strings.TrimSpace(cfg.Metrics.URLPath)
```
Comment (dmathieu) [inline exporters/otlp/otlpmetric/internal/otlpconfig/options.go:94]: (probably for another PR): this is repeated in the trace exporter as well. How about a shared `CleanPathOr(path, default)` method?

File: exporters/otlp/otlpmetric/otlpmetrichttp/options.go [hunk 4]
```diff
@@ -40,6 +40,14 @@ type Option interface {
 	applyHTTPOption(otlpconfig.Config) otlpconfig.Config
 }
 
+func asHTTPOptions(opts []Option) []otlpconfig.HTTPOption {
```
Comment (dmathieu) [inline exporters/otlp/otlpmetric/otlpmetrichttp/options.go:43]: (maybe for another PR too)
This is repeated quite a few times in both metric and tracer. How about sharing it?

File: exporters/otlp/otlpmetric/internal/otlpconfig/options.go (hunk 3 above)
Comment (MrAlias) [reply exporters/otlp/otlpmetric/internal/otlpconfig/options.go:94]: I'm in favor of the unification of this shared functionality, but I do not want to include it in this PR. This PR is intended to primarily resolve #2614, adding such unification would overload the PR.

File: exporters/otlp/otlpmetric/otlpmetrichttp/options.go (hunk 4 above)
Comment (MrAlias) [reply exporters/otlp/otlpmetric/otlpmetrichttp/options.go:43]: It is actually not a shared function. The arguments are slices of different types.
