### PR TITLE
Fix empty log body printed by stdoutlog exporter

### LINKED ISSUE #5310: OTel Log stdout Body shows as empty
### Description

I am trying to use OTel logger with simple stdout and the Body is just not outputted

### Environment

- OS:  Mac
- Architecture: ARM
- Go Version: 1.22
- opentelemetry-go version: Release v1.26.0/v0.48.0/v0.2.0-alpha

### Steps To Reproduce
```go
package main

import (
	"context"
	"fmt"
	"time"

	"go.opentelemetry.io/otel/exporters/stdout/stdoutlog"
	log2 "go.opentelemetry.io/otel/log"
	"go.opentelemetry.io/otel/sdk/log"
)

func main() {
	processor, err := stdoutlog.New()
	if err != nil {
		fmt.Println(err.Error())
		return
	}

	p := log.NewLoggerProvider(log.WithProcessor(log.NewBatchProcessor(processor)))
	l := p.Logger("test-stdout")

	r := log2.Record{}
	r.SetBody(log2.StringValue("This body will not show"))
	r.SetSeverityText("FATAL")
	r.SetSeverity(log2.SeverityFatal)
	l.Emit(context.Background(), r)

	time.Sleep(5 * time.Second)

}
```
Mod:
```
	go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp v0.51.0
	go.opentelemetry.io/otel v1.26.0
	go.opentelemetry.io/otel/metric v1.26.0
	go.opentelemetry.io/otel/trace v1.26.0

	go.opentelemetry.io/otel/exporters/otlp/otlplog/otlploggrpc v0.0.0-20240506090312-e0ed6a3028be // indirect
	go.opentelemetry.io/otel/exporters/otlp/otlplog/otlploghttp v0.2.0-alpha // indirect
	go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetricgrpc v1.26.0 // indirect
	go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetrichttp v1.26.0 // indirect
	go.opentelemetry.io/otel/exporters/otlp/otlptrace v1.26.0 // indirect
	go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc v1.26.0 // indirect
	go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp v1.26.0 // indirect
	go.opentelemetry.io/otel/exporters/stdout/stdoutlog v0.2.0-alpha // indirect
	go.opentelemetry.io/otel/exporters/stdout/stdoutmetric v1.26.0 // indirect
	go.opentelemetry.io/otel/exporters/stdout/stdouttrace v1.26.0 // indirect
	go.opentelemetry.io/otel/log v0.2.0-alpha // indirect
	go.opentelemetry.io/otel/sdk v1.26.0 // indirect
	go.opentelemetry.io/otel/sdk/log v0.2.0-alpha // indirect
	go.opentelemetry.io/otel/sdk/metric v1.26.0 // indirect
	go.opentelemetry.io/proto/otlp v1.2.0 // indirect

```

Output: 
```json
{"Timestamp":"0001-01-01T00:00:00Z","ObservedTimestamp":"2024-05-07T18:32:51.099086+03:00","Severity":21,"SeverityText":"FATAL",
"Body":{},"Attributes":[],"TraceID":"00000000000000000000000000000000","SpanID":"0000000000000000","TraceFlags":"00","Resource":[{"Key":"service.name",
"Value":{"Type":"STRING","Value":"unknown_service:___go_build_playground_git_otel"}},{"Key":"telemetry.sdk.language","Value":{"Type":"STRING","Value":"go"}},
{"Key":"telemetry.sdk.name","Value":{"Type":"STRING","Value":"opentelemetry"}},
{"Key":"telemetry.sdk.version","Value":{"Type":"STRING","Value":"1.26.0"}}],"Scope":{"Name":"test-stdout","Version":"","SchemaURL":""},"AttributeValueLengthLimit":0,"AttributeCountLimit":0}

```

### Expected behavior
`"Body":{}`
should be:
`"Body":{"This body will not show"}`

### PR DESCRIPTION
**Pull request by XSAM**
resolves #5310

### CODE REVIEW

File: log/keyvalue.go [hunk 1]
```diff
@@ -300,6 +301,38 @@ func (v Value) String() string {
 	}
 }
 
+// MarshalJSON implements a custom marshal function to encode Value.
+func (v Value) MarshalJSON() ([]byte, error) {
+	var jsonVal struct {
+		Type  string
+		Value interface{}
```
Comment (pellared) [inline log/keyvalue.go:308]: Cannot we just marshal the value (without the type)?

I guess this is for having the same experience as for `stdouttrace` and `stdoutmetric`. Personally, I do not like it and I would change it there as well.

Probably it would be better to handle it as a separate PR(s) for all stdout exporters.

File: log/keyvalue.go [hunk 2]
```diff
@@ -300,6 +301,38 @@ func (v Value) String() string {
 	}
 }
 
+// MarshalJSON implements a custom marshal function to encode Value.
+func (v Value) MarshalJSON() ([]byte, error) {
```
Comment (pellared) [inline log/keyvalue.go:305]: Can we move the marshaling code to `stdoutlog` (e.g. under `newRecordJSON`).

Take notice that e.g. https://pkg.go.dev/time#Time.MarshalJSON behavior is stable. Maybe in future the OTel Specification will define an official JSON representation of LogRecord (e.g. encoded in the same way as OTLP over JSON)

**Review by pellared — CHANGES_REQUESTED** [review]
We should add `MarshalJSON` to `log.Value`.

File: log/keyvalue.go (hunk 1 above)
Comment (XSAM) [reply log/keyvalue.go:308]: I know having a type is kind of annoying, but this is more like a debug message. It might be better to have a type so users know the concrete value.

For instance, a value can be a byte with `[]byte{5}`, it can also be a string with `BQ==`. The output of these two values will be the same without the type.

**Review by pellared — APPROVED** [review]

**Review by MrAlias — APPROVED** [review]

**Review by dashpole — APPROVED** [review]

**Comment by magodo** [comment]
@pellared, @dashpole Can we make a release for this `go.opentelemetry.io/otel/exporters/stdout/stdoutlog` module, as otherwise the example in https://opentelemetry.io/docs/languages/go/getting-started/ will still print empty body, making new comers confusing?
