### PR TITLE
Un-escape url coding when parsing baggage.

### LINKED ISSUE #2519: Baggage member values are not being decoded when extracted from carriers
### Description

According to the spec, [Baggage header values should be encoded](https://github.com/w3c/baggage/blob/main/baggage/HTTP_HEADER_FORMAT.md#value) in transit. 

The Baggage propagator appears to be [encoding Baggage Member values](https://github.com/open-telemetry/opentelemetry-go/blob/aedef05e953cbca349f1d8b4dfd46f69d96c6a61/baggage/baggage.go#L314) on Inject but never decoding them on Extract. For multiple passive hops, the Baggage Member value will continue getting encoded. 

### Environment

- OS: linux/mac
- Architecture: x86_64
- Go Version: 1.17
- opentelemetry-go version: v1.2.0

### Steps To Reproduce

1. Set a baggage header with a member value that requires encoding
2. Pass the baggage through multiple Inject/Extracts of the Baggage propagator. 

Here's a test to demonstrate the behavior in isolation:
```
func TestBaggage(t *testing.T) {
	propagator := propagation.Baggage{}
	hc := propagation.HeaderCarrier{}
	hc.Set("baggage", "myKey=1%3D1")

	want := "1%3D1"
        ctx := context.Background()

	ctx = propagator.Extract(ctx, hc)
	actual := baggage.FromContext(ctx).Member("myKey").Value()
	require.Equal(t, want, actual)

        // inject will encode the '%' literal from the already encoded value
	propagator.Inject(ctx, hc)

	ctx = propagator.Extract(ctx, hc)
	actual = baggage.FromContext(ctx).Member("myKey").Value()
	require.Equal(t, want, actual) // fail
}
```

### Expected behavior

The Baggage Member value should be decoded when being extracted onto the Context.

### PR DESCRIPTION
**Pull request by MadVikingGod**
Closes #2519 

The W3c Sepc indicates that the value of a baggage member is a URL encoded string.  We currently escape properly when we encode into the header, but we don't unescape when we praise from a header.

This change fixes that and adds tests at the propagator, and baggage level to ensure.

### CODE REVIEW

**Review by Aneurysm9 — APPROVED** [review]
Please add a changelog entry, otherwise LGTM.

**Review by MrAlias — APPROVED** [review]

File: baggage/baggage_test.go [hunk 1]
```diff
@@ -339,6 +339,13 @@ func TestBaggageParse(t *testing.T) {
 				"foo": {Value: "2"},
 			},
 		},
+		{
+			name: "url encoded value",
+			in:   "key1=val%252",
```
Comment (yurishkuro) [inline baggage/baggage_test.go:344]: This test was insufficient. The regexp check now happens _after_ `QueryUnescape`, not at all what was intended in the original code. As a result, valid strings like `val%27` do not pass the check. This specific test does pass because the decoded string `val%2` still "looks like" URL-encoded (i.e. it passes the regex).

Comment (yurishkuro) [reply baggage/baggage_test.go:344]: https://github.com/open-telemetry/opentelemetry-go/issues/3685#issuecomment-1421989032
