### PR TITLE
Format log message before logging with logr

### LINKED ISSUE #4141: Problem with logging after introducing logr
### Description

It seems that the logger is being called with its varargs as format arguments, but logr wants a list of key-values.

### Environment

```go
module main

go 1.19

require (
	github.com/go-logr/stdr v1.2.2
	go.opentelemetry.io/otel v1.16.0
	go.opentelemetry.io/otel/exporters/zipkin v1.16.0
	go.opentelemetry.io/otel/sdk v1.16.0
	go.opentelemetry.io/otel/trace v1.16.0
)

require (
	github.com/go-logr/logr v1.2.4 // indirect
	github.com/openzipkin/zipkin-go v0.4.1 // indirect
	go.opentelemetry.io/otel/metric v1.16.0 // indirect
	golang.org/x/sys v0.8.0 // indirect
)
```

### Steps To Reproduce

```go
package main

import (
	"context"
	"github.com/go-logr/stdr"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/exporters/zipkin"
	sdktrace "go.opentelemetry.io/otel/sdk/trace"
	"go.opentelemetry.io/otel/sdk/trace/tracetest"
	"go.opentelemetry.io/otel/trace"
	"log"
	"os"
	"time"
)

func main() {
	exporter, err := zipkin.New("http://localhost:9411/api/v2/spans", zipkin.WithLogr(stdr.New(log.New(os.Stdout, "", 0))))
	if err != nil {
		log.Fatalf("cannot initialize the application tracer: %v1", err)
	}
	err = exporter.ExportSpans(context.Background(), tracetest.SpanStubs{{
		SpanContext: trace.NewSpanContext(trace.SpanContextConfig{
			TraceID: trace.TraceID{0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F},
			SpanID:  trace.SpanID{0xFF, 0xFE, 0xFD, 0xFC, 0xFB, 0xFA, 0xF9, 0xF8},
		}),
		SpanKind:   trace.SpanKindServer,
		Name:       "foo",
		StartTime:  time.Date(2020, time.March, 11, 19, 24, 0, 0, time.UTC),
		EndTime:    time.Date(2020, time.March, 11, 19, 25, 0, 0, time.UTC),
		Attributes: nil,
		Events:     nil,
		Status: sdktrace.Status{
			Code:        codes.Error,
			Description: "404, file not found",
		},
	}}.Snapshots())
	if err != nil {
		log.Fatalf("error: %v", err)
	}
}
```

It outputs this:
```
"level"=0 "msg"="about to send a POST request to %s with body %s" "<non-string-key: [\"http://localho>"="<no-value>"
```

### Expected behavior

A structured log, something like:
```
"level"=0 "msg"="about to send a POST request" "url"="http://localhost:9411/api/v2/spans" "body"="..."
```

### PR DESCRIPTION
**Pull request by MrAlias**
Fixes #4141

The logr calling convention does not support fmt semantics for message formatting. Format the message before it is sent to logr for logging.

### CODE REVIEW

**Review by Aneurysm9 — APPROVED** [review]

File: exporters/zipkin/zipkin_test.go [hunk 1]
```diff
@@ -31,6 +32,7 @@ import (
 	zkmodel "github.com/openzipkin/zipkin-go/model"
 	"github.com/stretchr/testify/assert"
 	"github.com/stretchr/testify/require"
+	"github.com/tonglil/buflogr"
```
Comment (pellared) [inline exporters/zipkin/zipkin_test.go:35]: Can we use https://pkg.go.dev/github.com/go-logr/logr/funcr#New instead so that we do not introduce a new dependent Go module?

**Review by hanyuancheung — APPROVED** [review]

File: exporters/zipkin/zipkin_test.go [hunk 2]
```diff
@@ -364,3 +366,20 @@ func TestErrorOnExportShutdownExporter(t *testing.T) {
...
+
+	var buf bytes.Buffer
+	l := funcr.New(func(prefix, args string) {
+		_, _ = buf.WriteString(fmt.Sprint(prefix, args))
+	}, funcr.Options{})
+	exp, err := New("", WithLogr(l))
+	require.NoError(t, err)
+	exp.logf(format, args...)
+
+	want := "\"level\"=0 \"msg\"=\"string \\\"s\\\", int 1\""
```
Comment (pellared) [inline exporters/zipkin/zipkin_test.go:382]: Lets make it easier to read 😉 

```suggestion
	want := `"level"=0 "msg"="string \"s\", int 1"`
```

File: exporters/zipkin/zipkin_test.go [hunk 3]
```diff
@@ -364,3 +366,20 @@ func TestErrorOnExportShutdownExporter(t *testing.T) {
...
+	format := "string %q, int %d"
+	args := []interface{}{"s", 1}
+
+	var buf bytes.Buffer
+	l := funcr.New(func(prefix, args string) {
+		_, _ = buf.WriteString(fmt.Sprint(prefix, args))
+	}, funcr.Options{})
+	exp, err := New("", WithLogr(l))
+	require.NoError(t, err)
+	exp.logf(format, args...)
```
Comment (pellared) [inline exporters/zipkin/zipkin_test.go:380]: Just adding a blank line to have the "act" section of the unit test more visible.

```suggestion

	exp.logf(format, args...)
```

File: exporters/zipkin/zipkin_test.go [hunk 4]
```diff
@@ -364,3 +366,20 @@ func TestErrorOnExportShutdownExporter(t *testing.T) {
 	assert.NoError(t, exp.Shutdown(context.Background()))
 	assert.NoError(t, exp.ExportSpans(context.Background(), nil))
 }
+
+func TestLogrFormatting(t *testing.T) {
+	format := "string %q, int %d"
+	args := []interface{}{"s", 1}
```
Comment (pellared) [inline exporters/zipkin/zipkin_test.go:372]: We could inline it to the `exp.logf(format, args...)` invocation.

**Review by pellared — APPROVED** [review]
Just nit suggestions.

**Review by MadVikingGod — APPROVED** [review]

File: exporters/zipkin/zipkin_test.go (hunk 2 above)
Comment (MrAlias) [reply exporters/zipkin/zipkin_test.go:382]: These should be equivalent. I think we can stick with the original.
