### PR TITLE
Fix baggage.NewMember to decode the accepted value

### LINKED ISSUE #3144: Inconsistence of baggage value restriction
### Description

[`Member.String()`](https://github.com/open-telemetry/opentelemetry-go/blob/9c2a0c2d6983cf3db6bb1432dc7d7bf3e391b852/baggage/baggage.go#L359) accpets UTF-8 strings as baggage member values, and URL-encodes them. But it seems this URL-encoding has no effect since `baggage.NewMember()` [does not accept](https://github.com/open-telemetry/opentelemetry-go/blob/9c2a0c2d6983cf3db6bb1432dc7d7bf3e391b852/baggage/baggage.go#L341) UTF-8 strings.

### Environment

- opentelemetry-go version: 1.9.0

### Steps To Reproduce

1. `baggage.NewMember("", ";")` returns an error.

### Expected behavior

`baggage.NewMember("", ";")` does not return errors or `Member.String()` does no URL-encoding.

### PR DESCRIPTION
**Pull request by NewReStarter**
fix #3144 
fix https://github.com/open-telemetry/opentelemetry-go/issues/2523

Function `baggage.NewMember(key, value, props...)` input `value` is decoded and stored after validating the input parameters according to [the W3C specification of baggage value](https://www.w3.org/TR/baggage/#value).

Corresponding test cases are modified so that we can make sure `value` is properly encoded before creating `baggage.Member`.

### CODE REVIEW

**Comment by NewReStarter** [comment]
@MrAlias can you please help approve to run the ci check pipeline?

File: baggage/baggage.go [hunk 1]
```diff
@@ -263,7 +263,15 @@ func NewMember(key, value string, props ...Property) (Member, error) {
 	if err := m.validate(); err != nil {
```
Comment (MrAlias) [inline baggage/baggage.go:263]: The function documentation needs to be updated to clearly inform developers what this function expects.

**Review by MrAlias — COMMENTED** [review]
Does the parse of new baggage work properly? Or does it also need to be included here?

File: baggage/baggage.go (hunk 1 above)
Comment (NewReStarter) [reply baggage/baggage.go:270]: The doc suggests function comment? If so, function comment is added for the input value encoding and decoding clarification.

File: baggage/baggage.go [hunk 2]
```diff
@@ -252,7 +252,14 @@ type Member struct {
 
 // NewMember returns a new Member from the passed arguments. An error is
 // returned if the created Member would be invalid according to the W3C
-// Baggage specification.
+// Baggage specification and an error will be returned if any of the input
+// parameters does not follow the specification.
```
Comment (MrAlias) [inline baggage/baggage.go:256]: This is redundant.

```suggestion
// Baggage specification.
```

It might make more sense to generalize the reason an error is returned in the prior sentence fragment instead of restarting an almost identical idea here.

File: baggage/baggage.go [hunk 3]
```diff
@@ -263,7 +270,14 @@ func NewMember(key, value string, props ...Property) (Member, error) {
 	if err := m.validate(); err != nil {
 		return newInvalidMember(), err
 	}
-
+	// decode the input value so that it can be parsed
+	// and stored properly when used and propagated.
```
Comment (MrAlias) [inline baggage/baggage.go:274]:
```suggestion
```

File: baggage/baggage.go [hunk 4]
```diff
@@ -263,7 +270,14 @@ func NewMember(key, value string, props ...Property) (Member, error) {
...
+	decodedValue, err := url.QueryUnescape(value)
+	if err != nil {
+		return newInvalidMember(),
+			fmt.Errorf("%w: %q", errInvalidValue, value)
```
Comment (MrAlias) [inline baggage/baggage.go:278]:
```suggestion
		return newInvalidMember(), fmt.Errorf("%w: %q", errInvalidValue, value)
```

File: propagation/baggage_test.go [hunk 5]
```diff
@@ -46,8 +47,8 @@ func (m member) Member(t *testing.T) baggage.Member {
 		}
 		props = append(props, p)
 	}
-
-	bMember, err := baggage.NewMember(m.Key, m.Value, props...)
+	// when creating a new Member, NewMember only accepted encoded string as value
```
Comment (MrAlias) [inline propagation/baggage_test.go:50]:
```suggestion
```

File: baggage/baggage.go (hunk 2 above)
Comment (NewReStarter) [reply baggage/baggage.go]: noted, please check the latest version of these comments.

**Comment by NewReStarter** [comment]
@MrAlias thx for the comments. 
changelog is fixed and redundant comments are removed. I also tried to rephrase and simplify the function document of the new `NewMember`. Any further suggestions?

File: CHANGELOG.md [hunk 6]
```diff
@@ -18,6 +18,10 @@ This project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.htm
 - Upgrade `golang.org/x/sys/unix` from `v0.0.0-20210423185535-09eb48e85fd7` to `v0.0.0-20220919091848-fb04ddd9f9c8`.
   This addresses [GO-2022-0493](https://pkg.go.dev/vuln/GO-2022-0493). (#3235)
 
+### Fixed
+
+- Fix function `baggage.NewMember` to decode the `value` parameter instead of directly use it according to the W3C specification. (#3144)
```
Comment (MrAlias) [inline CHANGELOG.md:23]:
```suggestion
- Fix function `baggage.NewMember` to decode the `value` parameter instead of directly use it according to the W3C specification. (#3226 )
```

**Review by MrAlias — APPROVED** [review]

File: CHANGELOG.md (hunk 6 above)
Comment (NewReStarter) [reply CHANGELOG.md]: fixed

Comment (MrAlias) [reply CHANGELOG.md]: This does not appear resolved to me:

**Review by MadVikingGod — APPROVED** [review]

**Comment by yurishkuro** [comment]
I think this PR was invalid (see #3685). It provides no motivation why in-memory storage of the value should be URL-encoded representation. The W3C spec says nothing about internal storage, only wire representation. I could see if this was done for efficiency reasons, but as an end user I should not be concerned with how the baggage is going to be encoded (and W3C is not the only possible format, there may be protocols that support metadata without encoding), I want to use whichever strings make sense in the application.
