### PR TITLE
handle multiples connect start/done trace

### LINKED ISSUE #266: ConnectStart/ConnectDone() called multiple times, causing panic
Stack trace from @austinlparker:

```
11:19 AM
11:19 AM
goroutine 592 [running]:
11:19 AM
go.opentelemetry.io/plugin/httptrace.(*clientTracer).close(0xc00055ec00, 0x828607, 0xc)
11:19 AM
	/app/pkg/mod/go.opentelemetry.io@v0.0.0-20191023164856-8cb378678945/plugin/httptrace/clienttrace.go:79 +0x21f
11:19 AM
go.opentelemetry.io/plugin/httptrace.(*clientTracer).connectDone(...)
11:19 AM
	/app/pkg/mod/go.opentelemetry.io@v0.0.0-20191023164856-8cb378678945/plugin/httptrace/clienttrace.go:125
11:19 AM
net.(*sysDialer).dialSingle.func1(0xc000493cc0, 0xc0004d0f80, 0xc000512bc0, 0xe, 0xc0001b9e00)
11:19 AM
	/tmp/go/src/net/dial.go:571 +0x6b
11:19 AM
net.(*sysDialer).dialSingle(0xc0004d0f80, 0x8b1900, 0xc000483f00, 0x8ad2e0, 0xc000485e30, 0x8b4140, 0xc00031e008, 0x0, 0x0)
11:19 AM
	/tmp/go/src/net/dial.go:594 +0x2fa
11:19 AM
net.(*sysDialer).dialSerial(0xc0004d0f80, 0x8b1900, 0xc000483f00, 0xc000529770, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
11:19 AM
	/tmp/go/src/net/dial.go:546 +0x221
11:19 AM
net.(*sysDialer).dialParallel.func1(0x8b1900, 0xc000483f00, 0xc000529701)
11:19 AM
	/tmp/go/src/net/dial.go:467 +0x95
11:19 AM
created by net.(*sysDialer).dialParallel
11:19 AM
	/tmp/go/src/net/dial.go:482 +0x25a
11:19 AM
exit status 2
```

My analysis:
```
Okay, so this happens in https://github.com/open-telemetry/opentelemetry-go/blob/master/plugin/httptrace/clienttrace.go#L80

this happens when the close() call happens _before_ the open() has happened. because concurrency and goroutines and delayed reporting of HTTP events :/

One solution is to just... not panic and drop the span. I prefer that one. but the other is to actually block and wait for the open span to happen before the close span call is run, if it isn't in the map. *cry*

this used to be worse, it would close the last span reported, rather than closing the correct span. so if run in the wrong order, you'd see open-x, open-y, close-y (meant to close-x), close-??? (uh oh) happening. because of the ordering not being open-close-open-close.

we now deal correctly with open-open-close-open-close-close, but not with close-open.
```

### PR DESCRIPTION
**Pull request by paivagustavo**
Closes #266 

@rghetia I kept your initial changes since I think they are still relevant, hope this is okay.

`ConnectStart` and `ConnectDone` hooks of client trace can be called multiple times for multiple addresses. With this, we are able to create a span for each address that the net/http tries to connect to within this trace.

### CODE REVIEW

File: plugin/httptrace/clienttrace.go [hunk 1]
```diff
@@ -45,112 +44,124 @@ type clientTracer struct {
...
 }
 
 func (ct *clientTracer) connectStart(network, addr string) {
-	ct.open("http.connect")
+	ct.start("http.connect."+addr, "http.connect", HTTPRemoteAddr.String(addr))
 }
 
 func (ct *clientTracer) connectDone(network, addr string, err error) {
-	ct.close("http.connect")
+	ct.end("http.connect." + addr)
```
Comment (lizthegrey) [inline plugin/httptrace/clienttrace.go]: It has always felt strange to me that we don't have the option to pass the `err` as an attribute to end to set it on that span as we close it...

but I guess we currently deal with this by calling `ct.span("http.getconn").SetAttributes(...)` before calling `ct.end()` (which also has its own way of blowing up on the outside case that start/end timing is reversed. shouldn't happen elsewhere in the `http` code as far as I know, buuut...)

File: plugin/httptrace/clienttrace.go [hunk 2]
```diff
@@ -45,112 +44,124 @@ type clientTracer struct {
...
 	}
 	ct.tr = global.TraceProvider().GetTracer("go.opentelemetry.io/otel/plugin/httptrace")
-	ct.open("http.request")
+	ct.start("http.request", "http.request")
 	return ct
 }
 
-func (ct *clientTracer) open(name string, attrs ...core.KeyValue) {
-	_, sp := ct.tr.Start(ct.Context, name, trace.WithAttributes(attrs...), trace.WithSpanKind(trace.SpanKindClient))
+func (ct *clientTracer) start(hook, span string, attrs ...core.KeyValue) {
```
Comment (lizthegrey) [inline plugin/httptrace/clienttrace.go]: `span` feels like it could be confusing given a lot of folks might name the result of `tr.Start` `span` rather than `sp`. Consider using `spanName` or similar if you don't like `name`?

Comment (paivagustavo) [reply plugin/httptrace/clienttrace.go]: Changed to `spanName` to be a little more clear  :)

File: plugin/httptrace/clienttrace.go (hunk 1 above)
Comment (paivagustavo) [reply plugin/httptrace/clienttrace.go]: I've added an error and a list of attributes to be added when `end` is called and now only `start` and `end` modifies children spans, this should be enough to handle any race condition on `start`/`end` methods.

**Comment by rghetia** [comment]
> @rghetia I kept your initial changes since I think they are still relevant, hope this is okay.
> 
That is perfectly fine with me.

File: plugin/httptrace/clienttrace_test.go [hunk 3]
```diff
@@ -0,0 +1,149 @@
...
+			} else {
+				t.Fatalf("[span %s] is missing attribute %v", tl.name, local)
+			}
+		}
+
+		if diff := cmp.Diff(actualAttrs, expectedAttrs); diff != "" {
+			t.Fatalf("[span %s] Attributes are different: %v", tl.name, diff)
+		}
+	}
+}
```
Comment (rghetia) [inline plugin/httptrace/clienttrace_test.go]: Does the test capture race condition?

Comment (paivagustavo) [reply plugin/httptrace/clienttrace_test.go]: Nope, but I've added a new one that does.

File: plugin/httptrace/clienttrace.go [hunk 4]
```diff
@@ -41,116 +40,147 @@ var (
...
+		Wait100Continue:      ct.wait100Continue,
+		WroteRequest:         ct.wroteRequest,
+	}
 }
 
-func (ct *clientTracer) open(name string, attrs ...core.KeyValue) {
-	_, sp := ct.tr.Start(ct.Context, name, trace.WithAttributes(attrs...), trace.WithSpanKind(trace.SpanKindClient))
+func (ct *clientTracer) start(hook, spanName string, attrs ...core.KeyValue) {
+	_, sp := ct.tr.Start(ct.Context, spanName, trace.WithAttributes(attrs...), trace.WithSpanKind(trace.SpanKindClient))
+	// TODO(paivagustavo): remove this for loop when `trace.WithAttributes(attrs...)` works.
```
Comment (krnowak) [inline plugin/httptrace/clienttrace.go]: Doesn't it already work in master? Also, if it doesn't, you could use `sp.SetAttributes()`.

Comment (lizthegrey) [reply plugin/httptrace/clienttrace.go]: Yup I removed the TODO and fixed the bug :)
