### PR TITLE
otel: conceal unwrapping for global async instrument registration

### LINKED ISSUE #5827: Regression: Delegation broken for global meterproviders
From https://github.com/open-telemetry/opentelemetry-go/issues/5753#issuecomment-2354164595 reported by @Jesse-Bonfire

> It appears that this change has broken metrics that are registered before otel.SetMeterProvider is called. We are getting into a spot where the delegate on the siUpDownCounter isn't getting set as it looks like with the new map we are creating new ones and throwing away the old. But the old counter has been registered with meter.RegisterCallback
https://github.com/open-telemetry/opentelemetry-go/blob/42fd8fe325c125a40a21796c3f14b599e5e5f586/internal/global/meter.go#L175C8-L175C9

> I am pretty new to Otel and Go but this change seems to break the connection pools convention outlined here.
https://github.com/open-telemetry/semantic-conventions/blob/422eeb71f40c73d1b195723cc1cffeb09abf2391/docs/database/database-metrics.md#connection-pools

> Currently I am seeing this when instrumenting a Redis Cluster as it creates instrumentation for the connection pool to each node in the cluster. https://github.com/redis/go-redis/blob/233f97accde15bcb2e3d86ee744109b4dce34171/extra/redisotel/metrics.go#L85

> This problem is removed if we apply the instrumentation after we call otel.SetMeterProvider because the delegate just creates the counter. Not sure the best way to proceed.

> I am able to reproduce the exception with the following test case

```golang
package bench

import (
	"context"
	"testing"

	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/metric"
	sdkmetric "go.opentelemetry.io/otel/sdk/metric"
)

const (
	meterName  = "foo"
	metricName = "bar"
)

func BenchmarkSimple(b *testing.B) {
	b.ReportAllocs()
	meter := otel.Meter(meterName)
	for i := 0; i < 5; i++ {
		m, _ := meter.Int64ObservableUpDownCounter(metricName)
		meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
			o.ObserveInt64(m, int64(10))
			return nil
		}, m)
	}
	p1 := sdkmetric.NewMeterProvider()
	otel.SetMeterProvider(p1)
}
```

### PR DESCRIPTION
**Pull request by jmacd**
~Two defects are fixed here. However, note that async instrument delegation appears to have been broken a long time.~

Internalizes and tests the behavior of the Global MeterProvider. This moves the call to `Unwrap()` out of the SDK, fully concealing it within the internal/global package (using an un-exported method).

This adds a test for the new functionality. While this test is not comprehensive, because it doesn't test every instrument variation, it explicitly tests that both the NewCallback function and the Observe functions receive objects constructed by the alternate SDK.

Fixes #5827

### CODE REVIEW

**Comment by dashpole** [comment]
Is this broken for our SDK as well?  https://github.com/open-telemetry/opentelemetry-go/blob/a7d5c1aef7a99e79eab0287327d3731ee2c2e3b5/sdk/metric/meter.go#L448

**Comment by jmacd** [comment]
I'm mildly confused by this. My expectation was that the internal/global package would hide details about the delgation and that SDKs would not need to unwrap themselves.

**Comment by jmacd** [comment]
@dashpole PTAL

You pointed me to more tests w/ more nuance. The `TestGlobalInstRegisterCallback` test in sdk/metric exercises a case with mixed use of pre-registration and post-registration instruments.  I've corrected this PR to pass all tests.

The `unwrap()` method is non-exported again. SDKs should not need to call such a method.

File: sdk/metric/meter.go [hunk 1]
```diff
@@ -444,13 +444,6 @@ func (m *meter) RegisterCallback(f metric.Callback, insts ...metric.Observable)
 	reg := newObserver()
 	var errs multierror
 	for _, inst := range insts {
-		// Unwrap any global.
```
Comment (dashpole) [inline sdk/metric/meter.go:447]: Do we need to worry about version skew between our API and SDK (old API with new SDK)?  I don't see anything about that in https://github.com/open-telemetry/opentelemetry-go/blob/main/VERSIONING.md.

**Review by dashpole — COMMENTED** [review]
I tried to figure out why the unwrapping was done in the SDK in https://github.com/open-telemetry/opentelemetry-go/pull/3584, but can't figure it out.  This LGTM, but I would really like @MrAlias to review if he remembers why this was done

File: sdk/metric/meter.go (hunk 1 above)
Comment (jmacd) [reply sdk/metric/meter.go:447]: Good question!

First, I doubt that there are any other alternate metrics SDKs out there--I think we would know. It's probably safe to assume https://github.com/lightstep/otel-launcher-go/tree/main/lightstep/sdk/metric is the only one.

If there were others, they would have noticed that asynchronous instruments were not working through globals--I think this has been the case for a long time, maybe when NewCallback() was introduced?

The otel-launcher-go SDK is used extensively inside our company, but there are not many asynchronous instruments and the ones that are aren't registered through globals. This leads me to suspect that basically no one is using an alternate SDK with globals.

I had to look up the history. I wrote the initial version of the global meter implementation, and I had to visit those old PRs to remember how this unwrap() or Unwrap() stuff started. I realize now, that I was imagining that the global meter concealed this detail. In the original code, there was an `Implementation()` method that returned `any` and the SDKs were expected to call it. 

See https://github.com/open-telemetry/opentelemetry-go/blob/d7b3c3d7e7a7c56e9bfa6aa40d03d75e78e3dd3f/api/metric/sdkhelpers.go#L51

(By the way, no one should go reading that old, old code base!! We're in a much nicer place, today!)

At some point along the way, `Implementation() any` which was part of the SDK instrument interface became `Unwrap() metric.Observer` hidden in an internal package, but the SDK was aware of the detail and downcasts to the same type. I see how this could go either way: we could document the `Unwrap()` interface for alternate SDKs to use with callbacks, or we could fix the global package to eliminate this detail.

Still, your question: I can't see any potential for version-skew problems because`internal/global`, `/metric` and `sdk/metric` are in the same Go module.

**Comment by jmacd** [comment]
@dashpole As we discussed, I'll leave this open.
I think it is safe to release this repo as-is. The fact that `unwrap()` is called, doing nothing, appears harmless for OTel-Go SDK users. For the alternate SDK user, I can work around this by calling `Unwrap()`. I would be glad to see this PR applied after the release, but I'll accept if you decide to keep calling Unwrap() the SDK's responsibility. If so, I'd propose to add a public Unwrap interface and documentation. I'll leave it up to you and @MrAlias. Thanks!

File: sdk/metric/meter.go (hunk 1 above)
Comment (dashpole) [reply sdk/metric/meter.go:447]: After sleeping on it, I realize that since our SDK depends on the API of the same version, you can't have that kind of version skew.  Thank you for the history lesson!

**Review by dashpole — APPROVED** [review]
I would like to wait to merge this until after the release.

**Review by dmathieu — APPROVED** [review]

**Comment by jmacd** [comment]
I worked around the problem as stated above, so I consider this a nice-to-have low priority fix. The workaround, in case anyone else cares, is

```
	if unwrapped, ok := inst.(interface {
		Unwrap() metric.Observable
	}); ok {
		inst = unwrapped.Unwrap()
	}
```

I needed to do this in two places related to asynchronous instrument handling. The global package hides this detail as far as synchronous instruments are concerned.

**Review by pellared — APPROVED** [review]

File: internal/global/meter.go [hunk 2]
```diff
@@ -515,9 +511,33 @@ type registration struct {
...
-func (c *registration) setDelegate(m metric.Meter) {
-	insts := unwrapInstruments(c.instruments)
+type unwrapObs struct {
+	embedded.Observer
+	obs metric.Observer
+}
+
+func (uo *unwrapObs) ObserveFloat64(inst metric.Float64Observable, value float64, opts ...metric.ObserveOption) {
+	if un, ok := inst.(unwrapper); ok {
+		inst = un.unwrap().(metric.Float64Observable)
```
[the remark this answers is not in the document]
Comment (jmacd) [reply internal/global/meter.go]: I'm glad to improve this. I believe the condition we're talking about is impossible without a logic bug internal to this package, since the thing that was wrapped originally by an instrument of the matching type. I'm worried about constructing error conditions that are impossible to test.

I figure that we probably don't need to create a new error condition. If the instrument fails to unwrap as expected, the receiving SDK's asynchronous code path is obligated to handle an error, as there's not much it can do with a reference to the internal/global-private wrapper object.

How does this look, to you?

```
// unwrapFloat64Observable returns an expected metric.Float64Observable after
// unwrapping the global object.
func unwrapFloat64Observable(inst metric.Float64Observable) metric.Float64Observable {
	if unwrapped, ok := inst.(unwrapper); ok {
		if floatObs, ok := unwrapped.unwrap().(metric.Float64Observable); ok {
			// Note: if the unwrapped object does not
			// unwrap as an observable for either of the
			// predicates here, it means an internal bug in
			// this package.  We avoid logging an error in
			// this case, because the SDK has to try its
			// own type conversion on the object.  The SDK
			// will see this and be forced to respond with
			// its own error.
			//
			// This code uses a double-nested if statement
			// to avoid creating a branch that is
			// impossible to cover.
			inst = floatObs
		}
	}
	return inst
}
```

(and same for int64). When I say the SDK is forced to check the same error in the comment above, I'm referring to [this](https://github.com/open-telemetry/opentelemetry-go/blob/81b2a33e1bbc57ef8f401e5ee7aaa9bc6b7ac772/sdk/metric/meter.go#L531).

[the remark this answers is not in the document]
Comment (MrAlias) [reply internal/global/meter.go]: Makes sense, LGTM :+1:

**Review by MrAlias — APPROVED** [review]
