### PR TITLE
Fix and test uses of global.Meter with RecordBatch()

### LINKED ISSUE #677: RecordBatch panics if creates measurement before InstallNewPipeline
The code below will panic with `interface conversion: metric.SyncImpl is *internal.syncImpl, not *metric.syncInstrument`.

```go
package main

import (
	"context"
	"log"

	"go.opentelemetry.io/otel/api/global"
	"go.opentelemetry.io/otel/api/metric"
	"go.opentelemetry.io/otel/exporters/metric/stdout"
)

func main() {
	log.SetFlags(0)
	meter := global.MeterProvider().Meter("example/ping")
	counter := metric.Must(meter).NewInt64Counter("example.counter")

	pusher, err := stdout.InstallNewPipeline(stdout.Config{})
	if err != nil {
		log.Fatal(err)
	}
	defer pusher.Stop()

	n := counter.Measurement(1)
	meter.RecordBatch(context.Background(), nil, n)
}
```

Should I keep to install the exporter before creating any instruments?

### environment

- Go: 1.14
- GOOS: darwin
- GOARCH: amd64
- otel: v0.4.3

### PR DESCRIPTION
**Pull request by jmacd**
Resolves #677.

### CODE REVIEW

File: api/global/internal/meter_test.go [hunk 1]
```diff
@@ -360,3 +362,56 @@ func TestImplementationIndirection(t *testing.T) {
...
+	meter.RecordBatch(context.Background(), nil, counter.Measurement(1))
+
+	var buf bytes.Buffer
+
+	pusher, err := stdout.InstallNewPipeline(stdout.Config{
+		Writer:         &buf,
+		DoNotPrintTime: true,
+	})
+	if err != nil {
+		log.Fatal(err)
```
Comment (MrAlias) [inline api/global/internal/meter_test.go:408]:
```suggestion
		t.Fatal(err)
```

**Comment by jmacd** [comment]
Looks like CircleCI is busted.
