### PR TITLE
Change NewSplitDriver paramater and initialization

### LINKED ISSUE #1583: OTLP exporter only for traces
Is it possible to configure OTLP exporter only for traces (and omit metrics)? E.g.

```go
driver := otlpgrpc.NewDriver(...)

exporter, err := otlp.NewExporter(ctx,
	otlp.NewSplitDriver(otlp.SplitConfig{
		// ForMetrics: driver,
		ForTraces: driver,
	}),
)
```

produces

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x6d0495]

goroutine 13 [running]:
go.opentelemetry.io/otel/exporters/otlp.(*splitDriver).Start.func1(0xc000257390, 0xc0000d1c80, 0xb061b0, 0xc0000b2000, 0xc000227df0)
	/home/vmihailenco/workspace/opentelemetry-go/exporters/otlp/protocoldriver.go:92 +0x55
created by go.opentelemetry.io/otel/exporters/otlp.(*splitDriver).Start
	/home/vmihailenco/workspace/opentelemetry-go/exporters/otlp/protocoldriver.go:90 +0xcb
exit status 2
```

Uncommenting `ForMetrics` fixes the panic, but I guess it will also export metrics which is undesirable for backends that don't support metrics...

### PR DESCRIPTION
**Pull request by bryan-aguilar**
This PR updates the way that NewSplitDriver is initialized and the arguments that it takes. As discussed in the SIG meeting on 2021-04-01 the program should not panic if a user fails to initialize all drivers in the config. NewSplitDriver now accepts a set of options which moves it to be in line with the rest of the code base. A noopDriver is internally created for uninitialized fields.

Resolves #1583

### CODE REVIEW

**Comment by bryan-aguilar** [comment]
@MrAlias  @Aneurysm9

File: exporters/otlp/options.go [hunk 1]
```diff
@@ -43,3 +43,22 @@ func WithMetricExportKindSelector(selector metricsdk.ExportKindSelector) Exporte
 		cfg.exportKindSelector = selector
 	}
 }
+
+// ProtocolDriverOption provides options for setting up a split driver
+type ProtocolDriverOption func(d *splitDriver)
```
Comment (Aneurysm9) [inline exporters/otlp/options.go:48]:
```suggestion
type SplitDriverOption func(d *splitDriver)
```

I'm wondering if this name makes more sense as these options are only applicable to the `splitDriver`.

File: exporters/otlp/otlp_test.go [hunk 2]
```diff
@@ -283,46 +283,109 @@ func TestNewExportPipeline(t *testing.T) {
...
+		assert.NoError(t, driver.Start(ctx))
+
+		assert.Equal(t, 1, driverMetrics.started)
+		assert.Equal(t, 0, driverMetrics.stopped)
+		assert.Equal(t, 0, driverMetrics.tracesExported)
+		assert.Equal(t, 0, driverMetrics.metricsExported)
+
+		recordCount := 5
+		assert.NoError(t, driver.ExportMetrics(ctx, stubCheckpointSet{recordCount}, metricsdk.StatelessExportKindSelector()))
+		assert.NoError(t, driver.ExportTraces(ctx, nil))
```
Comment (MadVikingGod) [inline exporters/otlp/otlp_test.go:340]: I know this makes no actual difference in the code, but could we change these nils to actual snapshots like the test above?
This is just to make sure future iterations of this can't shortcut nil or 0 len inputs and still pass but fail with real data.

File: exporters/otlp/protocoldriver.go [hunk 3]
```diff
@@ -143,3 +154,23 @@ func (d *splitDriver) ExportMetrics(ctx context.Context, cps metricsdk.Checkpoin
...
+func (d *noopDriver) Stop(ctx context.Context) error {
+	return nil
+}
+
+// ExportMetrics does nothing
+func (d *noopDriver) ExportMetrics(ctx context.Context, cps metricsdk.CheckpointSet, selector metricsdk.ExportKindSelector) error {
+	return nil
+}
+
+// Export traces does nothing
```
Comment (MrAlias) [inline exporters/otlp/protocoldriver.go:173]:
```suggestion
// ExportTraces does nothing.
```

File: exporters/otlp/protocoldriver.go [hunk 4]
```diff
@@ -143,3 +154,23 @@ func (d *splitDriver) ExportMetrics(ctx context.Context, cps metricsdk.Checkpoin
 func (d *splitDriver) ExportTraces(ctx context.Context, ss []*tracesdk.SpanSnapshot) error {
 	return d.trace.ExportTraces(ctx, ss)
 }
+
+// Start does nothing
```
Comment (MrAlias) [inline exporters/otlp/protocoldriver.go:158]:
```suggestion
// Start does nothing.
```

File: exporters/otlp/protocoldriver.go [hunk 5]
```diff
@@ -143,3 +154,23 @@ func (d *splitDriver) ExportMetrics(ctx context.Context, cps metricsdk.Checkpoin
...
+func (d *noopDriver) Start(ctx context.Context) error {
+	return nil
+}
+
+// Stop does nothing
```
Comment (MrAlias) [inline exporters/otlp/protocoldriver.go:163]:
```suggestion
// Stop does nothing.
```

File: exporters/otlp/protocoldriver.go [hunk 6]
```diff
@@ -143,3 +154,23 @@ func (d *splitDriver) ExportMetrics(ctx context.Context, cps metricsdk.Checkpoin
...
+func (d *noopDriver) Stop(ctx context.Context) error {
+	return nil
+}
+
+// ExportMetrics does nothing
```
Comment (MrAlias) [inline exporters/otlp/protocoldriver.go:168]:
```suggestion
// ExportMetrics does nothing.
```

File: exporters/otlp/options.go [hunk 7]
```diff
@@ -43,3 +43,22 @@ func WithMetricExportKindSelector(selector metricsdk.ExportKindSelector) Exporte
 		cfg.exportKindSelector = selector
 	}
 }
+
+// ProtocolDriverOption provides options for setting up a split driver
```
Comment (MrAlias) [inline exporters/otlp/options.go:47]:
```suggestion
// ProtocolDriverOption provides options for setting up a split driver.
```

File: exporters/otlp/options.go [hunk 8]
```diff
@@ -43,3 +43,22 @@ func WithMetricExportKindSelector(selector metricsdk.ExportKindSelector) Exporte
...
+type ProtocolDriverOption func(d *splitDriver)
+
+// WithMetricDriver allows one to set the driver used for metrics
+// in a SplitDriver
```
Comment (MrAlias) [inline exporters/otlp/options.go:51]:
```suggestion
// in a SplitDriver.
```

File: exporters/otlp/options.go [hunk 9]
```diff
@@ -43,3 +43,22 @@ func WithMetricExportKindSelector(selector metricsdk.ExportKindSelector) Exporte
...
+func WithMetricDriver(dr ProtocolDriver) ProtocolDriverOption {
+	return func(d *splitDriver) {
+		d.metric = dr
+	}
+}
+
+// WithTraceDriver allows one to set the driver used for traces
+// in a SplitDriver
```
Comment (MrAlias) [inline exporters/otlp/options.go:59]:
```suggestion
// in a SplitDriver.
```

File: exporters/otlp/otlp_test.go (hunk 2 above)
Comment (MrAlias) [reply exporters/otlp/otlp_test.go:340]: It would make sense to just abstract this part of the repeated code into a separate function that can be called and will ensure this uniform call.

File: exporters/otlp/options.go (hunk 1 above)
Comment (bryan-aguilar) [reply exporters/otlp/options.go:48]: Agreed and updated.

File: exporters/otlp/otlp_test.go (hunk 2 above)
Comment (bryan-aguilar) [reply exporters/otlp/otlp_test.go]: That makes a lot of sense. I will work on refining the test cases, was trying to get the core change out for review. Do you want me to change this to a draft PR @MrAlias ?

File: exporters/otlp/options.go [hunk 10]
```diff
@@ -43,3 +43,22 @@ func WithMetricExportKindSelector(selector metricsdk.ExportKindSelector) Exporte
 		cfg.exportKindSelector = selector
 	}
 }
+
+// ProtocolDriverOption provides options for setting up a split driver.
```
Comment (MrAlias) [inline exporters/otlp/options.go:47]:
```suggestion
// SplitDriverOption provides options for setting up a split driver.
```

File: exporters/otlp/options.go [hunk 11]
```diff
@@ -43,3 +43,22 @@ func WithMetricExportKindSelector(selector metricsdk.ExportKindSelector) Exporte
...
+type SplitDriverOption func(d *splitDriver)
```
Comment (MrAlias) [inline exporters/otlp/options.go:48]: This doesn't match our configuration style guide: https://github.com/open-telemetry/opentelemetry-go/blob/main/CONTRIBUTING.md#option

If we are going to switch to an options approach we should follow the other patterns in the repo.

File: exporters/otlp/otlp_test.go (hunk 2 above)
Comment (MrAlias) [reply exporters/otlp/otlp_test.go]: @bryan-aguilar if you think the changes needed will be greater than just the two tests here doing in another PR sounds reasonable, but if not including the changes here seems valid.

**Review by Aneurysm9 — APPROVED** [review]

**Review by MrAlias — APPROVED** [review]
:1st_place_medal:

File: CHANGELOG.md [hunk 12]
```diff
@@ -97,6 +97,8 @@ This project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.htm
 - Make `ExportSpans` in Jaeger Exporter honor context deadline. (#1773)
 - Modify Zipkin Exporter default service name, use default resouce's serviceName instead of empty. (#1777)
 - The `go.opentelemetry.io/otel/sdk/export/trace` package is merged into the `go.opentelemetry.io/otel/sdk/trace` package. (#1778)
+- Make `NewSplitDriver` from `go.opentelemetry.io/otel/exporters/otlp` take variadic arguments instead of a `SplitConfig` item. 
+  `NewSplitDriver` now automically implements an internal `noopDriver` for `SplitConfig` fields that are not initialized. (#1798)
```
Comment (Aneurysm9) [inline CHANGELOG.md:101]: Since this missed the `v0.20.0` release the `CHANGELOG.md` entry here needs to be moved up into the `Unreleased`/`Changed` section above.
