### PR TITLE
sdk/log: Fix TestBatchProcessor/DroppedLogs flaky test

### LINKED ISSUE #5384: Flaky test `TestBatchProcessor/DroppedLogs`
https://github.com/open-telemetry/opentelemetry-go/actions/runs/9153962106/job/25163732175

```
go test -timeout 60s -short ./sdk/log/...
--- FAIL: TestBatchProcessor (0.06s)
    --- FAIL: TestBatchProcessor/DroppedLogs (0.01s)
make: *** [test/./sdk/log] Error 1
        batch_test.go:449: 
            	Error Trace:	/Users/runner/work/opentelemetry-go/opentelemetry-go/sdk/log/batch_test.go:449
            	Error:      	"" does not contain "\"level\"=1 \"msg\"=\"dropped log records\" \"dropped\"=1"
            	Test:       	TestBatchProcessor/DroppedLogs
```

### PR DESCRIPTION
**Pull request by amanakin**
Fix #5384

Run of `go test  -count=1000000 -run="TestBatchProcessor/DroppedLogs"`
**Before**:
Failed with either `Condition never satisfied` or panic
**After**:
Passed

First, bytes.Buffer is not thread-safe, so writing log and reading (`bytes.String()`) caused panic. Added `concurrentBuffer`
Second, fixed flaky test with 4 records:
1. Record goes to `testExporter.Export` function and blocks in this function because of `ExportTrigger` (https://github.com/open-telemetry/opentelemetry-go/blob/19ee6d4775d578357e251828215213782eafed54/sdk/log/exporter_test.go#L87)
2. Record goes to `bufferExporter.input` (https://github.com/open-telemetry/opentelemetry-go/blob/7c5e64cccc16710b2e75f3d60e96acc07dacd7a7/sdk/log/exporter.go#L129)
3. Record goes to `BatchProcessor.q` queue and it could not be enqueued to export, because `bufferExporter.input` is full
4. Record goes to `BatchProcessor.q` and because of overfill, drops third record

### CODE REVIEW

File: sdk/log/batch_test.go [hunk 1]
```diff
@@ -421,7 +438,8 @@ func TestBatchProcessor(t *testing.T) {
 	t.Run("DroppedLogs", func(t *testing.T) {
 		orig := global.GetLogger()
 		t.Cleanup(func() { global.SetLogger(orig) })
-		buf := new(bytes.Buffer)
+		// Use concurrentBuffer for thread-safe reading buffer
```
Comment (MrAlias) [inline sdk/log/batch_test.go:441]: nit:

```suggestion
		// Use concurrentBuffer for concurrent-safe reading.
```

**Review by MrAlias — APPROVED** [review]

**Review by XSAM — APPROVED** [review]
