### PR TITLE
add more test cases to jaeger exporter and fix comments

### LINKED ISSUE #145: Add more test cases to Jaeger Exporter
see this [comment](https://github.com/open-telemetry/opentelemetry-go/pull/143#discussion_r328368123) 

Also fix this [comment](https://github.com/open-telemetry/opentelemetry-go/pull/143#discussion_r328367696)

### PR DESCRIPTION
**Pull request by eran-levy**
still work in progress to add more test cases to jaeger exporter 
fixes #145

### CODE REVIEW

File: exporter/trace/jaeger/jaeger_test.go [hunk 1]
```diff
@@ -15,24 +15,90 @@
...
+			ServiceName: serviceName,
+			Tags: []core.KeyValue{
+				key.String(tagKey, tagVal),
+			},
+		}),
+	)
+
+	assert.NoError(t, err)
+
+	exp.RegisterSimpleSpanProcessor()
```
Comment (rghetia) [inline exporter/trace/jaeger/jaeger_test.go]: Not required. In fact, RegisterSimpleSpanProcessor should be removed.

File: exporter/trace/jaeger/jaeger_test.go [hunk 2]
```diff
@@ -15,24 +15,90 @@
...
+		sdktrace.WithConfig(sdktrace.Config{DefaultSampler: sdktrace.AlwaysSample()}),
+		sdktrace.WithSyncer(exp))
+
+	assert.NoError(t, err)
+
+	apitrace.SetGlobalProvider(tp)
+	_, span := apitrace.GlobalProvider().GetTracer("test-tracer").Start(context.Background(), "test-span")
+	span.End()
+
+	assert.True(t, span.SpanContext().IsValid())
```
Comment (rghetia) [inline exporter/trace/jaeger/jaeger_test.go]: It would be nice to have a mock Jaeger collector and verify that it receives the span.

File: sdk/trace/trace_test.go [hunk 3]
```diff
@@ -273,14 +270,8 @@ func TestSetSpanAttributesOverLimit(t *testing.T) {
...
-			{
-				Key:   core.Key("key1"),
-				Value: core.Value{Type: core.STRING, String: "value3"},
-			},
-			{
-				Key:   core.Key("key4"),
-				Value: core.Value{Type: core.STRING, String: "value4"},
-			},
+			key.String("key1", "value3"),
+			key.String("key4", "value4"),
```
Comment (rghetia) [inline sdk/trace/trace_test.go]: can you please add non-string attributes here ([comment](https://github.com/open-telemetry/opentelemetry-go/pull/143/files/1d02a09f0171d9e3e2f066bf658e91c89c028dd0#r328368123) in #143)?

File: exporter/trace/jaeger/jaeger_test.go (hunk 1 above)
Comment (eran-levy) [reply exporter/trace/jaeger/jaeger_test.go]: correct, done, will create another PR to deprecate jaeger export RegisterSimpleSpanProcessor() that already being taken care of by the sdk

File: sdk/trace/trace_test.go (hunk 3 above)
Comment (eran-levy) [reply sdk/trace/trace_test.go]: done

File: exporter/trace/jaeger/jaeger_test.go (hunk 2 above)
Comment (eran-levy) [reply exporter/trace/jaeger/jaeger_test.go]: @rghetia fixed, if it makes sense, i will also add similar tests to the agent as well

Comment (rghetia) [reply exporter/trace/jaeger/jaeger_test.go]: looks good.

Comment (eran-levy) [reply exporter/trace/jaeger/jaeger_test.go]: done and added tests for the agent as well

**Comment by eran-levy** [comment]
@rghetia thanks for the review, resolved all, renaming the PR from WIP

File: exporter/trace/jaeger/jaeger_test.go [hunk 4]
```diff
@@ -15,24 +15,132 @@
...
+
+	exp.Flush()
+	tc := exp.uploader.(*testCollectorEnpoint)
+	assert.True(t, len(tc.spansUploaded) > 0)
```
Comment (rghetia) [inline exporter/trace/jaeger/jaeger_test.go]: please check for specific count of spans.

Comment (eran-levy) [reply exporter/trace/jaeger/jaeger_test.go]: done

**Comment by eran-levy** [comment]
Yup fixed np

File: exporter/trace/jaeger/jaeger_test.go [hunk 5]
```diff
@@ -15,24 +15,133 @@
...
+			},
+		}),
+	)
+
+	assert.NoError(t, err)
+	assert.EqualValues(t, serviceName, exp.process.ServiceName)
+	assert.Len(t, exp.process.Tags, 1)
+}
+
+func TestNewExporterShouldFailIfCollectorEndpoingEmpty(t *testing.T) {
```
Comment (krnowak) [inline exporter/trace/jaeger/jaeger_test.go]: typo in Endpoing

Comment (eran-levy) [reply exporter/trace/jaeger/jaeger_test.go]: @krnowak fixed

**Comment by lizthegrey** [comment]
FYI: this undid go.mod changes, causing the Jaeger module to become non-importable outside the otel repo itself.

**Comment by eran-levy** [comment]
@lizthegrey thanks
