### PR TITLE
Fix up docs and other othttp cleanups

### LINKED ISSUE #211: Better documentation for othttp
I was reading my own docs today and they're sorely lacking. They leave out a lot of details about how, why and when to use different parts of othttp.

### PR DESCRIPTION
**Pull request by freeformz**
Closes #211 

This includes a few cleanups that are more obvious to me now as well.

### CODE REVIEW

File: plugin/othttp/handler.go [hunk 1]
```diff
@@ -0,0 +1,228 @@
...
+
+	h.handler.ServeHTTP(rww, r.WithContext(ctx))
+
+	setAfterServeAttributes(span, bw.read, rww.written, int64(rww.statusCode), bw.err, rww.err)
+}
+
+func setAfterServeAttributes(span trace.Span, read, wrote, statusCode int64, rerr, werr error) {
+	kv := make([]core.KeyValue, 0, 5)
+	// TODO: Consider adding an event after each read and write, possibly as an
+	// option (defaulting to off), so at to not create needlesly verbose spans.
```
Comment (rghetia) [inline plugin/othttp/handler.go]: nit: s/at to/as to/
s/needlesly/needlessly/

File: plugin/othttp/doc.go [hunk 2]
```diff
@@ -0,0 +1,18 @@
+// Package othttp provides a http.Handler and functions that are
```
Comment (dmathieu) [inline plugin/othttp/doc.go]: Shouldn't the licence be put first?

**Comment by freeformz** [comment]
@jmacd Yep. Done.
