### PR TITLE
bridge/opentracing: fix baggage item key is canonicalized

### LINKED ISSUE #2793: Baggage is not propagated by OpenTracing bridge
### Description

When using BridgeTracer, after Inject the Carrier has no entries for baggage.
After Extract the resulting SpanContext has nil in the baggage field.

### Environment

- OS: Linux
- Architecture: ARM64 (M1)
- Go Version: `go1.17.1 darwin/arm64`
- opentelemetry-go version: 1884de2b4b68aaf, shortly after v1.6.3

### Steps To Reproduce

Starting with the test from #2141, add some baggage:
https://github.com/bboreham/opentelemetry-go/commit/c162bddc5ca80999b5f4ead43fff6b57adac17c8

Observe the test now fails:
```
go test -run ^TestHeaderCarrier$ go.opentelemetry.io/otel/bridge/opentracing
--- FAIL: TestHeaderCarrier (0.00s)
    /Users/bryan/src/github.com/open-telemetry/opentelemetry-go/bridge/opentracing/bridge_test.go:93: Extracted span context does not match: 
&opentracing.bridgeSpanContext{bag:baggage.Baggage{list:baggage.List{"Foo":baggage.Item{Value:"bar", Properties:[]baggage.Property(nil)}}}, otelSpanContext:trace.SpanContext{traceID:trace.TraceID{0x5e, 0xb4, 0x86, 0x1, 0x52, 0xcc, 0x3b, 0x6a, 0xab, 0xdd, 0x71, 0x2f, 0xe7, 0x5a, 0x7d, 0x54}, spanID:trace.SpanID{0x41, 0x3f, 0xec, 0x7c, 0x4b, 0xec, 0xea, 0x13}, traceFlags:0x0, traceState:trace.TraceState{list:[]trace.member(nil)}, remote:false}}, 
&opentracing.bridgeSpanContext{bag:baggage.Baggage{list:baggage.List(nil)}, otelSpanContext:trace.SpanContext{traceID:trace.TraceID{0x5e, 0xb4, 0x86, 0x1, 0x52, 0xcc, 0x3b, 0x6a, 0xab, 0xdd, 0x71, 0x2f, 0xe7, 0x5a, 0x7d, 0x54}, spanID:trace.SpanID{0x41, 0x3f, 0xec, 0x7c, 0x4b, 0xec, 0xea, 0x13}, traceFlags:0x0, traceState:trace.TraceState{list:[]trace.member(nil)}, remote:true}}
```

### Expected behavior

Baggage should be propagated.

### Commentary

There are lines in `BridgeTracer.Inject` and `Extract` aimed at doing something with baggage:
https://github.com/open-telemetry/opentelemetry-go/blob/1884de2b4b68aaf6e7613339b6d0b4397e5aa5c8/bridge/opentracing/bridge.go#L648
https://github.com/open-telemetry/opentelemetry-go/blob/1884de2b4b68aaf6e7613339b6d0b4397e5aa5c8/bridge/opentracing/bridge.go#L667

However the propagator Inject and Extract methods do not seem to line up with this code's expectations.

### LINKED ISSUE #4799: bridge/opentracing: propagated baggage item key is canonicalized
### Description

When a baggage item key is added to a bridge span, they shouldn't be canonicalized by `http.CanonicalHeaderKey`
https://github.com/open-telemetry/opentelemetry-go/blob/1cfd83a1eeaac16edaebbd2938f14b7c70b37c59/bridge/opentracing/bridge.go#L76-L88

> Baggage keys are case sensitive, they are not supposed to be mangled this way -- 
https://github.com/w3c/baggage/blob/ebda53c1d33031d95f1104f44840d3d4b875eb89/baggage/HTTP_HEADER_FORMAT_RATIONALE.md?plain=1#L55
_Originally posted by @yurishkuro in https://github.com/open-telemetry/opentelemetry-go/pull/4776#discussion_r1434431775_

**Additional Info**
Seems like this was added in the initial opentracing bridge implementation in https://www.github.com/open-telemetry/opentelemetry-go/issues/98

`opentelemetry-java` does not canonicalize the keys: https://github.com/open-telemetry/opentelemetry-java/blob/227580ba0956fcd43429d684b7e0798c8723481a/opentracing-shim/src/main/java/io/opentelemetry/opentracingshim/SpanShim.java#L166-L188

`opentelemetry-dotnet` also does not canonicalize the key: https://github.com/open-telemetry/opentelemetry-dotnet/blob/0889e8dc32badbb4c9be8fd24a974fb7e61fa779/src/OpenTelemetry.Shims.OpenTracing/SpanShim.cs#L140-L144

There aren't any references to canonicalizing in spec: https://opentelemetry.io/docs/specs/otel/compatibility/opentracing/#set-baggage-item

### Environment

- OS: macOS
- Architecture: arm
- Go Version: 1.21
- opentelemetry-go version: v1.21.0

### Steps To Reproduce

Test from #4776
https://github.com/scorpionknifes/opentelemetry-go/blob/a112d3f67926fe27a2948a8b15380d5c5ccdcbe1/bridge/opentracing/bridge_test.go#L603-L614

### Expected behavior

The baggage item key should be the same.

### PR DESCRIPTION
**Pull request by scorpionknifes**
Fixes #4799
Related to #2793

Updated to fix propagated baggage item key is canonicalized https://github.com/open-telemetry/opentelemetry-go/issues/4799
A test to prove #2793 is working as expected.

### CODE REVIEW

File: bridge/opentracing/bridge_test.go [hunk 1]
```diff
@@ -574,3 +574,89 @@ func TestBridgeSpanContextPromotedMethods(t *testing.T) {
 		assert.True(t, spanContext.(spanContextProvider).HasTraceID())
 	})
 }
+
+func TestBridgeCarrierBaggagePropagaton(t *testing.T) {
```
Comment (pellared) [inline bridge/opentracing/bridge_test.go:578]:
```suggestion
func TestBridgeCarrierBaggagePropagation(t *testing.T) {
```

**Review by pellared — COMMENTED** [review]
I just made a quick look.

Won't this tests be helpful when working on https://github.com/open-telemetry/opentelemetry-go/issues/3685?

File: bridge/opentracing/bridge_test.go [hunk 2]
```diff
@@ -574,3 +574,89 @@ func TestBridgeSpanContextPromotedMethods(t *testing.T) {
...
+			carrier: ot.HTTPHeadersCarrier(http.Header{}),
+			baggageItems: []bipBaggage{
+				{
+					key:   "foo",
+					value: "bar",
+				},
+			},
+			wantBaggageItems: []bipBaggage{
+				{
+					key:   "Foo",
```
Comment (yurishkuro) [inline bridge/opentracing/bridge_test.go:598]: why is this capitalized? If it is to demonstrate that case doesn't matter, they I would do use a separate test case for that that is explicit about it.

File: bridge/opentracing/bridge_test.go [hunk 3]
```diff
@@ -574,3 +574,89 @@ func TestBridgeSpanContextPromotedMethods(t *testing.T) {
...
+		name             string
+		format           ot.BuiltinFormat
+		carrier          interface{}
+		baggageItems     []bipBaggage
+		wantBaggageItems []bipBaggage
+	}{
+		{
+			name:    "HTTPHeadersCarrier",
+			format:  ot.HTTPHeaders,
+			carrier: ot.HTTPHeadersCarrier(http.Header{}),
```
Comment (yurishkuro) [inline bridge/opentracing/bridge_test.go:589]: unless you envision different test cases for HTTP vs. Text, I would pull the type of carrier into another pre-defined loop, rather than being part of the test case.

**Review by yurishkuro — COMMENTED** [review]
The issue I personally experienced with the bridge was when values contained special characters, not these simplistic foo/bar strings

File: bridge/opentracing/bridge_test.go (hunk 2 above)
Comment (scorpionknifes) [reply bridge/opentracing/bridge_test.go:598]: The capitalization isn't important to the test, it seems `setBaggageItem` would set the `CanonicalHeaderKey` to capitalized
https://github.com/open-telemetry/opentelemetry-go/blob/885210bf33238f8c6cc94c3f3711b0036fbe77b1/bridge/opentracing/bridge.go#L76-L78

Comment (yurishkuro) [reply bridge/opentracing/bridge_test.go:611]: > would set it to capitalized through

which is another bug. Baggage keys are case sensitive, they are not supposed to be mangled this way -- https://github.com/w3c/baggage/blob/ebda53c1d33031d95f1104f44840d3d4b875eb89/baggage/HTTP_HEADER_FORMAT_RATIONALE.md?plain=1#L55

File: CHANGELOG.md [hunk 4]
```diff
@@ -34,6 +34,7 @@ This project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.htm
 
 - Fix `Parse` in `go.opentelemetry.io/otel/baggage` to validate member value before percent-decoding. (#4755)
 - Fix whitespace encoding of `Member.String` in `go.opentelemetry.io/otel/baggage`. (#4756)
+- Fix baggage item key is canonicalized in `go.opentelemetry.io/otel/bridge/opentracing`. (#4799)
```
Comment (pellared) [inline CHANGELOG.md:37]:
```suggestion
- Fix baggage item key so that is not canonicalized in `go.opentelemetry.io/otel/bridge/opentracing`. (#4799)
```

**Comment by yurishkuro** [comment]
Note - I changed the description from `Closes 2793` to `Related to` - this PR does *NOT* close the original issue because the implementation still mangles the baggage values.

**Comment by yurishkuro** [comment]
In order to close that issue the implementation must satisfy this condition: https://github.com/open-telemetry/opentelemetry-specification/pull/3801

**Comment by scorpionknifes** [comment]
> Note - I changed the description from `Closes 2793` to `Related to` - this PR does _NOT_ close the original issue because the implementation still mangles the baggage values.

We might be referencing different tickets; #2793 is an invalid issue and no changes needed: https://github.com/open-telemetry/opentelemetry-go/issues/2793#issuecomment-1866427747
I think https://github.com/open-telemetry/opentelemetry-go/issues/3685 was the one that shouldn't be closed?

**Comment by pellared** [comment]
> Note - I changed the description from `Closes 2793` to `Related to` - this PR does _NOT_ close the original issue because the implementation still mangles the baggage values.

I guess @yurishkuro had https://github.com/open-telemetry/opentelemetry-go/issues/3685 in mind.
I plan to look at this issue tomorrow or even today.

Regarding https://github.com/open-telemetry/opentelemetry-go/issues/2793 I would prefer the author to close the issue or close it after e.g. 1 month in case we got no response.

**Review by pellared — APPROVED** [review]

File: CHANGELOG.md [hunk 5]
```diff
@@ -34,6 +34,7 @@ This project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.htm
 
 - Fix `Parse` in `go.opentelemetry.io/otel/baggage` to validate member value before percent-decoding. (#4755)
 - Fix whitespace encoding of `Member.String` in `go.opentelemetry.io/otel/baggage`. (#4756)
+- Fix baggage item key so that is not canonicalized in `go.opentelemetry.io/otel/bridge/opentracing`. (#4776)
```
Comment (yurishkuro) [inline CHANGELOG.md:37]:
```suggestion
- Fix baggage item key so that it is not canonicalized in `go.opentelemetry.io/otel/bridge/opentracing`. (#4776)
```

File: bridge/opentracing/bridge_test.go [hunk 6]
```diff
@@ -574,3 +574,101 @@ func TestBridgeSpanContextPromotedMethods(t *testing.T) {
...
+	}{
+		{
+			name: "single baggage item",
+			baggageItems: []bipBaggage{
+				{
+					key:   "foo",
+					value: "bar",
+				},
+			},
+			wantBaggageItems: []bipBaggage{
```
Comment (yurishkuro) [inline bridge/opentracing/bridge_test.go:609]: nit: seems redundant. The contract of the Baggage API is if you set a key/value it either causes an error because they are malformed, or they are accepted and returned as-is via get. There's no situation where they should be different, so having this presumption in the tests is misleading too.

**Review by yurishkuro — APPROVED** [review]

File: bridge/opentracing/bridge_test.go (hunk 6 above)
Comment (pellared) [reply bridge/opentracing/bridge_test.go]: https://github.com/open-telemetry/opentelemetry-go/pull/4776/commits/b4c11fea9b9e2e00df2c4e80dfd7c3a3c89021f5

**Review by yurishkuro — APPROVED** [review]

**Comment by MrAlias** [comment]
This seems to have merged without two approvals from the Go Approvers team.

**Comment by pellared** [comment]
@MrAlias Sorry, I have missed that @yurishkuro is not an approver 😬
