### PR TITLE
Validate members once, in `NewMember`

### LINKED ISSUE #2498: Baggage calls validate() on Member too often
### Description

validate() is called on a Member when it is created, and when the Member is added to Baggage.

### Environment

- OS: linux
- Architecture: amd64
- Go Version: 1.17
- opentelemetry-go version: 1.3.0

### Steps To Reproduce

```
b := baggage.FromContext(ctx)
m, _ := baggage.NewMember("foo", "bar") // validate() is called on Member
b.SetMember(m) // validate() is called on Member
```

### Expected behavior

`validate()` is only called at Member creation or when Member is added to a Baggage. Since Tracing is adding overhead to an application, this is to minimize all overhead as much as possible.

### PR DESCRIPTION
**Pull request by dmathieu**
This is an alternative attempt to #2505 at at improving the number of calls to `validate()` in `baggage.Member`, calling it only when the member is added to the baggage.
Right now, we call it twice. Once within `baggage.NewMember`, and another time within `baggage.New`.

Closes #2498

### CODE REVIEW

File: baggage/baggage.go [hunk 1]
```diff
@@ -324,19 +324,17 @@ type Baggage struct { //nolint:golint
...
 func New(members ...Member) (Baggage, error) {
 	if len(members) == 0 {
 		return Baggage{}, nil
 	}
 
 	b := make(baggage.List)
 	for _, m := range members {
-		if err := m.validate(); err != nil {
-			return Baggage{}, err
-		}
```
Comment (MadVikingGod) [inline baggage/baggage.go:339]: As I mentioned in the other approach on this.  We still need to weed out the only possible invalid Member, `Member{}`.  So a check here would be warrented.

**Comment by dmathieu** [comment]
I have added an `isEmpty`, which is used to check whether the provided member and property are empty or not, so they don't need revalidation but also can't be added to their parent struct if they are empty.

File: baggage/baggage_test.go [hunk 2]
```diff
@@ -657,7 +660,10 @@ func TestMemberProperties(t *testing.T) {
 }
 
 func TestMemberValidation(t *testing.T) {
-	m := Member{}
+	m := Member{isEmpty: true}
+	assert.ErrorIs(t, m.validate(), errInvalidMember)
+
+	m.isEmpty = false
 	assert.ErrorIs(t, m.validate(), errInvalidKey)
```
Comment (MadVikingGod) [inline baggage/baggage_test.go:667]: You removed a Valid and important test.  Specifically that `Member{}`, a thing that users can do, should report they are invalid.

File: baggage/baggage_test.go [hunk 3]
```diff
@@ -205,9 +208,9 @@ func TestNewBaggageWithDuplicates(t *testing.T) {
 	assert.Equal(t, want, b)
 }
 
-func TestNewBaggageErrorInvalidMember(t *testing.T) {
-	_, err := New(Member{key: ""})
-	assert.ErrorIs(t, err, errInvalidKey)
+func TestNewBaggageErrorEmptyMember(t *testing.T) {
+	_, err := New(Member{isEmpty: true})
+	assert.ErrorIs(t, err, errInvalidMember)
```
Comment (MadVikingGod) [inline baggage/baggage_test.go:213]: You have removed a valid test.
Creating a Baggage with a `Member{}`.  It doesn't necessarily need to return an error, but it should be an empty baggage.
There is also the test case where a `Member{}` is in the list, it should return baggage with that Member removed.

**Review by MadVikingGod — CHANGES_REQUESTED** [review]

File: baggage/baggage_test.go (hunk 3 above)
Comment (dmathieu) [reply baggage/baggage_test.go]: Good catch. I've renamed `isEmpty` to `hasData` so an empty struct is really marked as invalid, and brought back that test.

File: baggage/baggage_test.go (hunk 2 above)
Comment (dmathieu) [reply baggage/baggage_test.go]: See my other comment.

File: baggage/baggage.go [hunk 4]
```diff
@@ -288,12 +319,16 @@ func parseMember(member string) (Member, error) {
 		panic("failed to parse baggage member")
 	}
 
-	return Member{key: key, value: value, properties: props}, nil
+	return NewMember(key, value, props...)
```
[the remark this answers is not in the document]
Comment (dmathieu) [reply baggage/baggage.go:316]: You're right, I didn't see that this validation already happened earlier in the method. I've removed the duplicate.

File: baggage/baggage.go [hunk 5]
```diff
@@ -448,8 +490,8 @@ func (b Baggage) Members() []Member {
 // If member is invalid according to the W3C Baggage specification, an error
 // is returned with the original Baggage.
 func (b Baggage) SetMember(member Member) (Baggage, error) {
-	if err := member.validate(); err != nil {
-		return b, fmt.Errorf("%w: %s", errInvalidMember, err)
+	if !member.hasData {
+		return b, errInvalidMember
```
[the remark this answers is not in the document]
Comment (dmathieu) [reply baggage/baggage.go]: It previously had, when the parameter was named `isEmpty`. Now that the boolean is inversed, it doesn't. I've switched it back, thank you.

**Comment by MadVikingGod** [comment]
So as it stands, this change has a net negative effect on parsing.  For this to proceed, you will have to do a bit of profiling and improve what is already here.

```
name         old time/op    new time/op    delta
New-4          3.15µs ± 5%    3.12µs ± 3%     ~     (p=0.489 n=9+9)
NewMember-4     363ns ± 5%     360ns ± 3%     ~     (p=0.605 n=9+9)
Parse-4        6.29µs ± 6%    7.40µs ± 4%  +17.61%  (p=0.000 n=10+9)

name         old alloc/op   new alloc/op   delta
New-4            832B ± 0%      832B ± 0%     ~     (all equal)
NewMember-4     0.00B          0.00B          ~     (all equal)
Parse-4        1.35kB ± 0%    1.43kB ± 0%   +5.94%  (p=0.000 n=10+10)

name         old allocs/op  new allocs/op  delta
New-4            16.0 ± 0%      16.0 ± 0%     ~     (all equal)
NewMember-4      0.00           0.00          ~     (all equal)
Parse-4          19.0 ± 0%      20.0 ± 0%   +5.26%  (p=0.000 n=10+10)
```

File: baggage/baggage.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (dmathieu) [reply baggage/baggage.go:494]: Scratch that. We do still need it. If we call `validate()`, we will re-run the regexp if `hasData` is true. So we do keep running the validations twice (see my latest benchstats vs yours, which shows the improvement).

**Comment by dmathieu** [comment]
So, I've done two changes:

* `New` actually needs to very `hasData` and not call `validate()`. If we call validate, with `hasData` being true, we rerun the validation (hence no performance improvement in your benchstat).
* We need to check the regex themselves and not use `NewMember` in `parseMember`. Doing the latter reruns the validation, both on the member and on the properties, hence the performance loss.

Here is my benchstat with the latest changes:


```
name          old time/op    new time/op    delta
New-12          2.45µs ± 1%    1.22µs ± 2%  -50.29%  (p=0.000 n=10+10)
NewMember-12     288ns ± 1%     290ns ± 2%     ~     (p=0.315 n=9+10)
Parse-12        4.92µs ± 1%    4.94µs ± 1%     ~     (p=0.589 n=10+9)

name          old alloc/op   new alloc/op   delta
New-12            832B ± 0%      832B ± 0%     ~     (all equal)
NewMember-12     0.00B          0.00B          ~     (all equal)
Parse-12        1.36kB ± 0%    1.36kB ± 0%     ~     (p=0.875 n=10+10)

name          old allocs/op  new allocs/op  delta
New-12            16.0 ± 0%      16.0 ± 0%     ~     (all equal)
NewMember-12      0.00           0.00          ~     (all equal)
Parse-12          19.0 ± 0%      19.0 ± 0%     ~     (all equal)
```

**Review by MadVikingGod — APPROVED** [review]
I don't see any further problems with this approach.

**Review by Aneurysm9 — APPROVED** [review]

File: CHANGELOG.md [hunk 6]
```diff
@@ -13,6 +13,7 @@ This project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.htm
 - Support `OTEL_EXPORTER_ZIPKIN_ENDPOINT` env to specify zipkin collector endpoint (#2490)
 - Log the configuration of TracerProviders, and Tracers for debugging. To enable use a logger with Verbosity (V level) >=1
 - Added environment variables for: `OTEL_BSP_SCHEDULE_DELAY`, `OTEL_BSP_EXPORT_TIMEOUT`, `OTEL_BSP_MAX_QUEUE_SIZE` and `OTEL_BSP_MAX_EXPORT_BATCH_SIZE` (#2515)
+- Baggage members are now only validated once, when calling `NewMember` and not also when adding it to the baggage itself. (#2522)
```
Comment (MrAlias) [inline CHANGELOG.md:16]: Please move this to the `### Fixed` section.

File: baggage/baggage.go [hunk 7]
```diff
@@ -61,58 +61,75 @@ type Property struct {
...
-	p.key = key
-	p.value = value
-	p.hasValue = true
 	return p, nil
 }
 
+func newInvalidProperty() Property {
+	return Property{}
+}
+
```
Comment (MrAlias) [inline baggage/baggage.go:100]: This seems unneeded. Is there a reason to use this instead of the existing declarations of the empty `Property` type?

File: baggage/baggage.go [hunk 8]
```diff
@@ -220,26 +237,40 @@ func (p properties) String() string {
...
+		return newInvalidMember(), err
 	}
 
 	return m, nil
 }
 
+func newInvalidMember() Member {
+	return Member{}
+}
+
```
Comment (MrAlias) [inline baggage/baggage.go:267]: Same question here regarding if this is needed?

File: baggage/baggage.go [hunk 9]
```diff
@@ -61,58 +61,75 @@ type Property struct {
...
 	}
+
 	return p, nil
 }
 
 // validate ensures p conforms to the W3C Baggage specification, returning an
 // error otherwise.
 func (p Property) validate() error {
+	if !p.hasData {
+		return errInvalidProperty
```
Comment (MrAlias) [inline baggage/baggage.go:130]: Specifically this is identifying an invalid key. Can we update this returned error to match what is done below to make sure our returned errors are as actionable as possible? i.e.

```go
return errFunc(fmt.Errorf("%w: %q", errInvalidKey, p.key))
```

File: baggage/baggage.go [hunk 10]
```diff
@@ -288,12 +319,16 @@ func parseMember(member string) (Member, error) {
...
 
-	return Member{key: key, value: value, properties: props}, nil
+	return Member{key: key, value: value, properties: props, hasData: true}, nil
 }
 
 // validate ensures m conforms to the W3C Baggage specification, returning an
 // error otherwise.
 func (m Member) validate() error {
+	if !m.hasData {
+		return errInvalidMember
```
Comment (MrAlias) [inline baggage/baggage.go:329]: Similar here, can we update this returned error to contain info what makes it invalid?

File: baggage/baggage.go (hunk 7 above)
Comment (dmathieu) [reply baggage/baggage.go:100]: It seems more readable to me. Whenever we call that method, we know we are returning an invalid property object.

File: baggage/baggage.go (hunk 8 above)
Comment (dmathieu) [reply baggage/baggage.go:267]: Same as for the property. It's not needed per-se, it just seems more readable to me.

File: baggage/baggage.go (hunk 9 above)
Comment (dmathieu) [reply baggage/baggage.go]: Sure, I've done so. I've kept it an `errInvalidProperty` though, as technically, the reason for having an invalid property could have been something different than the key (the actual reason would have been provided when the invalid property was initially provided though).

File: baggage/baggage.go (hunk 10 above)
Comment (dmathieu) [reply baggage/baggage.go]: See my other comment as well :)

**Review by MrAlias — APPROVED** [review]
