### PR TITLE
Fix incorrect aggregation; Prometheus exporter behavior

### LINKED ISSUE #887: Prometheus Exporter Example
### Description (What happened)
While running the metrics example for the prometheus exporter from [here](https://github.com/open-telemetry/opentelemetry-go/tree/master/example/prometheus), I noticed the following:

After all meter.Records in `main.go` have happened (~10s)
Calling the metrics endpoint `http://localhost:2222/metrics` yields the following expected prometheus metrics:
```
# HELP ex_com_one A ValueObserver set to 1.0
# TYPE ex_com_one histogram
ex_com_one_bucket{ex_com_lemons="13",le="+Inf"} 1
ex_com_one_sum{ex_com_lemons="13"} 1
ex_com_one_count{ex_com_lemons="13"} 1
# HELP ex_com_three 
# TYPE ex_com_three counter
ex_com_three{ex_com_lemons="13"} 22
ex_com_three{A="1",B="2",C="3",ex_com_lemons="10"} 12
# HELP ex_com_two 
# TYPE ex_com_two histogram
ex_com_two_bucket{ex_com_lemons="13",le="+Inf"} 1
ex_com_two_sum{ex_com_lemons="13"} 2
ex_com_two_count{ex_com_lemons="13"} 1
ex_com_two_bucket{A="1",B="2",C="3",ex_com_lemons="10",le="+Inf"} 1
ex_com_two_sum{A="1",B="2",C="3",ex_com_lemons="10"} 2
ex_com_two_count{A="1",B="2",C="3",ex_com_lemons="10"} 1
```

After some additional time interval (~15s) all values of the metrics instruments seem to be increasing. 
Especially the counter `ex_com_three{ex_com_lemons="13"} 44` has been rising from `22` to `44`
```
# HELP ex_com_one A ValueObserver set to 1.0
# TYPE ex_com_one histogram
ex_com_one_bucket{ex_com_lemons="13",le="+Inf"} 2
ex_com_one_sum{ex_com_lemons="13"} 2
ex_com_one_count{ex_com_lemons="13"} 2
ex_com_one_bucket{A="1",B="2",C="3",ex_com_lemons="10",le="+Inf"} 1
ex_com_one_sum{A="1",B="2",C="3",ex_com_lemons="10"} 13
ex_com_one_count{A="1",B="2",C="3",ex_com_lemons="10"} 1
# HELP ex_com_three 
# TYPE ex_com_three counter
ex_com_three{ex_com_lemons="13"} 44
ex_com_three{A="1",B="2",C="3",ex_com_lemons="10"} 25
# HELP ex_com_two 
# TYPE ex_com_two histogram
ex_com_two_bucket{ex_com_lemons="13",le="+Inf"} 2
ex_com_two_sum{ex_com_lemons="13"} 4
ex_com_two_count{ex_com_lemons="13"} 2
ex_com_two_bucket{A="1",B="2",C="3",ex_com_lemons="10",le="+Inf"} 2
ex_com_two_sum{A="1",B="2",C="3",ex_com_lemons="10"} 14
ex_com_two_count{A="1",B="2",C="3",ex_com_lemons="10"} 2
```

All the metrics of the example keep increasing indefinitely, even though no new measurements for the metric instruments in the example application are recorded.

### Expectations
I would have expected that the counter would not increase any further since no new measurement for this counter is recorded in the example application. 

Is this an expected behavior? If so, what is the reason for the additional increase and can it be configured?

In the future I would like to employ counters and other metric instruments in a go grpc-interceptor in some applications, but the described behavior would seem to work against that. Is there maybe another approach to achive that?

### Configuration
go version: 
- go1.13.8

Dependencies:
- go.opentelemetry.io/otel v0.7.0
- go.opentelemetry.io/otel/exporters/metric/prometheus v0.7.0

### PR DESCRIPTION
**Pull request by jmacd**
There was a bug in `FinishCollection()` that would double-apply stale updates for instruments that had not been modified in the most recent collection interval. This corrects the incorrect aggregation.

This adds further correctness and testing for Prometheus. The basic processor supports a new `Memory` option that says whether to remember and report metric instruments and label sets that were not modified in the most recent collection interval. The `TestProcessor` test is refactored to reduce indentation level. New tests are added for the delta and cumulative case, where a stateful aggregator may be called for and the no-memory configuration still suppresses reporting  for unmodified data.

Resolves #887.

### CODE REVIEW

File: example/prometheus/main.go [hunk 1]
```diff
@@ -105,5 +108,7 @@ func main() {
 		counter.Measurement(13.0),
 	)
 
-	time.Sleep(100 * time.Second)
+	fmt.Println("Example finished updating, please visit :2222")
```
Comment (lizthegrey) [inline example/prometheus/main.go:111]: are you sure you meant to leave this printf line here?

File: exporters/metric/prometheus/prometheus_test.go [hunk 2]
```diff
@@ -69,6 +74,8 @@ func TestPrometheusExporter(t *testing.T) {
 	expected = append(expected, `valuerecorder_sum{A="B",C="D",R="V"} 19.6`)
 
 	compareExport(t, exporter, expected)
+	time.Sleep(3 * time.Second)
```
Comment (lizthegrey) [inline exporters/metric/prometheus/prometheus_test.go:77]: this will make the tests take 3 seconds longer, is there another mechanism of forcing this e.g. by advancing a fake clock or do we really need the sleep?

File: sdk/metric/processor/basic/basic.go [hunk 3]
```diff
@@ -36,6 +36,16 @@ type (
 	}
 
 	stateKey struct {
+		// TODO: This code is organized to support multiple
```
Comment (lizthegrey) [inline sdk/metric/processor/basic/basic.go:39]: open an Issue for this and link it.

File: exporters/metric/prometheus/prometheus_test.go (hunk 2 above)
Comment (jmacd) [reply exporters/metric/prometheus/prometheus_test.go:77]: Thanks. I need to understand the caching mechanism used by the Prometheus server to debounce requests or supply a testable clock.

File: sdk/metric/processor/basic/basic.go (hunk 3 above)
Comment (jmacd) [reply sdk/metric/processor/basic/basic.go:39]: It's linked to #862.

File: exporters/metric/prometheus/prometheus_test.go (hunk 2 above)
Comment (jmacd) [reply exporters/metric/prometheus/prometheus_test.go]: Looks like I was mistaken. The test would fail without the sleep in the old code and I've removed it.

**Comment by jmacd** [comment]
Done

> - Prometheus exporter will not apply stale updates or forget inactive metrics. (#903)

File: sdk/metric/processor/basic/basic.go [hunk 4]
```diff
@@ -291,9 +308,12 @@ func (b *Processor) FinishCollection() error {
 
 	for key, value := range b.values {
 		mkind := key.descriptor.MetricKind()
+		stale := value.updated != b.finishedCollection
+		stateless := !value.stateful
 
-		if !value.stateful {
-			if value.updated != b.finishedCollection {
+		// If the
```
Comment (cbandy) [inline sdk/metric/processor/basic/basic.go:314]: This comment appears incomplete.

Comment (jmacd) [reply sdk/metric/processor/basic/basic.go]: Fixed.

File: sdk/metric/processor/basic/config.go [hunk 5]
```diff
@@ -0,0 +1,42 @@
...
+	// metrics that were not updated in the most recent interval.
+	Memory bool
+}
+
+type Option interface {
+	ApplyProcessor(*Config)
+}
+
+// WithMemory sets the memory behavior of a Processor.  If this is
+// true, the processor will report metrics instruments and label sets
```
Comment (MrAlias) [inline sdk/metric/processor/basic/config.go:31]:
```suggestion
// true, the processor will report metric instruments and label sets
```
