### PR TITLE
Fix duplicate logs across resources

### LINKED ISSUE #5782: OTLP log export duplicates logs across all present resources
### Description

When I call `Export` with a `[]log.Record` batch that includes records from multiple different resources, it includes _all_ logs for _every_ resource, resulting in duplicates and incorrect data.

Seems to be a simple error in code - this line just passes the full set of records along to `ScopeLogs`:

https://github.com/open-telemetry/opentelemetry-go/blob/1b8f785c02521efbee5141b3dd8577b4893a1569/exporters/otlp/otlplog/otlploggrpc/internal/transform/log.go#L65

I suppose it should either send only the subset for the current resource, or check against the resource `Equivalent()` as it populates the per-scope batches.

### Environment

- OS: Linux
- Architecture: x86_64
- Go Version: 1.23
- opentelemetry-go version:

(I'm aware this is out of date but afaict the issue exists on `master:`)

```
        go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc v0.52.0
        go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp v0.52.0
        go.opentelemetry.io/otel v1.27.0
        go.opentelemetry.io/otel/exporters/otlp/otlplog/otlploghttp v0.3.0
        go.opentelemetry.io/otel/exporters/otlp/otlptrace v1.27.0 // indirect
        go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp v1.27.0
        go.opentelemetry.io/otel/log v0.3.0
        go.opentelemetry.io/otel/sdk v1.27.0
        go.opentelemetry.io/otel/sdk/log v0.3.0
        go.opentelemetry.io/otel/sdk/metric v1.27.0 // indirect
        go.opentelemetry.io/otel/trace v1.27.0
        go.opentelemetry.io/proto/otlp v1.3.1
        go.opentelemetry.io/contrib/instrumentation/net/http/httptrace/otelhttptrace v0.52.0 // indirect
        go.opentelemetry.io/otel/exporters/otlp/otlplog/otlploggrpc v0.0.0-20240524160931-7c5e64cccc16 // indirect
        go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetricgrpc v1.27.0 // indirect
        go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetrichttp v1.27.0 // indirect
        go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc v1.27.0 // indirect
        go.opentelemetry.io/otel/metric v1.27.0 // indirect
```

### Steps To Reproduce

* Call `Export` with a `[]log.Record` with a heterogeneous set of resources.
* Verify that the OTLP collector equivalent receives logs multiple times, once with each resource.

Sorry this is verbal, I can try to put a code example together but figured the linked code would make it seem obvious!

### Expected behavior

I would expect the OTLP payload to divide the records across the resources. Instead, _all_ records are sent for _all_ resources.

So `[A1, A2, B3, B4]` ends up as `[A: [1, 2, 3, 4], B: [1, 2, 3, 4]}` when instead it should be `{A: [1, 2], B: [3, 4]}`.

### PR DESCRIPTION
**Pull request by pree-dew**
1. Create scope map with resource key to map the correct log record. 
2. Add test case with different resource and scope combination

Fixes #5782 

### Benchmarks

```
goos: darwin
goarch: arm64
pkg: go.opentelemetry.io/otel/exporters/otlp/otlplog/otlploggrpc/internal/transform
               │   old.txt   │               new.txt               │
               │   sec/op    │   sec/op     vs base                │
ResourceLogs-8   3.266µ ± 3%   1.100µ ± 5%  -66.33% (p=0.000 n=10)

               │   old.txt    │               new.txt                │
               │     B/op     │     B/op      vs base                │
ResourceLogs-8   8.297Ki ± 0%   2.430Ki ± 0%  -70.72% (p=0.000 n=10)

               │   old.txt   │              new.txt               │
               │  allocs/op  │ allocs/op   vs base                │
ResourceLogs-8   178.00 ± 0%   52.00 ± 0%  -70.79% (p=0.000 n=10)
```

### CODE REVIEW

**Comment by pree-dew** [comment]
@dmathieu all checks have passed except this one https://github.com/open-telemetry/opentelemetry-go/actions/runs/10809312925/job/29984151866?pr=5803, it looks flaky as it was passing in previous build.

Let me know your feedback on PR, open to discuss and fix it. :)

**Comment by pellared** [comment]
I will change the PR to draft until it is ready for review.

I think this PR removes the performance optimization from https://github.com/open-telemetry/opentelemetry-go/pull/5378. It seems undesirable. Can you add benchmark results to PR description once it is ready for review?

**Comment by pree-dew** [comment]
@pellared 

> I think this PR removes the performance optimization from https://github.com/open-telemetry/opentelemetry-go/pull/5378. It seems undesirable. Can you add benchmark results to PR description once it is ready for review?

Sure, I can bring back the pool in the PR if the benchmark doesn't match the performance requirement. Thanks for the feedback.

**Comment by pree-dew** [comment]
@pellared Added benchmarks in PR description.

File: exporters/otlp/otlplog/otlploggrpc/internal/transform/log_test.go [hunk 1]
```diff
@@ -226,6 +227,81 @@ func TestResourceLogs(t *testing.T) {
...
+		}.NewRecord())
+
+		out = append(out, logtest.RecordFactory{
+			Timestamp:            ts,
+			ObservedTimestamp:    obs,
+			Body:                 bodyB,
+			Attributes:           []api.KeyValue{alice},
+			Resource:             res2,
+			InstrumentationScope: &scope,
+		}.NewRecord())
```
Comment (pellared) [inline exporters/otlp/otlplog/otlploggrpc/internal/transform/log_test.go:285]: The log record bodies, attributes, etc. are set, but later they are not verified in the assertion.

I suggest removing setting fields which are not important for the unit test or make the assertions more strict.

Comment (pree-dew) [reply exporters/otlp/otlplog/otlploggrpc/internal/transform/log_test.go:285]: Makes sense @pellared , I will make the necessary changes.

**Review by XSAM — APPROVED** [review]
@pree-dew Thanks for the help! Good catch.

It overall looks good to me. I only have the test comment that needs to be solved.

File: exporters/otlp/otlplog/otlploggrpc/internal/transform/log_test.go [hunk 2]
```diff
@@ -226,6 +227,81 @@ func TestResourceLogs(t *testing.T) {
 	assert.Equal(t, want, ResourceLogs(records))
 }
 
+func TestResourceLogsPerResource(t *testing.T) {
```
[the remark this answers is not in the document]
Comment (pree-dew) [reply exporters/otlp/otlplog/otlploggrpc/internal/transform/log_test.go]: @XSAM It definitely make sense and as @pellared also highlighted in the previous comment we should have better(strict) assertions for this scenario, so it will address that also. I have addressed this and made suggested changes.


@XSAM Happy to help :). Feel free to tag me wherever I can help, I am very active on consumer side of opentelemetry. I would love to contribute more and help in this amazing project that you all are maintaining.

**Comment by pree-dew** [comment]
@XSAM @pellared looks like checks of `test-race` and `test-coverage` are facing some type of weird issue, it is not reproducible on my github and local, plus it is showing the error at a line that doesn't exists in current version of code. Can you help with this? or am I missing something.

**Comment by pellared** [comment]
@pree-dew, can you please sync with `main`?

**Comment by pree-dew** [comment]
@pellared Sync with main is done

File: exporters/otlp/otlplog/otlploggrpc/internal/transform/log.go [hunk 3]
```diff
@@ -28,71 +27,25 @@ func ResourceLogs(records []log.Record) []*lpb.ResourceLogs {
...
-		resourceLogsMapPool.Put(resMap)
-	}()
-	resourceLogsMap(&resMap, records)
+	resMap := make(map[attribute.Distinct]*lpb.ResourceLogs)
 
-	out := make([]*lpb.ResourceLogs, 0, len(resMap))
-	for _, rl := range resMap {
-		out = append(out, rl)
+	type key struct {
+		r  attribute.Distinct
```
Comment (pellared) [inline exporters/otlp/otlplog/otlploggrpc/internal/transform/log.go:33]: I am not sure how it is possible to setup the Go Logs SDK in a way that an exporter would receive a `[]log.Record` with a heterogeneous set of resources.

https://github.com/open-telemetry/opentelemetry-go/issues/5782#issuecomment-2352217170

**Review by pellared — COMMENTED** [review]
I am not sure how the bug was reproduced and if this a valid scenario.

On the other hand, I am surprised that it looks like this code has better performance (I have not analyzed why).

**Comment by pellared** [comment]
Closing per https://github.com/open-telemetry/opentelemetry-go/issues/5782#issuecomment-2352494455

However, it would be good to check why performance has been improved according to the benchmark.

**Comment by pellared** [comment]
Reopening per https://github.com/open-telemetry/opentelemetry-go/issues/5782#issuecomment-2354232278

File: exporters/otlp/otlplog/otlploggrpc/internal/transform/log.go (hunk 3 above)
Comment (pellared) [reply exporters/otlp/otlplog/otlploggrpc/internal/transform/log.go:33]: https://github.com/open-telemetry/opentelemetry-go/issues/5782#issuecomment-2352494455

**Review by pellared — APPROVED** [review]

File: exporters/otlp/otlplog/otlploggrpc/internal/transform/log_test.go [hunk 4]
```diff
@@ -182,76 +219,97 @@ var (
...
-	assert.Equal(t, want, ResourceLogs(records))
+	want := pbResourceLogsList
+	rLogs := ResourceLogs(records)
+	for _, got := range rLogs {
+		expected := want[1]
+		if got.Resource.Attributes[1].GetValue().GetStringValue() == "v0.1.1" {
+			expected = want[0]
+		}
+		assert.Equal(t, expected, got)
+	}
```
Comment (XSAM) [inline exporters/otlp/otlplog/otlploggrpc/internal/transform/log_test.go:312]:
```suggestion
	assert.Equal(t, want, ResourceLogs(records))
```

nit. This should be more clear.

File: CHANGELOG.md [hunk 5]
```diff
@@ -16,6 +16,7 @@ This project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.htm
 
 ### Fixed
 
+- Fix log records duplication in case of heterogeneous resource attributes by correctly mapping each log record to it's resource and scope. (#5782)
```
Comment (XSAM) [inline CHANGELOG.md:19]:
```suggestion
- Fix log records duplication in case of heterogeneous resource attributes by correctly mapping each log record to it's resource and scope. (#5803)
```

File: exporters/otlp/otlplog/otlploggrpc/internal/transform/log_test.go (hunk 4 above)
Comment (pree-dew) [reply exporters/otlp/otlplog/otlploggrpc/internal/transform/log_test.go:312]: when we construct the array of ResourceLogs we internally create a map and that changes the order so when comparing it directly it definitely is more clear but will make this test flaky depending on the order.

File: CHANGELOG.md (hunk 5 above)
Comment (pree-dew) [reply CHANGELOG.md]: Done.

File: exporters/otlp/otlplog/otlploggrpc/internal/transform/log_test.go (hunk 4 above)
Comment (pellared) [reply exporters/otlp/otlplog/otlploggrpc/internal/transform/log_test.go:312]: If you want to ignore order you can use https://pkg.go.dev/github.com/stretchr/testify/assert#ElementsMatch

Comment (pree-dew) [reply exporters/otlp/otlplog/otlploggrpc/internal/transform/log_test.go]: @pellared thank you for the suggestion, I learned something new today :)
 I have made the changes using this function and pushed.

**Review by dmathieu — APPROVED** [review]
