### PR TITLE
baggage: Fix Parse to validate member value before percent-decoding

### LINKED ISSUE #4241: baggage module fails to accept baggage produced by itself
### Description

In current implementation (otel@v1.16.0) of baggage propagation and parsing it is possible to pass value into baggage member, which is accepted, then inject given baggage into HeaderCarrier and then extract baggage from HeaderCarrier to find out, that baggage hasn't been successfully parsed.

### Steps To Reproduce
- Playground link https://go.dev/play/p/Edu6AMmhD2G with demonstration of given behavior.

Or

- Try to propagate `baggage.NewMember("ok-key", url.QueryEscape("messed,up%key"))` through HeaderCarrier

### Expected behavior
Parsed baggage contains member with key "ok-key" and value "messed,up%key"

### Other issues dealing with same problem
 - https://github.com/open-telemetry/opentelemetry-go/issues/3601
 - https://github.com/open-telemetry/opentelemetry-go/issues/3467

### Problem
In `baggage.parseMember()`  value of baggage is first [unescaped](https://github.com/open-telemetry/opentelemetry-go/blob/main/baggage/baggage.go#L314) and then is [checked](https://github.com/open-telemetry/opentelemetry-go/blob/main/baggage/baggage.go#L321) whether it contains "forbidden values" by W3C Baggage wire restriction.

#### Solution
Most obvious solution to me is to move check that value conforms to W3C Baggage right before unescaping that value, or completely remove that check.

### PR DESCRIPTION
**Pull request by pellared**
Fixes #4241

CC @Lim3nius

### CODE REVIEW

File: propagation/baggage_test.go [hunk 1]
```diff
@@ -47,7 +47,7 @@ func (m member) Member(t *testing.T) baggage.Member {
 		}
 		props = append(props, p)
 	}
-	bMember, err := baggage.NewMember(m.Key, url.QueryEscape(m.Value), props...)
+	bMember, err := baggage.NewMember(m.Key, url.PathEscape(m.Value), props...)
```
Comment (pellared) [inline propagation/baggage_test.go:50]: Opportunistic fix in test code.

See: https://go.dev/play/p/G9V8b31t_R7

**Review by Lim3nius — APPROVED** [review]
Looks good to me :+1:

**Review by hanyuancheung — APPROVED** [review]

**Review by dmathieu — APPROVED** [review]
