### PR TITLE
Do not use the user-defined empty set when comparing sets.

### LINKED ISSUE #7356: The empty set value should not change set equality
The empty set is mutable because it is not a set but a file-level pointer exposed to the user:

```go
func TestSetEqualsEmpty(t *testing.T) {
	e := attribute.EmptySet()
	empty := *e

	alt := attribute.NewSet(attribute.String("A", "B"))
	*e = alt

	var s attribute.Set
	assert.Truef(t, s.Equals(&empty), "expected %v to equal empty set %v", s, attribute.EmptySet())
}
```

```console
> go test -run=TestSetEqualsEmpty
--- FAIL: TestSetEqualsEmpty (0.00s)
    set_test.go:480:
        	Error Trace:	/home/tyler/go/src/go.opentelemetry.io/otel/attribute/set_test.go:480
        	Error:      	Should be true
        	Test:       	TestSetEqualsEmpty
        	Messages:   	expected {{<nil>}} to equal empty set &{{[{A {4 0 B <nil>}}]}}
FAIL
```

This test should pass.

### PR DESCRIPTION
**Pull request by MrAlias**
Fix #7356

### CODE REVIEW

File: attribute/set.go [hunk 1]
```diff
@@ -62,7 +72,11 @@ var (
 //
 // This is a convenience provided for optimized calling utility.
 func EmptySet() *Set {
```
Comment (bboreham) [inline attribute/set.go:74]: Should `EmptySet()` be deprecated?  Or a warning added to the docstring?

File: attribute/set.go [hunk 2]
```diff
@@ -62,7 +72,11 @@ var (
...
-	return emptySet
+	// Continue to return the pointer to the user-defined empty set for
+	// backwards-compatibility.
+	//
+	// New code should not use this, instead use emptySet.
+	return userDefinedEmptySet
```
Comment (dashpole) [inline attribute/set.go:79]: I assume we can't just do
```golang 
es := emptySet
return &es
```
for performance reasons?

Comment (MrAlias) [reply attribute/set.go:79]: Correct, that would allocate a pointer for each call.
