### PR TITLE
sdk/metric: Fix observable not registered error when the asynchronous instrument has a drop aggregation

### LINKED ISSUE #4666: view: observable instrument not registered for callback
Following runnable code with conditional view is not working and it prints `observable instrument not registered for callback `message. 

```
package main

import (
	"encoding/json"
	"log"
	"math/rand"
	"os"
	"time"

	"go.opentelemetry.io/contrib/instrumentation/runtime"
	"go.opentelemetry.io/otel/exporters/stdout/stdoutmetric"
	"go.opentelemetry.io/otel/sdk/metric"
	metricsdk "go.opentelemetry.io/otel/sdk/metric"

	"go.opentelemetry.io/otel"
)

func main() {

	// Print with a JSON encoder that indents with two spaces.
	enc := json.NewEncoder(os.Stdout)
	enc.SetIndent("", "  ")
	exporter, err := stdoutmetric.New(
		stdoutmetric.WithEncoder(enc),
		stdoutmetric.WithoutTimestamps(),
	)
	if err != nil {
		panic(err)
	}

	reader := metricsdk.NewPeriodicReader(exporter,
		metricsdk.WithInterval(5*time.Second))

	var drop metric.View = func(i metric.Instrument) (metric.Stream, bool) {
		if i.Name != "process.runtime.go.mem.heap_alloc" {
			return metricsdk.Stream{Aggregation: metricsdk.AggregationDrop{}}, true
		}
		return metricsdk.Stream{}, false
	}

	meterProvider := metricsdk.NewMeterProvider(
		metricsdk.WithReader(reader),
		metricsdk.WithView(drop),
	)
	otel.SetMeterProvider(meterProvider)

	log.Print("Starting runtime instrumentation:")
	err = runtime.Start(runtime.WithMinimumReadMemStatsInterval(time.Second))
	if err != nil {
		panic(err)
	}

	time.Sleep(99 * time.Minute)

}
```

If I remove the condition from the view and drop the aggregation, it works. 

```
	var drop metric.View = func(i metric.Instrument) (metric.Stream, bool) {
		return metricsdk.Stream{Aggregation: metricsdk.AggregationDrop{}}, true
	}
```

### PR DESCRIPTION
**Pull request by scorpionknifes**
Resolves #4666

When an observable instrument is dropped by view drop aggregation, it prints `observable instrument not registered for callback message`, as the instrument isn't register due to it being dropped.

https://github.com/open-telemetry/opentelemetry-go/blob/cb8cb2d2697d6932a6e56f5821da12c1aa62c371/sdk/metric/meter.go#L472-L480

This PR attempts to ignore the above code by adding a flag to the observable instrument indicating it has been dropped and ignoring registered check

### CODE REVIEW

File: sdk/metric/meter_test.go [hunk 1]
```diff
@@ -2064,3 +2068,208 @@ func TestHistogramBucketPrecedenceOrdering(t *testing.T) {
...
+		name                   string
+		views                  []View
+		expectedObservableName []string
+		expectedLogs           []map[string]interface{}
+	}{
+		{
+			name:  "default",
+			views: []View{},
+			expectedObservableName: []string{
+				"observable.int64.counter",
```
Comment (pellared) [inline sdk/metric/meter_test.go:2083]: Can we declare all the observable names in a `const` section in the beginning of the test?

I think it will make the test readable and easier to navigate.

Something like

```go
const (
  intCounterName = "observable.int64.counter"
  ...
  dropIntCounterName = "unregistered.observable.int64.counter"
```

File: sdk/metric/meter_test.go [hunk 2]
```diff
@@ -2064,3 +2068,208 @@ func TestHistogramBucketPrecedenceOrdering(t *testing.T) {
...
+			require.Len(t, rm.ScopeMetrics, 1)
+			require.Len(t, rm.ScopeMetrics[0].Metrics, len(tt.expectedObservableName))
+
+			for i, m := range rm.ScopeMetrics[0].Metrics {
+				assert.Equal(t, tt.expectedObservableName[i], m.Name)
+			}
+
+			if diff := cmp.Diff(logEntries, tt.expectedLogs,
+				cmpopts.IgnoreMapEntries(func(_ string, v interface{}) bool {
+					return v.(string) == "" // skip comparing empty values
```
Comment (pellared) [inline sdk/metric/meter_test.go:2268]: This looks wrong. I guess that the function inside `global.SetLogger(` invocation should make sure to not add such entries.

Then we should also be able to use `assert.Equal` instead of `cmp.Diff`.

File: sdk/metric/meter_test.go [hunk 3]
```diff
@@ -2064,3 +2068,208 @@ func TestHistogramBucketPrecedenceOrdering(t *testing.T) {
...
+						logEntries = append(logEntries, entry)
+					},
+					funcr.Options{Verbosity: 0},
+				),
+			)
+
+			reader := NewManualReader()
+			meter := NewMeterProvider(WithView(tt.views...), WithReader(reader)).Meter("TestObservableDropAggregation")
+
+			aiCounter, err := meter.Int64ObservableCounter("observable.int64.counter")
```
Comment (pellared) [inline sdk/metric/meter_test.go:2213]: nit: can we rename the names from `aiCounter` to eg. `intCnt`. The `ai` prefix is cryptic while `cnt` is rather a common shorthand for `counter`. `hist` can be used for Histogram. `udcnt` for UpDownCounter

File: sdk/metric/meter_test.go [hunk 4]
```diff
@@ -2064,3 +2068,208 @@ func TestHistogramBucketPrecedenceOrdering(t *testing.T) {
 		})
 	}
 }
+
+func TestObservableDropAggregation(t *testing.T) {
+	testcases := []struct {
+		name                   string
+		views                  []View
+		expectedObservableName []string
```
Comment (pellared) [inline sdk/metric/meter_test.go:2076]:
```suggestion
		wantObservables []string
```

File: sdk/metric/meter_test.go [hunk 5]
```diff
@@ -2064,3 +2068,208 @@ func TestHistogramBucketPrecedenceOrdering(t *testing.T) {
...
+		expectedLogs           []map[string]interface{}
```
Comment (pellared) [inline sdk/metric/meter_test.go:2077]:
```suggestion
		wantLogs           []map[string]interface{}
```

File: CHANGELOG.md [hunk 6]
```diff
@@ -33,6 +33,7 @@ This project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.htm
 ### Fixed
 
 - Fix `Parse` in `go.opentelemetry.io/otel/baggage` to validate member value before percent-decoding. (#4755)
+- Fix `observable` not registered error during drop aggregation in `go.opentelemetry.io/otel/sdk/metric`. (#4760)
```
Comment (pellared) [inline CHANGELOG.md:36]:
```suggestion
- Fix observable not registered error when the asynchronous instrument has a drop aggregation in `go.opentelemetry.io/otel/sdk/metric`. (#4772)
```

File: sdk/metric/meter_test.go [hunk 7]
```diff
@@ -2109,167 +2118,157 @@ func TestObservableDropAggregation(t *testing.T) {
...
 				funcr.NewJSON(
 					func(obj string) {
 						var entry map[string]interface{}
 						_ = json.Unmarshal([]byte(obj), &entry)
-						logEntries = append(logEntries, entry)
+
+						// All unregistered observables should log `errUnregObserver` error.
+						// A observable with drop aggregation is also unregistered,
+						// however this is expected and should not log an error.
+						require.Equal(t, errUnregObserver.Error(), entry["error"])
```
Comment (pellared) [inline sdk/metric/meter_test.go:2201]: We can still continue the test to find other possible issues.

```suggestion
						assert.Equal(t, errUnregObserver.Error(), entry["error"])
```

File: sdk/metric/meter_test.go [hunk 8]
```diff
@@ -2064,3 +2066,209 @@ func TestHistogramBucketPrecedenceOrdering(t *testing.T) {
...
+				intCntName, intUDCntName, intGaugeName,
+				floatCntName, floatUDCntName, floatGaugeName,
+			},
+			wantUnregLogs: nil,
+		},
+	}
+	for _, tt := range testcases {
+		t.Run(tt.name, func(t *testing.T) {
+			var unregLogs []log
+			global.SetLogger(
```
Comment (pellared) [inline sdk/metric/meter_test.go:2192]:
```suggestion
			otel.SetLogger(
```

File: sdk/metric/meter_test.go [hunk 9]
```diff
@@ -2064,3 +2066,209 @@ func TestHistogramBucketPrecedenceOrdering(t *testing.T) {
...
+
+						unregLogs = append(unregLogs, log{
+							name:   fmt.Sprintf("%v", entry["name"]),
+							number: fmt.Sprintf("%v", entry["number"]),
+						})
+					},
+					funcr.Options{Verbosity: 0},
+				),
+			)
+			defer global.SetLogger(logr.Discard())
```
Comment (pellared) [inline sdk/metric/meter_test.go:2211]:
```suggestion
			defer otel.SetLogger(logr.Discard())
```

**Review by pellared — APPROVED** [review]
Just nit comments.

@MrAlias @MadVikingGod @dashpole, can you check if the way how it is fixed in `meter.go` and `instrument.go` is acceptable?

**Review by hanyuancheung — APPROVED** [review]

File: sdk/metric/meter.go [hunk 10]
```diff
@@ -436,6 +438,11 @@ func (r observer) ObserveFloat64(o metric.Float64Observable, v float64, opts ...
 		return
 	}
 
+	if oImpl.dropAggregation {
```
Comment (MrAlias) [inline sdk/metric/meter.go:441]: This assumes only the drop aggregation is used for this instrument. There may be other measures that need to recorded here.

**Review by MrAlias — CHANGES_REQUESTED** [review]

File: sdk/metric/meter.go (hunk 10 above)
Comment (scorpionknifes) [reply sdk/metric/meter.go]: Good point! I've changed it to only effect whether we log the error https://github.com/open-telemetry/opentelemetry-go/blob/875fca6bd0fb97b17f54db717a67b097adea2130/sdk/metric/meter.go#L478-L486

File: sdk/metric/meter.go [hunk 11]
```diff
@@ -437,12 +440,14 @@ func (r observer) ObserveFloat64(o metric.Float64Observable, v float64, opts ...
 	}
 
 	if _, registered := r.float64[oImpl.observablID]; !registered {
```
Comment (MrAlias) [inline sdk/metric/meter.go:442]:
```suggestion
	if _, registered := r.float64[oImpl.observablID]; !registered && !oImpl.dropAggregation {
```

Reduces indentation.

File: sdk/metric/meter.go [hunk 12]
```diff
@@ -436,7 +439,7 @@ func (r observer) ObserveFloat64(o metric.Float64Observable, v float64, opts ...
 		return
 	}
 
-	if _, registered := r.float64[oImpl.observablID]; !registered {
+	if _, registered := r.float64[oImpl.observablID]; !registered && !oImpl.dropAggregation {
```
Comment (MrAlias) [inline sdk/metric/meter.go:442]: I made a mistake in my last suggestion. The conditional block before did not include the return, now the unified one does. This means that now if an instrument has a drop aggregator this block will be skipped and the return not executed. That is not what we want given we do not want to run the code below.

Sorry for my mistake, can you please revert my last suggestion. :facepalm:

**Review by MrAlias — APPROVED** [review]
