### PR TITLE
Use a DropReservoir when an exemplar.AlwaysOffFilter is provided

### LINKED ISSUE #6260: Synchronous metrics memory usage
### Description

I recently ported a service that was instrumented using prometheus prom client to use OTEL SDK with an OTLP GRPC exporter instead. The service uses quite a few synchronous counters and I noticed that the memory usage, when switching to use OTEL SDK, grew out of proportions - so much so I must consider abandoning the OTEL track for this service. Why is the OTEL SDK using so much memory? Am I doing something wrong in my instrumentation code - like not disabling something memory hungry that is on per default. 

### Environment

- OS: Any OS, but tested on Linux and MacOS
- Architecture: Any platform 
- Go Version: 1.22 (but doubtful that it depends on the golang version)
- opentelemetry-go version: v1.34.0

### Steps To Reproduce

Test program using Prometheus instrumentation: 
```golang
package main

import (
	"fmt"
	"net/http"
	"time"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promhttp"
)

const N_COUNTERS = 1000

var counters []prometheus.Counter

func init() {
	for i := 0; i < N_COUNTERS; i++ {
		counter := prometheus.NewCounter(
			prometheus.CounterOpts{
				Name: fmt.Sprintf("counter_%d", i),
				Help: "A counter that gets updated periodically",
			},
		)

		// Register the custom metric with Prometheus
		prometheus.MustRegister(counter)
		counters = append(counters, counter)
	}
}

func main() {
	// Expose the registered metrics via an HTTP server
	http.Handle("/metrics", promhttp.Handler())

	// Increment the counter every second
	go func() {
		for {
			for i := 0; i < N_COUNTERS; i++ {
				counters[i].Inc()
			}
			time.Sleep(1 * time.Second)
		}
	}()

	addr := ":9090"
	fmt.Printf("Starting server on %s...\n", addr)
	if err := http.ListenAndServe(addr, nil); err != nil {
		fmt.Println("Error starting server:", err)
	}
}
```

The above was then converted to the equivalent (or so I think, am I doing something wrong?) with OTEL SDK and OTLP GRPC exporter, like so: 

```golang
package main

import (
	"context"
	"fmt"
	"log"
	"time"

	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetricgrpc"
	otelmetric "go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/sdk/metric"
)

const N_COUNTERS = 1000

var counters []otelmetric.Int64Counter
var meter = otel.Meter("otel/target")

func init() {
	// Set up meter provider.
	meterProvider, err := newMeterProvider()
	if err != nil {
		log.Fatal(err)
	}

	otel.SetMeterProvider(meterProvider)

	// setup the counters

	for i := 0; i < N_COUNTERS; i++ {
		counter, _ := meter.Int64Counter(
			fmt.Sprintf("counter_%d", i),
			otelmetric.WithDescription("A counter that gets updated periodically"),
		)

		counters = append(counters, counter)
	}
}

func newMeterProvider() (*metric.MeterProvider, error) {
	ctx := context.Background()
	metricExporter, err := otlpmetricgrpc.New(ctx)
	if err != nil {
		panic(err)
	}

	meterProvider := metric.NewMeterProvider(
		metric.WithReader(
			metric.NewPeriodicReader(metricExporter,
				// set to 15 in order to match the
				// scrape interval used by Prometheus in the
				// experiment
				metric.WithInterval(15*time.Second),
			)),
	)
	return meterProvider, nil
}

func main() {
	// Increment the counter every second
	go func() {
		ctx := context.Background()
		for {
			for i := 0; i < N_COUNTERS; i++ {
				counters[i].Add(ctx, 1)
			}
			time.Sleep(10 * time.Second)
		}
	}()

	ch := make(chan bool)
	<-ch
}
```

When this is run, the memory usage of the prometheus code (as shown via top) is around 6194K and the memory for the OTEL SDK port is using 29M, so perhaps 5 times more memory for the OTEL SDK equivalent. 

### Expected behavior

The expected behaviour is that the OTEL SDK instrumented code wouldn't use that much more memory than the Prometheus alternative, so that one can motivate migrating to a solution away from Prometheus. Or is there anything wrong with the OTEL instrumentation above or that one can do something about this to make the memory consumption lower?

### PR DESCRIPTION
**Pull request by dashpole**
Fixes https://github.com/open-telemetry/opentelemetry-go/issues/6260, https://github.com/open-telemetry/opentelemetry-go/issues/6333

The [spec for always off](https://github.com/open-telemetry/opentelemetry-specification/blob/d500678e4612b56ff2cd5f03e67cd845977d1746/specification/metrics/sdk.md#alwaysoff) suggests this should "disable" the Exemplar feature:

> An ExemplarFilter which makes no measurements eligible for being an Exemplar.
Using this ExemplarFilter is as good as disabling the Exemplar feature.

There were a few reports of much higher memory usage when exemplars were added.  I looked into the reports, and it looks like exemplar reservoirs are expensive in terms of memory compared to the aggregation itself. Ideally, we shouldn't construct the reservoir when an AlwaysOff exemplar filter is used.

I couldn't find a super clean way to do this... `exemplar.AlwaysOffFilter` is a function, so I couldn't easily compare it without comparing the pointers. I'm open to other suggestions. The internet says that compiler optimizations could cause this logic to fail, but worst-case you get the existing behavior.

### Benchmarks

I needed a benchmark that creates a new attribute set for each call to be able to see how much memory each attribute set uses, so I added a new one, and ran it against main.

Overall, it reduces the amount of memory used per-attribute-set by 70-88%, which is pretty substantial.

Overall, 

```
                                                  │   old.txt   │               new.txt               │
                                                  │   sec/op    │    sec/op     vs base               │
BenchmarkMeasureNewAttributeSet/AlwaysOn/Int64Counter-24            3.523µ ± 2%   3.745µ ± 29%   +6.32% (p=0.002 n=6)
BenchmarkMeasureNewAttributeSet/AlwaysOn/Float64Counter-24          3.714µ ± 6%   3.879µ ±  5%        ~ (p=0.132 n=6)
BenchmarkMeasureNewAttributeSet/AlwaysOn/Int64UpDownCounter-24      3.811µ ± 8%   3.941µ ±  5%        ~ (p=0.065 n=6)
BenchmarkMeasureNewAttributeSet/AlwaysOn/Float64UpDownCounter-24    3.714µ ± 5%   3.822µ ±  1%        ~ (p=0.132 n=6)
BenchmarkMeasureNewAttributeSet/AlwaysOn/Int64Histogram-24          3.126µ ± 4%   3.333µ ±  4%   +6.61% (p=0.004 n=6)
BenchmarkMeasureNewAttributeSet/AlwaysOn/Float64Histogram-24        3.099µ ± 4%   3.204µ ±  8%        ~ (p=0.093 n=6)
BenchmarkMeasureNewAttributeSet/AlwaysOn/Int64Gauge-24              3.745µ ± 7%   3.902µ ±  4%        ~ (p=0.240 n=6)
BenchmarkMeasureNewAttributeSet/AlwaysOn/Float64Gauge-24            3.746µ ± 7%   3.862µ ±  2%        ~ (p=0.102 n=6)
BenchmarkMeasureNewAttributeSet/AlwaysOff/Int64Counter-24           3.621µ ± 3%   1.665µ ±  1%  -54.00% (p=0.002 n=6)
BenchmarkMeasureNewAttributeSet/AlwaysOff/Float64Counter-24         3.639µ ± 2%   1.686µ ±  4%  -53.68% (p=0.002 n=6)
BenchmarkMeasureNewAttributeSet/AlwaysOff/Int64UpDownCounter-24     3.563µ ± 4%   1.700µ ±  4%  -52.29% (p=0.002 n=6)
BenchmarkMeasureNewAttributeSet/AlwaysOff/Float64UpDownCounter-24   3.634µ ± 1%   1.690µ ±  4%  -53.49% (p=0.002 n=6)
BenchmarkMeasureNewAttributeSet/AlwaysOff/Int64Histogram-24         2.892µ ± 2%   2.005µ ±  2%  -30.66% (p=0.002 n=6)
BenchmarkMeasureNewAttributeSet/AlwaysOff/Float64Histogram-24       2.962µ ± 5%   2.057µ ±  6%  -30.55% (p=0.002 n=6)
BenchmarkMeasureNewAttributeSet/AlwaysOff/Int64Gauge-24             3.692µ ± 5%   1.599µ ±  2%  -56.68% (p=0.002 n=6)
BenchmarkMeasureNewAttributeSet/AlwaysOff/Float64Gauge-24           3.651µ ± 3%   1.612µ ±  2%  -55.86% (p=0.002 n=6)
geomean                                             3.495µ        2.541µ        -27.30%

                                                  │   old.txt    │               new.txt               │
                                                  │     B/op     │     B/op      vs base               │
BenchmarkMeasureNewAttributeSet/AlwaysOn/Int64Counter-24            3.107Ki ± 0%   3.107Ki ± 0%        ~ (p=0.121 n=6)
BenchmarkMeasureNewAttributeSet/AlwaysOn/Float64Counter-24          3.108Ki ± 0%   3.107Ki ± 0%        ~ (p=0.177 n=6)
BenchmarkMeasureNewAttributeSet/AlwaysOn/Int64UpDownCounter-24      3.108Ki ± 0%   3.108Ki ± 0%        ~ (p=0.675 n=6)
BenchmarkMeasureNewAttributeSet/AlwaysOn/Float64UpDownCounter-24    3.107Ki ± 0%   3.107Ki ± 0%        ~ (p=1.000 n=6)
BenchmarkMeasureNewAttributeSet/AlwaysOn/Int64Histogram-24          2.622Ki ± 0%   2.622Ki ± 0%        ~ (p=0.394 n=6)
BenchmarkMeasureNewAttributeSet/AlwaysOn/Float64Histogram-24        2.622Ki ± 0%   2.622Ki ± 0%        ~ (p=0.636 n=6)
BenchmarkMeasureNewAttributeSet/AlwaysOn/Int64Gauge-24              3.108Ki ± 0%   3.107Ki ± 0%        ~ (p=0.167 n=6)
BenchmarkMeasureNewAttributeSet/AlwaysOn/Float64Gauge-24            3.107Ki ± 0%   3.108Ki ± 0%        ~ (p=0.182 n=6)
BenchmarkMeasureNewAttributeSet/AlwaysOff/Int64Counter-24            3182.0 ± 0%     361.0 ± 0%  -88.65% (p=0.002 n=6)
BenchmarkMeasureNewAttributeSet/AlwaysOff/Float64Counter-24          3182.5 ± 0%     360.5 ± 0%  -88.67% (p=0.002 n=6)
BenchmarkMeasureNewAttributeSet/AlwaysOff/Int64UpDownCounter-24      3182.0 ± 0%     359.5 ± 1%  -88.70% (p=0.002 n=6)
BenchmarkMeasureNewAttributeSet/AlwaysOff/Float64UpDownCounter-24    3182.0 ± 0%     361.0 ± 0%  -88.65% (p=0.002 n=6)
BenchmarkMeasureNewAttributeSet/AlwaysOff/Int64Histogram-24          2684.0 ± 0%     773.0 ± 0%  -71.20% (p=0.002 n=6)
BenchmarkMeasureNewAttributeSet/AlwaysOff/Float64Histogram-24        2684.0 ± 0%     773.0 ± 0%  -71.20% (p=0.002 n=6)
BenchmarkMeasureNewAttributeSet/AlwaysOff/Int64Gauge-24              3182.0 ± 0%     361.0 ± 1%  -88.65% (p=0.002 n=6)
BenchmarkMeasureNewAttributeSet/AlwaysOff/Float64Gauge-24            3182.0 ± 0%     361.0 ± 0%  -88.65% (p=0.002 n=6)
geomean                                             2.978Ki        1.127Ki       -62.17%

                                                  │   old.txt   │               new.txt               │
                                                  │  allocs/op  │ allocs/op   vs base                 │
BenchmarkMeasureNewAttributeSet/AlwaysOn/Int64Counter-24             12.00 ± 0%   12.00 ± 0%        ~ (p=1.000 n=6) ¹
BenchmarkMeasureNewAttributeSet/AlwaysOn/Float64Counter-24           12.00 ± 0%   12.00 ± 0%        ~ (p=1.000 n=6) ¹
BenchmarkMeasureNewAttributeSet/AlwaysOn/Int64UpDownCounter-24       12.00 ± 0%   12.00 ± 0%        ~ (p=1.000 n=6) ¹
BenchmarkMeasureNewAttributeSet/AlwaysOn/Float64UpDownCounter-24     12.00 ± 0%   12.00 ± 0%        ~ (p=1.000 n=6) ¹
BenchmarkMeasureNewAttributeSet/AlwaysOn/Int64Histogram-24           13.00 ± 0%   13.00 ± 0%        ~ (p=1.000 n=6) ¹
BenchmarkMeasureNewAttributeSet/AlwaysOn/Float64Histogram-24         13.00 ± 0%   13.00 ± 0%        ~ (p=1.000 n=6) ¹
BenchmarkMeasureNewAttributeSet/AlwaysOn/Int64Gauge-24               12.00 ± 0%   12.00 ± 0%        ~ (p=1.000 n=6) ¹
BenchmarkMeasureNewAttributeSet/AlwaysOn/Float64Gauge-24             12.00 ± 0%   12.00 ± 0%        ~ (p=1.000 n=6) ¹
BenchmarkMeasureNewAttributeSet/AlwaysOff/Int64Counter-24           12.000 ± 0%   7.000 ± 0%  -41.67% (p=0.002 n=6)
BenchmarkMeasureNewAttributeSet/AlwaysOff/Float64Counter-24         12.000 ± 0%   7.000 ± 0%  -41.67% (p=0.002 n=6)
BenchmarkMeasureNewAttributeSet/AlwaysOff/Int64UpDownCounter-24     12.000 ± 0%   7.000 ± 0%  -41.67% (p=0.002 n=6)
BenchmarkMeasureNewAttributeSet/AlwaysOff/Float64UpDownCounter-24   12.000 ± 0%   7.000 ± 0%  -41.67% (p=0.002 n=6)
BenchmarkMeasureNewAttributeSet/AlwaysOff/Int64Histogram-24         13.000 ± 0%   9.000 ± 0%  -30.77% (p=0.002 n=6)
BenchmarkMeasureNewAttributeSet/AlwaysOff/Float64Histogram-24       13.000 ± 0%   9.000 ± 0%  -30.77% (p=0.002 n=6)
BenchmarkMeasureNewAttributeSet/AlwaysOff/Int64Gauge-24             12.000 ± 0%   7.000 ± 0%  -41.67% (p=0.002 n=6)
BenchmarkMeasureNewAttributeSet/AlwaysOff/Float64Gauge-24           12.000 ± 0%   7.000 ± 0%  -41.67% (p=0.002 n=6)
geomean                                              12.24        9.553       -21.97%
¹ all samples are equal
```

Gemini helped me write this.

### CODE REVIEW

File: sdk/metric/exemplar_test.go [hunk 1]
```diff
@@ -59,3 +62,18 @@ func TestFixedSizeExemplarConcurrentSafe(t *testing.T) {
...
+		exemplar.AlwaysOffFilter,
+	)
+
+	res := f(*attribute.EmptySet())
+	require.Contains(
+		t,
+		reflect.TypeOf(res).String(),
+		"dropRes",
+		"reservoirFunc should return DropReservoir when AlwaysOffFilter is used",
+	)
```
[the remark this answers is not in the document]
Comment (dashpole) [reply sdk/metric/exemplar_test.go]: https://github.com/open-telemetry/opentelemetry-go/pull/8211/changes/eba654749221d8fb36901c6ccbc4a6b179216401

File: sdk/metric/internal/aggregate/aggregate.go [hunk 2]
```diff
@@ -54,7 +54,7 @@ func (b Builder[N]) resFunc() func(attribute.Set) FilteredExemplarReservoir[N] {
 		return b.ReservoirFunc
 	}
 
-	return dropReservoir
+	return DropReservoir
 }
```
[the remark this answers is not in the document]
Comment (dashpole) [reply sdk/metric/internal/aggregate/aggregate.go:58]: https://github.com/open-telemetry/opentelemetry-go/pull/8211/changes/2463fedd13436e30f815215922a3b073abdf5ce6

File: sdk/metric/exemplar.go [hunk 3]
```diff
@@ -22,6 +23,12 @@ func reservoirFunc[N int64 | float64](
 	provider exemplar.ReservoirProvider,
 	filter exemplar.Filter,
 ) func(attribute.Set) aggregate.FilteredExemplarReservoir[N] {
+	if filter == nil {
+		return aggregate.DropReservoir[N]
+	}
```
[the remark this answers is not in the document]
Comment (dashpole) [reply sdk/metric/exemplar.go]: https://github.com/open-telemetry/opentelemetry-go/pull/8211/changes/01baf2188f97eb581faa6fea0b680fba5f0c5a51

File: sdk/metric/benchmark_test.go [hunk 4]
```diff
@@ -732,3 +732,123 @@ func appendAttributes(kvs []attribute.KeyValue, number int) []attribute.KeyValue
...
+					)
+					meter := provider.Meter("BenchmarkMeasureNewAttributeSet")
+					record := inst.make(b, meter)
+
+					b.ReportAllocs()
+					b.ResetTimer()
+
+					for n := 0; n < b.N; n++ {
+						record(n)
+					}
```
[the remark this answers is not in the document]
Comment (dashpole) [reply sdk/metric/benchmark_test.go:854]: https://github.com/open-telemetry/opentelemetry-go/pull/8211/commits/f252a8d21fa1de361b2504837c199a2c60ed6c82

File: sdk/metric/config.go [hunk 5]
```diff
@@ -162,6 +162,9 @@ func WithView(views ...View) Option {
 // [exemplar.AlwaysOffFilter].
 func WithExemplarFilter(filter exemplar.Filter) Option {
 	return optionFunc(func(cfg config) config {
+		if filter == nil {
+			return cfg
+		}
```
[the remark this answers is not in the document]
Comment (dashpole) [reply sdk/metric/config.go]: https://github.com/open-telemetry/opentelemetry-go/pull/8221

**Review by MrAlias — APPROVED** [review]

File: sdk/metric/exemplar.go [hunk 6]
```diff
@@ -22,6 +23,9 @@ func reservoirFunc[N int64 | float64](
 	provider exemplar.ReservoirProvider,
 	filter exemplar.Filter,
 ) func(attribute.Set) aggregate.FilteredExemplarReservoir[N] {
+	if filter != nil && reflect.ValueOf(filter).Pointer() == reflect.ValueOf(exemplar.AlwaysOffFilter).Pointer() {
```
Comment (MrAlias) [inline sdk/metric/exemplar.go:26]: I think this is the best we can do, FWIW.

File: sdk/metric/exemplar.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (dashpole) [reply sdk/metric/exemplar.go]: https://github.com/open-telemetry/opentelemetry-go/pull/8211/changes/25e8244c4d1025d97c56c804131439c7f925ffb2

File: CHANGELOG.md [hunk 7]
```diff
@@ -30,6 +30,7 @@ This project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.htm
 - `ErrorType` in `go.opentelemetry.io/otel/semconv` now unwraps errors created with `fmt.Errorf` when deriving the `error.type` attribute. (#8133)
 - `go.opentelemetry.io/otel/sdk/log` now unwraps error chains created with `fmt.Errorf` when deriving the `error.type` attribute from errors on log records. (#8133)
 - `Set.MarshalLog` method in `go.opentelemetry.io/otel/attribute` now uses `Value.String` formatting following the [OpenTelemetry AnyValue representation for non-OTLP protocols](https://opentelemetry.io/docs/specs/otel/common/#anyvalue). (#8169)
+- Optimize `go.opentelemetry.io/otel/sdk/metric` to return a drop reservoir when `exemplar.AlwaysOffFilter` is configured.
```
Comment (pellared) [inline CHANGELOG.md]:
```suggestion
- Optimize `go.opentelemetry.io/otel/sdk/metric` to return a drop reservoir when `exemplar.AlwaysOffFilter` is configured. (#8211)
```

File: sdk/metric/config.go (hunk 5 above)
Comment (pellared) [inline sdk/metric/config.go]: Is it not a behavioral change for the end users? Was not passing `nil` previously been an invalid configuration? I guess it was causing a `panic` when `filteredExemplarReservoir.Offer` was called. If so then I would rather split it to a separate PR. _Sorry for not debugging it myself._

File: CHANGELOG.md (hunk 7 above)
Comment (pellared) [reply CHANGELOG.md]: or `WithExemplarFilter(nil)` :wink:

File: sdk/metric/config.go (hunk 5 above)
Comment (dashpole) [reply sdk/metric/config.go]: I can split it out.  Yes, it would cause a panic.

Comment (pellared) [reply sdk/metric/config.go]: I think it would be nice to have this spitted and have a separate changelog entry for this.

File: CHANGELOG.md (hunk 7 above)
Comment (dashpole) [reply CHANGELOG.md]: done

File: sdk/metric/config.go (hunk 5 above)
Comment (dashpole) [reply sdk/metric/config.go]: Removed from this PR.

Comment (dashpole) [reply sdk/metric/config.go]: https://github.com/open-telemetry/opentelemetry-go/pull/8211

**Review by dmathieu — APPROVED** [review]

File: sdk/metric/internal/aggregate/drop.go [hunk 8]
```diff
@@ -10,8 +10,8 @@ import (
 	"go.opentelemetry.io/otel/sdk/metric/exemplar"
 )
 
-// dropReservoir returns a [FilteredReservoir] that drops all measurements it is offered.
-func dropReservoir[N int64 | float64](attribute.Set) FilteredExemplarReservoir[N] {
+// DropReservoir returns a [FilteredExemplarReservoir] that drops all measurements it is offered.
+func DropReservoir[N int64 | float64](attribute.Set) FilteredExemplarReservoir[N] {
```
Comment (flc1125) [inline sdk/metric/internal/aggregate/drop.go:14]: This parameter (`attribute.Set`) is currently not being used, so it seems that we can remove it

Comment (MrAlias) [reply sdk/metric/internal/aggregate/drop.go:14]: It will not satisfy the `Reservoir` interface if it is removed.

**Review by pellared — APPROVED** [review]
