### PR TITLE
Split large jaeger span batch to admire the udp packet size limit 

### LINKED ISSUE #1828: Jaeger exporter drops batches of spans exceeding the UDP packet size limit
### Description

The Jaeger exporter, when configured with and agent endpoint that it will spans to via UDP, will fail to send any spans if the batch of spans when serialized in the thrift buffer exceeds the UDP max packet size. Instead it will return [an error](https://github.com/open-telemetry/opentelemetry-go/blob/70bc9eb391965ba22e4d9f938dc300f7e9fbc128/exporters/trace/jaeger/agent.go#L119-L122) saying the data does not fit within one UDP packet and will drop the batch of spans.

### Environment

- OS: Linux 5.11.7-arch1-1
- Architecture: x86_64
- Go Version: 1.16
- opentelemetry-go version: [a2bf04d](https://github.com/open-telemetry/opentelemetry-go/commit/a2bf04dc367dbd2828423e629975935377ea7a65)

### Steps To Reproduce

1. Using:
   ```
   import (
   	"context"
   	"testing"
   
   	"github.com/stretchr/testify/assert"
   	"go.opentelemetry.io/otel"
   	"go.opentelemetry.io/otel/exporters/trace/jaeger"
   	tracesdk "go.opentelemetry.io/otel/sdk/export/trace"
   )
   
   type errorHandler struct{ t *testing.T }
   
   func (eh errorHandler) Handle(err error) { assert.NoError(eh.t, err) }
   
   func TestJaegerAgentUDPLimitBatching(t *testing.T) {
   	otel.SetErrorHandler(errorHandler{t})
   
   	n := 1500
   	s := make([]*tracesdk.SpanSnapshot, n)
   	for i := 0; i < n; i++ {
   		s[i] = &tracesdk.SpanSnapshot{}
   	}
   	exp, err := jaeger.NewRawExporter(
   		jaeger.WithAgentEndpoint("localhost:0"),
   		jaeger.WithBatchMaxCount(n+1),
   		jaeger.WithBufferMaxCount(n+1),
   	)
   	assert.NoError(t, err)
   
   	ctx := context.Background()
   	assert.NoError(t, exp.ExportSpans(ctx, s))
   	assert.NoError(t, exp.Shutdown(ctx))
   }
   ```
3. Run `go test .`
4. See
   ```
   --- FAIL: TestJaegerAgentUDPLimitBatching (0.00s)
       bug_test.go:15: 
           	Error Trace:	bug_test.go:15
           	            				handler.go:60
           	            				handler.go:88
           	            				jaeger.go:124
           	            				bundler.go:324
           	            				asm_amd64.s:1371
           	Error:      	Received unexpected error:
           	            	data does not fit within one UDP packet; size 79559, max 65000, spans 1500
           	Test:       	TestJaegerAgentUDPLimitBatching
   FAIL
   FAIL	testing/jaeger-udp-bug	0.007s
   FAIL
   ```

### Expected behavior

The exporter should batch any bundles larger than the max payload size. This is what [the Jaeger Go client does](https://github.com/jaegertracing/jaeger-client-go/blob/ba87d35db7991cab81ba9bed697d17a2433b83eb/transport_udp.go). Possibly that library should be leveraged for our transport or we need to implement similar logic to check the thrift buffer is appropriately split into send-able payloads.

### PR DESCRIPTION
**Pull request by tianyaqu**
Adds a  `splitAndFlush` method to split large batch into small ones which will not exceed the udp packet limit.
Should resolve #1828

### CODE REVIEW

File: exporters/trace/jaeger/agent.go [hunk 1]
```diff
@@ -124,6 +132,46 @@ func (a *agentClientUDP) EmitBatch(ctx context.Context, batch *gen.Batch) error
...
+	totalSize := processSize
+	var spans []*gen.Span
+	for _, span := range batch.Spans {
+		spanSize := a.calcSizeOfSerializedThrift(ctx, span)
+		if spanSize+processSize >= a.maxPacketSize {
+			// drop the span that exceeds the limit
+			continue
+		}
+		if totalSize+spanSize >= a.maxPacketSize {
+			err = a.Flush(ctx, &gen.Batch{
```
Comment (MrAlias) [inline exporters/trace/jaeger/agent.go:155]: Does this work? `a.Flush` calls `EmitBatch`, `EmitBatch` calls this `splitAndFlush`. This looks like an infinite loop.

Comment (tianyaqu) [reply exporters/trace/jaeger/agent.go:155]: > Does this work? `a.Flush` calls `EmitBatch`, `EmitBatch` calls this `splitAndFlush`. This looks like an infinite loop.

There are two different`EmitBatch` methods. `EmitBatch`of `agentClientUDP` calls `splitAndFlush` to do the splitting work; `a.Flush` calls the jaeger thrift client stub function `EmitBatch `.

File: exporters/trace/jaeger/agent.go [hunk 2]
```diff
@@ -124,6 +132,46 @@ func (a *agentClientUDP) EmitBatch(ctx context.Context, batch *gen.Batch) error
...
+			})
+			spans = spans[:0]
+			totalSize = processSize
+		}
+		totalSize += spanSize
+		spans = append(spans, span)
+	}
+
+	if len(spans) > 0 {
+		err = a.Flush(ctx, &gen.Batch{
```
Comment (MrAlias) [inline exporters/trace/jaeger/agent.go:167]: This and the other place `err` is assigned to have the possibility to hide errors by setting the value back to `nil`.

We should return all errors encountered to provide the user with more information of the failure so things do not have to be serially debugged. We should likely store all the errors in slice and handle that slice appropriately when we return.

**Review by MrAlias — CHANGES_REQUESTED** [review]

File: exporters/trace/jaeger/agent.go [hunk 3]
```diff
@@ -124,6 +132,46 @@ func (a *agentClientUDP) EmitBatch(ctx context.Context, batch *gen.Batch) error
 	return err
 }
 
+// calcSizeOfSerializedThrift calculate the serialized thrift packet size
+func (a *agentClientUDP) calcSizeOfSerializedThrift(ctx context.Context, thriftStruct thrift.TStruct) int {
+	a.thriftBuffer.Reset()
+	_ = thriftStruct.Write(ctx, a.thriftProtocol)
```
[the remark this answers is not in the document]
Comment (tianyaqu) [reply exporters/trace/jaeger/agent.go:138]: > Does the client also ignore this error or does it abandon the batch? We should not try sending a thriftStruct we know will not serialize and should probably batch intelligently by not including it.

I'll add an error as return value and drop the span which gets the err. And also add a complaining message

File: exporters/trace/jaeger/agent.go (hunk 2 above)
Comment (tianyaqu) [reply exporters/trace/jaeger/agent.go:167]: > This and the other place `err` is assigned to have the possibility to hide errors by setting the value back to `nil`.
> 
> We should return all errors encountered to provide the user with more information of the failure so things do not have to be serially debugged. We should likely store all the errors in slice and handle that slice appropriately when we return.

It's ok to return a slice of errors, but the `EmitBatch` only one return vale of error. Returning a new error like "partial failure"?

Comment (MrAlias) [reply exporters/trace/jaeger/agent.go:167]: > It's ok to return a slice of errors, but the `EmitBatch` only one return vale of error. Returning a new error like "partial failure"?

Yeah, I would keep track of all errors seen in a slice and if there are more than one try and combine them into a "multiple errors during transform" sort of error.

Comment (tianyaqu) [reply exporters/trace/jaeger/agent.go]: @MrAlias I've made some changes to handle your suggestions. Please have a look again

File: exporters/trace/jaeger/agent.go [hunk 4]
```diff
@@ -103,15 +105,66 @@ func newAgentClientUDP(params agentClientUDPParams) (*agentClientUDP, error) {
...
+		thriftProtocol: thriftProtocol,
 	}, nil
 }
 
 // EmitBatch implements EmitBatch() of Agent interface
 func (a *agentClientUDP) EmitBatch(ctx context.Context, batch *gen.Batch) error {
+	var errs []error
+	processSize, err := a.calcSizeOfSerializedThrift(ctx, batch.Process)
+	if err != nil {
+		// drop the bath if serialization of process fails.
```
Comment (MrAlias) [inline exporters/trace/jaeger/agent.go:121]:
```suggestion
		// drop the batch if serialization of process fails.
```

File: exporters/trace/jaeger/agent.go [hunk 5]
```diff
@@ -103,15 +105,66 @@ func newAgentClientUDP(params agentClientUDPParams) (*agentClientUDP, error) {
...
-		thriftBuffer:  thriftBuffer,
+		connUDP:        connUDP,
+		client:         client,
+		maxPacketSize:  params.MaxPacketSize,
+		thriftBuffer:   thriftBuffer,
+		thriftProtocol: thriftProtocol,
 	}, nil
 }
 
 // EmitBatch implements EmitBatch() of Agent interface
```
Comment (MrAlias) [inline exporters/trace/jaeger/agent.go:116]: Not related, but this would be a helpful inclusion.

```suggestion
// EmitBatch buffers batch to fit into UDP packets and sends the data to the agent.
```

File: exporters/trace/jaeger/agent.go [hunk 6]
```diff
@@ -103,15 +105,66 @@ func newAgentClientUDP(params agentClientUDPParams) (*agentClientUDP, error) {
...
+		if err := a.flush(ctx, &gen.Batch{
+			Process: batch.Process,
+			Spans:   spans,
+		}); err != nil {
+			errs = append(errs, err)
+		}
+	}
+
+	if len(errs) > 0 {
+		return fmt.Errorf("multiple errors during transform")
```
Comment (MrAlias) [inline exporters/trace/jaeger/agent.go:161]:
```suggestion
	if len(errs) == 1 {
		return errs[0]
	} else if len(errs) > 1 {
		joined := strings.Join(errs, ", ")
		return fmt.Errorf("multiple errors during transform: %s", joined)
```

File: exporters/trace/jaeger/agent_test.go [hunk 7]
```diff
@@ -99,3 +102,26 @@ func TestNewAgentClientUDPWithParamsReconnectingDisabled(t *testing.T) {
...
+	n := 1500
+	s := make([]*tracesdk.SpanSnapshot, n)
+	for i := 0; i < n; i++ {
+		s[i] = &tracesdk.SpanSnapshot{}
+	}
+
+	exp, err := NewRawExporter(
+		WithAgentEndpoint(WithAgentHost("localhost"), WithAgentPort("6831")),
+	)
+	assert.NoError(t, err)
```
Comment (MrAlias) [inline exporters/trace/jaeger/agent_test.go:122]:
```suggestion
	require.NoError(t, err)
```

File: exporters/trace/jaeger/agent_test.go [hunk 8]
```diff
@@ -99,3 +102,26 @@ func TestNewAgentClientUDPWithParamsReconnectingDisabled(t *testing.T) {
...
 }
+
+type errorHandler struct{ t *testing.T }
+
+func (eh errorHandler) Handle(err error) { assert.NoError(eh.t, err) }
+
+func TestJaegerAgentUDPLimitBatching(t *testing.T) {
+	otel.SetErrorHandler(errorHandler{t})
+
+	n := 1500
```
Comment (MrAlias) [inline exporters/trace/jaeger/agent_test.go:113]:
```suggestion
	// 1500 spans, size 79559, does not fit within one UDP packet with the default size of 65000.
	n := 1500
```

File: exporters/trace/jaeger/agent.go [hunk 9]
```diff
@@ -103,15 +105,66 @@ func newAgentClientUDP(params agentClientUDPParams) (*agentClientUDP, error) {
...
+	var spans []*gen.Span
+	for _, span := range batch.Spans {
+		spanSize, err := a.calcSizeOfSerializedThrift(ctx, span)
+		if err != nil {
+			errs = append(errs, fmt.Errorf("thrift serialization failed: %v", span))
+			continue
+		}
+		if spanSize+processSize >= a.maxPacketSize {
+			// drop the span that exceeds the limit.
+			errs = append(errs, fmt.Errorf("span too large to send: %v", span))
```
Comment (MrAlias) [inline exporters/trace/jaeger/agent.go:134]: Can we add tests for this? I'm guessing we can check things by carefully tuning the maxPacketSize to generate this error.

**Comment by MrAlias** [comment]
An entry in the changelog will be needed to communicate this fix.

File: exporters/trace/jaeger/agent.go (hunk 9 above)
Comment (tianyaqu) [reply exporters/trace/jaeger/agent.go:134]: > Can we add tests for this? I'm guessing we can check things by carefully tuning the maxPacketSize to generate this error.

OK,I'll add tests for that

**Comment by tianyaqu** [comment]
> An entry in the changelog will be needed to communicate this fix.

Yeah,I've made changes in the  fix and add section of the changlog, pls have a look on that.

File: CHANGELOG.md [hunk 10]
```diff
@@ -88,6 +88,7 @@ This project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.htm
   - `OTEL_EXPORTER_OTLP_TRACES_CERTIFICATE`
   - `OTEL_EXPORTER_OTLP_METRICS_CERTIFICATE`
 - Adds `otlpgrpc.WithTimeout` option for configuring timeout to the otlp/gRPC exporter. (#1821)
+- Adds `jaeger.WithMaxPacketSize` option for configuring maximum packet size of jaeger udp agent.
```
Comment (MrAlias) [inline CHANGELOG.md:91]:
```suggestion
- Adds `jaeger.WithMaxPacketSize` option for configuring maximum UDP packet size used when connecting to the Jaeger agent. (#1853)
```

File: CHANGELOG.md [hunk 11]
```diff
@@ -99,6 +100,7 @@ This project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.htm
 - Zipkin Exporter: Ensure mapping between OTel and Zipkin span data complies with the specification. (#1688)
 - Fixed typo for default service name in Jaeger Exporter. (#1797)
 - Fix flaky OTLP for the reconnnection of the client connection. (#1527, #1814)
+- Fix Jaeger exporter drops batches of spans exceeding the UDP packet size limit. (#1828)
```
Comment (MrAlias) [inline CHANGELOG.md:103]:
```suggestion
- Fix Jaeger exporter dropping of span batches that exceed the UDP packet size limit.
  Instead, the exporter now splits the batch into smaller sendable batches. (#1828)
```

File: exporters/trace/jaeger/uploader.go [hunk 12]
```diff
@@ -114,6 +114,13 @@ func WithAttemptReconnectingInterval(interval time.Duration) AgentEndpointOption
 	}
 }
 
+// WithMaxPacketSize sets the maximum size of udp packet.
```
Comment (MrAlias) [inline exporters/trace/jaeger/uploader.go:117]:
```suggestion
// WithMaxPacketSize sets the maximum UDP packet size for transport to the Jaeger agent.
```

Comment (tianyaqu) [reply exporters/trace/jaeger/uploader.go]: I've made a new commit to fix that.

File: exporters/trace/jaeger/agent_test.go (hunk 8 above)
Comment (MrAlias) [reply exporters/trace/jaeger/agent_test.go:115]: @tianyaqu this looks like it has not been addressed yet.

**Review by MrAlias — APPROVED** [review]
Awesome work! Thanks for the contribution.

File: exporters/trace/jaeger/agent_test.go [hunk 13]
```diff
@@ -99,3 +103,49 @@ func TestNewAgentClientUDPWithParamsReconnectingDisabled(t *testing.T) {
...
+
+func TestSpanExceedsMaxPacketLimit(t *testing.T) {
+	otel.SetErrorHandler(errorHandler{t})
+
+	// 106 is the serialized size of a span with default values.
+	maxSize := 106
+	span := &tracesdk.SpanSnapshot{
+		Name: "a-longer-name-that-makes-it-exceeds-limit",
+	}
+	largeSpans := []*tracesdk.SpanSnapshot{span, span, {}}
```
Comment (MrAlias) [inline exporters/trace/jaeger/agent_test.go:139]: Is this triggering the failure because there are two spans or because the span is too big?

Can this be changed back to one large span make it clear what this test is testing?

Comment (tianyaqu) [reply exporters/trace/jaeger/agent_test.go:140]: > Is this triggering the failure because there are two spans or because the span is too big?
> 
> Can this be changed back to one large span make it clear what this test is testing?

This line doesn't cause the test failure, i change this line to increase test coverage; Also i add a single large span test case that will explain what this test is testing.
The compatibility-test for windows actually causes the test failure, the span serialization bytes on windows is 4 bytes larger than linux/mac, it will make the normal span(empty ones) produces an error when exported, i change the maxSize to elimate the error.

Comment (MrAlias) [reply exporters/trace/jaeger/agent_test.go:140]: I'm aware this line does not produce the test failure, but it is [a change that was included](https://github.com/open-telemetry/opentelemetry-go/pull/1853/commits/ce591ba699a32afa39ebd07da55de918e4ec4f94) in the problem you are describing that is not related to the failure you mention:

```diff
-	largeSpans := []*tracesdk.SpanSnapshot{span, {}}
+	oneLargeSpan := []*tracesdk.SpanSnapshot{span}
+	largeSpans := []*tracesdk.SpanSnapshot{span, span, {}}
```

Having `largeSpans` now include 2 `span` makes it less clear what we are testing. Are we testing if two large spans should overload the UDP packet size when included with an empty span, or one?

```suggestion
	largeSpans := []*tracesdk.SpanSnapshot{span, {}}
```

Comment (tianyaqu) [reply exporters/trace/jaeger/agent_test.go:140]: > I'm aware this line does not produce the test failure, but it is [a change that was included in the fix commited](https://github.com/open-telemetry/opentelemetry-go/pull/1853/commits/ce591ba699a32afa39ebd07da55de918e4ec4f94) to addrss the problem you are describing that is does not seem related to the failure:
> 
> ```diff
> -	largeSpans := []*tracesdk.SpanSnapshot{span, {}}
> +	oneLargeSpan := []*tracesdk.SpanSnapshot{span}
> +	largeSpans := []*tracesdk.SpanSnapshot{span, span, {}}
> ```
> 
> Having `largeSpans` now include 2 `span` makes it less clear what we are testing. Are we testing if two large spans should overload the UDP packet size when included with an empty span, or one?

The reason why i put two large `span` in the `largeSpans` slice is very simple: to produce mutiple errors, and it will cover the joined error string logic. `oneLargeSpan` and `largeSpans` are two different cases,representing one single error and mutiple errors when processing a batch.

Comment (MrAlias) [reply exporters/trace/jaeger/agent_test.go:140]: The issue I'm talking about is that this test is testing multiple things. Please split the different errors cases you are testing into easily recognized test cases. This could mean splitting into multiple tests, refactoring into generalized testing conditions, or, at the very least, document what is being tested.

Comment (tianyaqu) [reply exporters/trace/jaeger/agent_test.go:140]: OK, I'll put them in different test cases

**Review by MrAlias — APPROVED** [review]

**Review by Aneurysm9 — APPROVED** [review]
