### PR TITLE
Do not block Temporality/Aggregation on OTLP metric export

### LINKED ISSUE #3925: Metric creation slowed down by unreachable collector with gRPC
### Description

I noticed that the creation of instruments while the agent/collector is down can easily take more than 10 seconds each.
I'm testing this by passing an invalid host (e.g. `unreachable:4317`) to my application and I see these calls taking more than 10 seconds each:

```go
switch any(m).(type) {
case map[string]instrument.Int64Counter:
	value, err = meter.Int64Counter(name, castOptions[instrument.Int64Option](opts...)...)
case map[string]instrument.Int64Histogram:
	value, err = meter.Int64Histogram(name, castOptions[instrument.Int64Option](opts...)...)
case map[string]instrument.Float64Histogram:
	value, err = meter.Float64Histogram(name, castOptions[instrument.Float64Option](opts...)...)
default:
	panic(fmt.Errorf("unknown instrument type %T", instr))
}
```

That is a small `switch` that I have in my own instruments factory that works as an adapter to your library.

image

To me it looks like these operations all hold a mutex (i.e. `e.clientMu`):

image

I think `Aggregation` and `Temporality` are called when an instrument is created but the same mutex is kept locked for the entire duration of `Export` as well, so maybe that is where the problem lies. I would expect `Export` to hold a lock just to create a copy of the data that it needs to send, then unlock then asynchronously take its time to send the data over the gRPC connection. Buffered channels can be used to and metrics can be discarded once the buffer is full.

### Environment

- OS: Kubernetes
- Architecture: [x86]
- Go Version: [1.20]
- opentelemetry-go version: [[v1.14.0/v0.37.0/v0.0.4](https://github.com/open-telemetry/opentelemetry-go/releases/tag/v1.14.0)]

### Steps To Reproduce

You don't even need a collector. Just create many go routines spawning instruments (also the same instrument over and over since it should be cached in memory) and pass something like `"unreachable:4317"` as the gRPC endpoint.

This is my default retry config:

```go
var DefaultRetryConfig = RetryConfig{
	Enabled:         true,
	InitialInterval: 5 * time.Second,
	MaxInterval:     30 * time.Second,
	MaxElapsedTime:  time.Minute,
}
```

And this is how I initialize the meter provider:

```go
meterProviderOptions := []otlpmetricgrpc.Option{
	otlpmetricgrpc.WithEndpoint(c.metricsEndpoint),
	otlpmetricgrpc.WithRetry(otlpmetricgrpc.RetryConfig{
		Enabled:         c.retryConfig.Enabled,
		InitialInterval: c.retryConfig.InitialInterval,
		MaxInterval:     c.retryConfig.MaxInterval,
		MaxElapsedTime:  c.retryConfig.MaxElapsedTime,
	}),
}
if c.withInsecure {
	meterProviderOptions = append(meterProviderOptions, otlpmetricgrpc.WithInsecure())
}
if len(c.meterProviderConfig.otlpMetricGRPCOptions) > 0 {
	meterProviderOptions = append(meterProviderOptions, c.meterProviderConfig.otlpMetricGRPCOptions...)
}
exp, err := otlpmetricgrpc.New(ctx, meterProviderOptions...)
if err != nil {
	return nil, nil, fmt.Errorf("failed to create metric exporter: %w", err)
}

m.mp = sdkmetric.NewMeterProvider(
	sdkmetric.WithResource(res),
	sdkmetric.WithReader(sdkmetric.NewPeriodicReader(
		exp,
		sdkmetric.WithInterval(c.meterProviderConfig.exportsInterval),
	)),
	sdkmetric.WithView(c.meterProviderConfig.views...),
)

if c.meterProviderConfig.global {
	global.SetMeterProvider(m.mp)
}
```

### Expected behavior

I would expect the creation of instruments not to take more than a few milliseconds at most.

### PR DESCRIPTION
**Pull request by MrAlias**
Resolve #3925 

Closes https://github.com/open-telemetry/opentelemetry-go/pull/4001

Currently for both the HTTP and gRPC OTLP metric exporters when `Export` is called all calls to `Aggregation` and `Temporality` are blocked. This means the whole SDK processing pipeline, which calls these methods, becomes blocked. This is especially bad when `Export` hangs indefinitely due to an inaccessible target.

Instead of having a universal `client` lock for a shared `Exporter` from the `otlpmetric/internal` package, have each exporter package implement a non-blocking `Exporter` directly. This removes the dependency on shared internal packages from an external module[^1].

This does not completely remove the dependency on shared internal packages from an external module. That is left for a separate PR.

[^1]: https://github.com/open-telemetry/opentelemetry-go/issues/3846

### CODE REVIEW

**Comment by MrAlias** [comment]
If merged, supersedes https://github.com/open-telemetry/opentelemetry-go/pull/4001

**Review by dashpole — APPROVED** [review]

File: exporters/otlp/otlpmetric/internal/exporter.go [hunk 1]
```diff
@@ -27,6 +27,11 @@ import (
 )
 
 // Exporter exports metrics data as OTLP.
+//
+// Deprecated: Exporter exists for historical compatibility, it should not be
+// used. Do not removed Exporter unless the whole
```
Comment (CharlieTLe) [inline exporters/otlp/otlpmetric/internal/exporter.go:32]: typo: removed --> remove

File: exporters/otlp/otlpmetric/internal/exporter.go [hunk 2]
```diff
@@ -96,6 +101,11 @@ func (e *Exporter) Shutdown(ctx context.Context) error {
 // New return an Exporter that uses client to transmits the OTLP data it
 // produces. The client is assumed to be fully started and able to communicate
 // with its OTLP receiving endpoint.
+//
+// Deprecated: New exists for historical compatibility, it should not be used.
+// Do not removed New unless the whole
```
Comment (CharlieTLe) [inline exporters/otlp/otlpmetric/internal/exporter.go:106]: typo: removed --> remove

Comment (MrAlias) [reply exporters/otlp/otlpmetric/internal/exporter.go:106]:
```suggestion
// Do not remove New unless the whole
```

File: exporters/otlp/otlpmetric/otlpmetrichttp/exporter_test.go [hunk 3]
```diff
@@ -0,0 +1,124 @@
...
+				default:
+				}
+			}
+		}()
+	}
+
+	for i := 0; i < goroutines; i++ {
+		<-first
+	}
+	close(first)
```
Comment (pellared) [inline exporters/otlp/otlpmetric/otlpmetrichttp/exporter_test.go:77]: Why we are closing the channel?

1. This is not needed
2. The producer should close the channel (not the consumer).

File: exporters/otlp/otlpmetric/otlpmetrichttp/exporter_test.go [hunk 4]
```diff
@@ -0,0 +1,124 @@
...
+	cfg := oconf.NewHTTPConfig(asHTTPOptions(opts)...)
+	client, err := newClient(cfg)
+	require.NoError(t, err)
+
+	exp, err := newExporter(client, oconf.Config{})
+	require.NoError(t, err)
+	rm := new(metricdata.ResourceMetrics)
+
+	done := make(chan struct{})
+	first := make(chan struct{}, goroutines)
```
Comment (pellared) [inline exporters/otlp/otlpmetric/otlpmetrichttp/exporter_test.go:50]: I think it would easier and more consistent to create another `sync.WaitGroup`.

**Review by pellared — COMMENTED** [review]
👍

File: exporters/otlp/otlpmetric/otlpmetrichttp/exporter_test.go (hunk 4 above)
Comment (MrAlias) [reply exporters/otlp/otlpmetric/otlpmetrichttp/exporter_test.go:50]: This test it copied from `otlpmetric/internal`. I don't plan to change it in this PR to avoid confusion. Please feel free to address it in a follow up PR if you feel it needs to be changed.

File: exporters/otlp/otlpmetric/otlpmetrichttp/exporter_test.go (hunk 3 above)
Comment (MrAlias) [reply exporters/otlp/otlpmetric/otlpmetrichttp/exporter_test.go:77]: Similar to my response to your other comment, I had just copied this test. Please feel free to change this (and the `otlpmetricgrpc` test) in a follow up PR.

Comment (pellared) [reply exporters/otlp/otlpmetric/otlpmetrichttp/exporter_test.go:77]: https://github.com/open-telemetry/opentelemetry-go/issues/4399

File: exporters/otlp/otlpmetric/otlpmetrichttp/exporter_test.go (hunk 4 above)
Comment (pellared) [reply exporters/otlp/otlpmetric/otlpmetrichttp/exporter_test.go:50]: https://github.com/open-telemetry/opentelemetry-go/issues/4399

**Review by pellared — APPROVED** [review]
