### PR TITLE
drop failed to exporter batches and return error when forcing flush a span processor

### LINKED ISSUE #1833: Batch processor batch size will grow endlessly on error
### Description

Hey, came across this bug as I was sending invalid utf-8 strings through the gRPC driver. The invalid spans would cause the batch [to roll-over](https://github.com/open-telemetry/opentelemetry-go/blob/sdk/v0.19.0/sdk/trace/batch_span_processor.go#L187) and be retried. If the batch size is already at/over max then the batch size check [fails permanently](https://github.com/open-telemetry/opentelemetry-go/blob/sdk/v0.19.0/sdk/trace/batch_span_processor.go#L213) and the batch will only be sent again after the timeout. As the batch grows it risks hitting gRPC message size limits imposed by the server.

How this looks with some debug logging wrapped around the driver:

```
2021/04/22 15:27:59 ERROR SENDING BATCH (size: 512): rpc error: code = Internal desc = grpc: error unmarshalling request: string field contains invalid UTF-8
2021/04/22 15:28:04 ERROR SENDING BATCH (size: 5342): rpc error: code = ResourceExhausted desc = grpc: received message larger than max (5389485 vs. 5000000)
2021/04/22 15:28:08 ERROR SENDING BATCH (size: 8177): exporter disconnected: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (5389485 vs. 5000000)
2021/04/22 15:28:13 ERROR SENDING BATCH (size: 8177): exporter disconnected: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (5389485 vs. 5000000)
2021/04/22 15:28:19 ERROR SENDING BATCH (size: 8177): rpc error: code = ResourceExhausted desc = grpc: received message larger than max (8174169 vs. 5000000)
```

### Environment

- OS: Alpine
- Architecture: i386
- Go Version: 1.16.2
- opentelemetry-go version: 0.19.0

### Steps To Reproduce

I don't have a repro setup outside my work project. It should be possible to reproduce using unit tests on the batch span processor though.

### Expected behavior

Either for the failed batch to be dropped, or some more intelligent retry with eventual discard

### PR DESCRIPTION
**Pull request by paivagustavo**
This resolves a problem in the batch span processor and a nice-to-have error report on the `ForceFlush()` method.

Failed span batches are now dropped as expected. Quoting specs:
> Failure - exporting failed. The batch must be dropped. For example, this can happen when the batch contains bad data and cannot be serialized.

`BatchSpanProcessor.ForceFlush()` method now correctly report export errors. Quoting specs:
> ForceFlush SHOULD provide a way to let the caller know whether it succeeded, failed or timed out.

Fixes #1833

### CODE REVIEW

**Review by Aneurysm9 — APPROVED** [review]
It shouldn't matter with the batch being reset regardless of errors, but there's a line in `processQueue()` that should be updated.  It's currently:

```go
shouldExport := len(bsp.batch) == bsp.o.MaxExportBatchSize
```

and should probably be:

```go
shouldExport := len(bsp.batch) >= bsp.o.MaxExportBatchSize
```

File: sdk/trace/batch_span_processor.go [hunk 1]
```diff
@@ -156,16 +156,16 @@ func (bsp *batchSpanProcessor) Shutdown(ctx context.Context) error {
...
 	var err error
 	if bsp.e != nil {
-		wait := make(chan struct{})
+		wait := make(chan error)
 		go func() {
 			if err := bsp.exportSpans(ctx); err != nil {
-				otel.Handle(err)
+				wait <- err
 			}
 			close(wait)
```
Comment (MrAlias) [inline sdk/trace/batch_span_processor.go:164]: Nit, but this could all be replaced with

```
wait <- bsp.exportSpans(ctx)
```

File: sdk/trace/batch_span_processor_test.go [hunk 2]
```diff
@@ -353,6 +359,65 @@ func TestBatchSpanProcessorForceFlushSucceeds(t *testing.T) {
...
+	assertMaxSpanDiff(t, te.len(), option.wantNumSpans, 10)
+	gotBatchCount := te.getBatchCount()
+	if gotBatchCount < option.wantBatchCount {
+		t.Errorf("number batches: got %+v, want >= %+v\n",
+			gotBatchCount, option.wantBatchCount)
+		t.Errorf("Batches %v\n", te.sizes)
+	}
+}
+
+func assertMaxSpanDiff(t *testing.T, want int, got int, maxDif int) {
```
Comment (MrAlias) [inline sdk/trace/batch_span_processor_test.go:410]: nit

```suggestion
func assertMaxSpanDiff(t *testing.T, want, got, maxDif int) {
```

File: sdk/trace/batch_span_processor_test.go [hunk 3]
```diff
@@ -353,6 +359,65 @@ func TestBatchSpanProcessorForceFlushSucceeds(t *testing.T) {
...
+	spanDifference := want - got
+	if spanDifference < 0 {
+		spanDifference = spanDifference * -1
+	}
+	if spanDifference > maxDif || spanDifference < 0 {
```
Comment (MrAlias) [inline sdk/trace/batch_span_processor_test.go:415]: is it possible for `spanDifference` to be less than zero given the above conditional multiplication?

**Review by MrAlias — APPROVED** [review]

File: sdk/trace/batch_span_processor_test.go (hunk 3 above)
Comment (paivagustavo) [reply sdk/trace/batch_span_processor_test.go]: Nope, that was supposed to be removed when I added the first `< 0` condition.
