### PR TITLE
Replaces golint by revive and fix newly reported linter issues

### LINKED ISSUE #1935: The linter 'golint' is deprecated
### Description

The following warning is reported when building locally.

```
WARN [runner] The linter 'golint' is deprecated (since v1.41.0) due to: The repository of the linter has been archived by the owner.  Replaced by revive
```

### Environment

```sh
$ uname -s -r -v -m -o      
Linux 5.12.3-arch1-1 #1 SMP PREEMPT Wed, 12 May 2021 17:54:18 +0000 x86_64 GNU/Linux
```

```sh
$ go version
go version go1.16.4 linux/amd64
```

- OS: Linux
- Architecture: x86_64
- Go Version: 16
- opentelemetry-go version: v0.20.0

### Steps To Reproduce

```sh
$ make lint
# ...
golangci-lint in .
WARN [runner] The linter 'golint' is deprecated (since v1.41.0) due to: The repository of the linter has been archived by the owner.  Replaced by revive. 
```

### Expected behavior

No warning to be printed.

### PR DESCRIPTION
**Pull request by AndersonQ**
As [`golint` is deprecated](https://github.com/golang/go/issues/38968) this PR replaces `golint` by [`revive`](https://github.com/mgechev/revive#revive), a drop-in replacement for `golint` and also the one suggested by [`golangci-lint `](https://github.com/golangci/golangci-lint).
It's a followup on #1941, closes #1941 and fixes #1935

Even though `revive` is a drop-in replacement for `golint` a few new lint issues rose after the change. I believe it's due to how `revive` walks the folder structure, as `golint` also reports these errors is I run it directly in the files with newly reported issues.

I took a mixed approach of fixing the issues and disabling the revive to fix all the new issues. I tries to use my best judgment and guess to decide when to fix or ignore the error. I decided not to skip the files or folder as I did not find a common pattern for all the files with new lint errors.

### CODE REVIEW

File: internal/matchers/temporal_matcher.go [hunk 1]
```diff
@@ -16,6 +16,7 @@ package matchers
 
 type TemporalMatcher byte
 
+//nolint:revive
```
Comment (pellared) [inline internal/matchers/temporal_matcher.go:19]: I would like to know what was ignored and why
```suggestion
//nolint:revive // ignoring missing comments for unexported constants in an internal package
```

File: metric/unit/unit.go [hunk 2]
```diff
@@ -16,6 +16,7 @@ package unit // import "go.opentelemetry.io/otel/metric/unit"
 
 type Unit string
 
+//nolint:revive
```
Comment (pellared) [inline metric/unit/unit.go:19]: I would like to know what was ignored and why
```suggestion
//nolint:revive // ignoring missing comments for obvious constants
```

File: sdk/export/metric/aggregation/aggregation.go [hunk 3]
```diff
@@ -128,6 +128,7 @@ type (
 	Kind string
 )
 
+//nolint:revive
```
Comment (pellared) [inline sdk/export/metric/aggregation/aggregation.go:131]: Maybe here it would be good to not ignore these errors and put some comments.

File: sdk/export/metric/aggregation/aggregation.go [hunk 4]
```diff
@@ -136,6 +137,7 @@ const (
 	ExactKind          Kind = "Exact"
 )
 
+//nolint:revive
```
Comment (pellared) [inline sdk/export/metric/aggregation/aggregation.go:140]: Maybe here it would be good to not ignore these errors and put some comments.

File: sdk/metric/processor/basic/basic.go [hunk 5]
```diff
@@ -119,8 +119,8 @@ type (
 var _ export.Processor = &Processor{}
 var _ export.Checkpointer = &Processor{}
 var _ export.CheckpointSet = &state{}
-var ErrInconsistentState = fmt.Errorf("inconsistent processor state")
-var ErrInvalidExportKind = fmt.Errorf("invalid export kind")
+var ErrInconsistentState = fmt.Errorf("inconsistent processor state") //nolint:revive
+var ErrInvalidExportKind = fmt.Errorf("invalid export kind")          //nolint:revive
```
Comment (pellared) [inline sdk/metric/processor/basic/basic.go:123]: Maybe here it would be good to not ignore these errors and put some comments.

File: sdk/metric/sdk.go [hunk 6]
```diff
@@ -147,7 +147,7 @@ var (
 	_ metric.SyncImpl      = &syncInstrument{}
 	_ metric.BoundSyncImpl = &record{}
 
-	ErrUninitializedInstrument = fmt.Errorf("use of an uninitialized instrument")
+	ErrUninitializedInstrument = fmt.Errorf("use of an uninitialized instrument") //nolint:revive
```
Comment (pellared) [inline sdk/metric/sdk.go:150]: Maybe here it would be good to not ignore these errors and put some comments.

File: trace/trace.go [hunk 7]
```diff
@@ -59,7 +59,7 @@ func (e errorConst) Error() string {
 }
 
 // TraceID is a unique identity of a trace.
-// nolint:golint
+// nolint:revive
```
Comment (pellared) [inline trace/trace.go:62]: what is was complaining about? maybe worth describing

File: trace/trace.go [hunk 8]
```diff
@@ -108,7 +108,7 @@ func (s SpanID) String() string {
 // TraceIDFromHex returns a TraceID from a hex string if it is compliant with
 // the W3C trace-context specification.  See more at
 // https://www.w3.org/TR/trace-context/#trace-id
-// nolint:golint
+// nolint:revive
```
Comment (pellared) [inline trace/trace.go:111]: what is was complaining about? maybe worth describing

File: trace/trace.go [hunk 9]
```diff
@@ -175,7 +175,7 @@ func decodeHex(h string, b []byte) error {
 //
 // Trace state must be valid according to the W3C Trace Context specification at all times. All
 // mutating operations validate their input and, in case of valid parameters, return a new TraceState.
-type TraceState struct { //nolint:golint
+type TraceState struct { //nolint:revive
```
Comment (pellared) [inline trace/trace.go:178]: what is was complaining about? maybe worth describing

File: trace/trace.go [hunk 10]
```diff
@@ -277,7 +277,7 @@ func (ts TraceState) copyKVsAndDeleteEntry(key attribute.Key) []attribute.KeyVal
 
 // TraceStateFromKeyValues is a convenience method to create a new TraceState from
 // provided key/value pairs.
-func TraceStateFromKeyValues(kvs ...attribute.KeyValue) (TraceState, error) { //nolint:golint
+func TraceStateFromKeyValues(kvs ...attribute.KeyValue) (TraceState, error) { //nolint:revive
```
Comment (pellared) [inline trace/trace.go:280]: what is was complaining about? maybe worth describing

File: trace/trace.go [hunk 11]
```diff
@@ -313,7 +313,7 @@ func isTraceStateKeyValueValid(kv attribute.KeyValue) bool {
 }
 
 // TraceFlags contains flags that can be set on a SpanContext
-type TraceFlags byte //nolint:golint
+type TraceFlags byte //nolint:revive
```
Comment (pellared) [inline trace/trace.go:316]: what is was complaining about? maybe worth describing

File: exporters/otlp/internal/otlpconfig/tls.go [hunk 12]
```diff
@@ -21,6 +21,7 @@ import (
 	"io/ioutil"
 )
 
+//nolint:revive
```
Comment (pellared) [inline exporters/otlp/internal/otlpconfig/tls.go:24]: I would like to know what was ignored and why
```suggestion
//nolint:revive // ignoring missing comments for unexported constants in an internal package
```

File: bridge/opentracing/internal/mock.go [hunk 13]
```diff
@@ -30,6 +30,7 @@ import (
 	"go.opentelemetry.io/otel/bridge/opentracing/migration"
 )
 
+//nolint:revive
```
Comment (pellared) [inline bridge/opentracing/internal/mock.go:33]: I would like to know what was ignored and why
```suggestion
//nolint:revive // ignoring missing comments for unexported global variables in an internal package
```

File: CHANGELOG.md [hunk 14]
```diff
@@ -8,6 +8,9 @@ This project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.htm
 
 ## [Unreleased]
 
+- Replaces [_golint_](https://github.com/golang/lint) with [_revive_](https://github.com/mgechev/revive)
```
Comment (pellared) [inline CHANGELOG.md:11]: Personally, I think it is not worth putting it in the changelog. It is purely internal.

File: semconv/http.go [hunk 15]
```diff
@@ -26,8 +26,8 @@ import (
 )
 
 var (
-	HTTPSchemeHTTP  = HTTPSchemeKey.String("http")
-	HTTPSchemeHTTPS = HTTPSchemeKey.String("https")
+	httpSchemeHTTP  = HTTPSchemeKey.String("http")
+	httpSchemeHTTPS = HTTPSchemeKey.String("https")
```
Comment (pellared) [inline semconv/http.go:30]: This is a breaking change.
I guess these might have been intentionally exported.

File: sdk/metric/controller/basic/controller.go [hunk 16]
```diff
@@ -196,12 +196,10 @@ func (c *Controller) collect(ctx context.Context) error {
 	if c.exporter == nil {
 		return nil
 	}
+
 	// Note: this is not subject to collectTimeout.  This blocks the next
 	// collection despite collectTimeout because it holds a lock.
-	if err := c.export(ctx); err != nil {
-		return err
-	}
-	return nil
```
Comment (AndersonQ) [inline sdk/metric/controller/basic/controller.go:204]: I'm not sure if this structure was intentional, however as the linter complained and the change does not affect the behaviour I applied it.

**Review by dashpole — COMMENTED** [review]
Should we open an issue to track fixing the "missing comments" `nolint` comments if we aren't going to fix them here?

File: example/passthrough/go.sum [hunk 17]
```diff
@@ -9,9 +9,7 @@ github.com/pmezard/go-difflib v1.0.0/go.mod h1:iKH77koFhYxTK1pcRnkKkqfTogsbg7gZN
 github.com/stretchr/objx v0.1.0/go.mod h1:HFkY916IF+rwdDfMAkV7OtwuqBVzrE8GR6GFx+wExME=
 github.com/stretchr/testify v1.7.0 h1:nwc3DEeHmmLAfoZucVR881uASk0Mfjw8xYJ99tb5CcY=
 github.com/stretchr/testify v1.7.0/go.mod h1:6Fq8oRcR53rry900zMqJjRRixrwX3KX962/h/Wwjteg=
-golang.org/x/xerrors v0.0.0-20191204190536-9bdfabe68543 h1:E7g+9GITq07hpfrRu66IVDexMakfv52eLZ2CXBWiKr4=
 golang.org/x/xerrors v0.0.0-20191204190536-9bdfabe68543/go.mod h1:I/5z698sn9Ka8TeJc9MKroUUfqBBauWjQqLJ2OPfmY0=
-gopkg.in/check.v1 v0.0.0-20161208181325-20d25e280405 h1:yhCVgyC4o1eVCa2tZl7eS0r+SDo693bJlVdllGtEeKM=
```
Comment (MrAlias) [inline example/passthrough/go.sum:14]: These changes need to be reverted. See https://github.com/open-telemetry/opentelemetry-go/pull/1936#issuecomment-845527022

File: semconv/http.go [hunk 18]
```diff
@@ -25,6 +25,7 @@ import (
 	"go.opentelemetry.io/otel/codes"
 )
 
+// HTTP scheme key-value pairs.
```
Comment (MrAlias) [inline semconv/http.go:28]:
```suggestion
// HTTP scheme attributes.
```

File: metric/unit/unit.go [hunk 19]
```diff
@@ -16,6 +16,7 @@ package unit // import "go.opentelemetry.io/otel/metric/unit"
 
 type Unit string
 
+//nolint:revive // ignoring missing comments for obvious constants.
```
Comment (MrAlias) [inline metric/unit/unit.go:19]:
```suggestion
// Units defined by OpenTelemetry.
```

**Comment by MrAlias** [comment]
> Should we open an issue to track fixing the "missing comments" `nolint` comments if we aren't going to fix them here?

I'm in favor of just resolving these here by adding descriptive comments.

File: propagation/propagation_test.go [hunk 20]
```diff
@@ -25,7 +25,7 @@ import (
 type ctxKeyType uint
 
 var (
-	ctxKey ctxKeyType = 0
+	ctxKey ctxKeyType
```
Comment (Aneurysm9) [inline propagation/propagation_test.go:28]:
```suggestion
	ctxKey ctxKeyType = iota
```

Would it complain about this?  I'm not sure I like just leaving a bare variable declaration there even if I know it'll receive `0`.  I still have to spend some time thinking about it and why it's okay every time I look at the variable.

**Review by Aneurysm9 — APPROVED** [review]

File: propagation/propagation_test.go (hunk 20 above)
Comment (AndersonQ) [reply propagation/propagation_test.go:28]: The linter complains because `0` is already the zero value, thus initialising it with `0` is redundant. On the other hand. to use `iota` would change the meaning here. Even thought `ctxKey ` would have the value `0`, as it's the fist value used by `iota`, it'd indicate that more variables should be expected and for a context key, it isn't the case.

File: trace/tracestate.go [hunk 21]
```diff
@@ -88,7 +88,8 @@ func (m member) String() string {
 // that conform to the specification. Specifically, this means that all
 // list-member's key/value pairs are valid, no duplicate list-members exist,
 // and the maximum number of list-members (32) is not exceeded.
-type TraceState struct { //nolint:golint
+//nolint:revive // revive complains about stutter of `trace.TraceState`
+type TraceState struct {
```
Comment (MrAlias) [inline trace/tracestate.go:92]:
```suggestion
type TraceState struct { //nolint:revive // revive complains about stutter of `trace.TraceState`
```

File: sdk/metric/sdk.go [hunk 22]
```diff
@@ -147,6 +147,7 @@ var (
 	_ metric.SyncImpl      = &syncInstrument{}
 	_ metric.BoundSyncImpl = &record{}
 
+	// ErrUninitializedInstrument is passed to otel.ErrorHandler to be returned when an instrument is uninitialized.
```
Comment (MadVikingGod) [inline sdk/metric/sdk.go:150]:
```suggestion
	// ErrUninitializedInstrument isreturned when an instrument is used when uninitialized.
```

**Review by MadVikingGod — APPROVED** [review]

**Review by pellared — APPROVED** [review]

**Review by MrAlias — CHANGES_REQUESTED** [review]
https://github.com/open-telemetry/opentelemetry-go/pull/1946#discussion_r638153975

**Comment by AndersonQ** [comment]
Sorry, I missed the suggestions, I've already applied them :)

**Review by MrAlias — APPROVED** [review]
