### PR TITLE
Do not handle empty partial OTLP successes

### LINKED ISSUE #3432: Extraneous Partial Success Error Message Exporting Traces to OTel Collector
### Description

I have successfully set up to use the Go OpenTelemetry libraries to export trace spans to an OpenTelemetry Collector using OTLP over gRPC. However, even though all the spans are being exported to the collector correctly, I am getting error messages in the OpenTelemetry log in my Go application which look like the following:

```
2022/10/30 22:55:09 OTLP partial success: empty message (0 spans rejected)
```

This message repeats as more spans are sent. I believe what is happening here is that the spans are sent, the response is a full success, but the Go library is mistaking it as a partial success. See the code below:

https://github.com/open-telemetry/opentelemetry-go/blob/3b9862a771d2413a0cc787fd0ce219adef8531d1/exporters/otlp/otlptrace/otlptracegrpc/client.go#L200-L217

I added a `fmt.Printf("%#v\n%#v", resp, resp.PartialSuccess)` in this code just before line 204 (the if statement) and got this...

```
&v1.ExportTraceServiceResponse{
    state:impl.MessageState{
        NoUnkeyedLiterals:pragma.NoUnkeyedLiterals{},
        DoNotCompare:pragma.DoNotCompare{},
        DoNotCopy:pragma.DoNotCopy{},
        atomicMessageInfo:(*impl.MessageInfo)(0x4000580948)
    },
    sizeCache:0,
    unknownFields:[]uint8(nil),
    PartialSuccess:(*v1.ExportTracePartialSuccess)(0x40006404c0)
}
&v1.ExportTracePartialSuccess{
    state:impl.MessageState{
        NoUnkeyedLiterals:pragma.NoUnkeyedLiterals{},
        DoNotCompare:pragma.DoNotCompare{},
        DoNotCopy:pragma.DoNotCopy{},
        atomicMessageInfo:(*impl.MessageInfo)(nil)
    },
    sizeCache:0,
    unknownFields:[]uint8(nil),
    RejectedSpans:0,
    ErrorMessage:""
}
```

As you can see, there were no rejected spans and no error message, so I believe this should be seen as a full success, and thus the log message is not needed.

### Environment

- OS: alpine 3.16.2
- Architecture: amd64
- Go Version: 1.18
- opentelemetry-go version: v1.11.1 (2fe8861)
- OTel Collector: 0.63.0

### Steps To Reproduce

1.) Set up an OTel collector that accepts traces over gRPC (in my case, no TLS).
2.) Set up an application using go's otel library to export traces to otel.
3.) See error messages in stderr even as traces are correct in exporting.

### Expected behavior

The traces should continue to successfully export, but there should be no error messages printed out, as a partial success did not actually occur.

### PR DESCRIPTION
**Pull request by MrAlias**
Fix #3432.

The OTLP server will respond with empty partial success responses (i.e. empty messages and 0 count). Treat these as equivalent to it not being set/present like the documentation specifies in the proto: https://github.com/open-telemetry/opentelemetry-proto/blob/724e427879e3d2bae2edc0218fff06e37b9eb46e/opentelemetry/proto/collector/trace/v1/trace_service.proto#L58

### CODE REVIEW

File: exporters/otlp/internal/partialsuccess_test.go [hunk 1]
```diff
@@ -36,9 +36,8 @@ func requireErrorString(t *testing.T, expect string, err error) {
 }
 
 func TestPartialSuccessFormat(t *testing.T) {
-	requireErrorString(t, "empty message (0 metric data points rejected)", PartialSuccessToError(MetricsPartialSuccess, 0, ""))
-	requireErrorString(t, "help help (0 metric data points rejected)", PartialSuccessToError(MetricsPartialSuccess, 0, "help help"))
-	requireErrorString(t, "what happened (10 metric data points rejected)", PartialSuccessToError(MetricsPartialSuccess, 10, "what happened"))
-	requireErrorString(t, "what happened (15 spans rejected)", PartialSuccessToError(TracingPartialSuccess, 15, "what happened"))
-	requireErrorString(t, "empty message (7 log records rejected)", PartialSuccessToError("log records", 7, ""))
+	requireErrorString(t, "empty message (0 metric data points rejected)", MetricPartialSuccessError(0, ""))
```
Comment (Aneurysm9) [inline exporters/otlp/internal/partialsuccess_test.go:39]: Doesn't this same change need to be made for the [metric](https://github.com/open-telemetry/opentelemetry-proto/blob/724e427879e3d2bae2edc0218fff06e37b9eb46e/opentelemetry/proto/collector/metrics/v1/metrics_service.proto#L58-L60) exporter?

Comment (MrAlias) [reply exporters/otlp/internal/partialsuccess_test.go:39]: It does, but we haven't implemented partial response handling there yet. I'm happy to add it in a follow on PR though.

FWIW, it is being tracked here: https://github.com/open-telemetry/opentelemetry-go/issues/3162

**Review by jmacd — APPROVED** [review]

**Review by hanyuancheung — APPROVED** [review]

**Review by MadVikingGod — APPROVED** [review]
