### PR TITLE
Kick label encoder out of sdk

### LINKED ISSUE #539: Prepare to remove `LabelSet`
There are three parts to this ticket to prepare the SDK for removing `LabelSet` from the API, as specified in https://github.com/open-telemetry/oteps/pull/90.

1. As mentioned [here](https://github.com/open-telemetry/opentelemetry-go/pull/523#discussion_r390606417), there is a TODO about replacing the `[]core.KeyValue` slice by a `Get(int) core.KeyValue` interface so that the array representation can support the interface, meaning we do not need to hold a reference to the original `kvs ...core.KeyValue` argument (which could be modified by the caller).
2. As mentioned [here](https://github.com/open-telemetry/opentelemetry-go/pull/523#discussion_r390606527), following PR #523 the label encoding will be recomputed once per collection interval per label set, which is a regression that we'd like fixed.
3. There is a great (and bad) dependency created between the SDK and the Batcher (Integrator) and the Exporters where the LabelEncoder is concerned. This was an optimization, as shown in #523, since the cost of computing a single label encoding once is less than the cost of one array map key and one single label encoding.  However, the code complexity is not worth it, we think, and after #523 the label encoding for a given set of labels is only needed for the Batcher (Integrator) and Exporters, not the `SDK` (Accumulator) itself. If more than one label encoding are needed by more than one exporter, the current code structure causes trouble.

In [OTEP 78](https://github.com/open-telemetry/oteps/issues/78), specifically [here](https://github.com/open-telemetry/opentelemetry-go/pull/427/files#diff-6bf038ff70296ed34eaa20d9cad0ba5e) or really [here](https://github.com/open-telemetry/opentelemetry-go/pull/427/files#diff-9f2d1e0f1e6cb16bca2348f23db82773), the `LabelSet` was made concrete and allowed to cache more than one label encoding. This was because OTEP 78 was moving `LabelSet` into the API. To address OTEP 90, we will remove the Meter `Labels(...)` API, but first we should address the three points above.

This can be done by re-implementing the `sdk/meter.labels` type, currently defined

```
	labels struct {
		meter   *SDK
		sorted  sortedLabels
		encoded string
	}
```

As we will remove `Labels(...)`, this struct can mostly shift into the `record` itself.  The `record` will now need a reference to its `SDK`. The `sortedLabels` is replaced in #523 by `orderedLabels` which will remain private to the SDK. The `export.Record` type will store an interface (of the `*record`) that supports `Get(int) core.KeyValue` instead of exposing a slice directly, which addresses [this comment](https://github.com/open-telemetry/opentelemetry-go/pull/523#discussion_r390605739). and the TODO in (1) above. The `export.Record`, in the same interface as `Get(int) core.KeyValue` will also support `Encode(LabelEncoder) string`, as shown in https://github.com/open-telemetry/opentelemetry-go/pull/427. Lastly, the `Encode()` function will support caching a small fixed number of encodings. This will be stored directly in the record, since these cached values should persist across collection intervals.

These steps will make it easy to remove `LabelSet` from the user-facing API in a future PR. :rocket:

### PR DESCRIPTION
**Pull request by krnowak**
This is a WIP on removing the dependency of SDK on label encoder. This PR attempts to address point 3 from #539.

`export.Labels` became an interface, which SDK implements. `export` package provides a simple, immutable implementation of the interface, mostly for testing, but the `defaultkeys` batcher also uses it.

~~I was thinking about dropping the `LabelStorage` interface, so the simple labels would rely on `[]core.KeyValue`.~~
I couldn't drop `LabelStorage` (`LabelIterator` uses it), but the simple labels now use `[]core.KeyValue` - that simplified the way we create the simple labels a bit.

The `export.LabelEncoder.ID` is likely going to be controversial - I'm using it for being able to store several encoded labels in case we need several different label encoders. Other solution would be to use `LabelEncoder` as a pointer, but the limitation would be that value-based label encoders wouldn't be cached at all (see https://github.com/jmacd/opentelemetry-go/blob/8bed2e14df7f9f4688fbab141924bb786dc9a3a1/api/context/internal/set.go#L89).

Closes #539.

TODO:

- ~~docs~~
- tests
  - ~~bring back the iterator benchmarks~~
- ~~move `defaultLabelEncoder` from `sdk/metric` to `sdk/export/metric`~~

### CODE REVIEW

File: sdk/metric/sdk.go [hunk 1]
```diff
@@ -374,6 +374,54 @@ func (ls *labels) GetLabel(idx int) core.KeyValue {
...
+	}
+	// Try to take the cache for ourselves. This is the place
+	// where other encoders may be "blocked".
+	if atomic.CompareAndSwapInt64(&ls.cachedEncoderID, 0, -1) {
+		// The cache is ours.
+		ls.cachedEncoded = encoded
+		atomic.StoreInt64(&ls.cachedEncoderID, id)
+	}
+	return encoded
+}
```
Comment (jmacd) [inline sdk/metric/sdk.go]: LGTM.

**Comment by krnowak** [comment]
Updated, ready for review.

File: sdk/metric/sdk.go [hunk 2]
```diff
@@ -366,14 +366,69 @@ func (m *SDK) Labels(kvs ...core.KeyValue) api.LabelSet {
...
+	// If cached ID is the same as ID of the passed encoder, we've
+	// got the fast path.
+	if cachedID == id {
+		return ls.cachedEncoded
+	}
+	// If we are here, either some other encoder cached its
+	// encoded labels or the cache is still for the taking. Either
+	// way, we need to compute the encoded labels anyway.
+	encoded := encoder.Encode(ls.Iter())
+	// If some other encoder took the cache, then we just return
```
Comment (MrAlias) [inline sdk/metric/sdk.go]: This caching scheme seems to only cache for a single encoder. Specifically the first encoder called. Any reason we cannot use a `sync.Map` to cache for all the encoders?

File: sdk/export/metric/metric.go [hunk 3]
```diff
@@ -260,27 +253,42 @@ func (i *LabelIterator) Len() int {
...
-	// syntax for serialized label sets should implement
-	// LabelEncoder, thus avoiding duplicate computation in the
-	// export path.
+	// The expectation is that when setting up an export pipeline
+	// both the batcher and the exporter will use the same label
+	// encoder to avoid the duplicate computation of the encoded
+	// labels in the export path.
 	Encode(LabelIterator) string
+
+	// ID should return a unique positive number associated with
```
[the remark this answers is not in the document]
Comment (krnowak) [reply sdk/export/metric/metric.go]: I'm reserving -1 for "pending the caching". And I don't expect a lot of label encoders to be registered, so rather no risk for an ID exhaustion.

File: sdk/metric/sdk.go (hunk 2 above)
Comment (krnowak) [reply sdk/metric/sdk.go]: Yeah. I don't know if we currently have a use case of having different label encoder for batcher and different for exporter. For now we expect them to use the same encoder, so caching scheme for a single encoder makes sense.

File: sdk/export/metric/metric.go [hunk 4]
```diff
@@ -16,11 +16,25 @@ package metric // import "go.opentelemetry.io/otel/sdk/export/metric"
 
 import (
 	"context"
+	"sync/atomic"
 
 	"go.opentelemetry.io/otel/api/core"
 	"go.opentelemetry.io/otel/api/metric"
 )
 
+// id 1 is reserved for noop label exporter
```
[the remark this answers is not in the document]
Comment (krnowak) [reply sdk/export/metric/metric.go]: Will do.

File: sdk/metric/sdk.go (hunk 2 above)
Comment (jmacd) [reply sdk/metric/sdk.go]: It's OK to support one for now, since that's the status quo. In the PR supporting OTEP 78 I let the labels object support caching up to three encodings. We could do that later.

File: sdk/export/metric/metric.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (jmacd) [reply sdk/export/metric/metric.go]: I suppose we could use a pointer to the implementation instead of unique integers?  I don't have strong feelings.

[the remark this answers is not in the document]
Comment (krnowak) [reply sdk/export/metric/metric.go]: The sole reason for using IDs was to not force the implementations of the label encoders to be pointers. The `NoopLabelEncoder` is an example here.

**Comment by krnowak** [comment]
Rebased and updated.

File: sdk/export/metric/metric.go [hunk 5]
```diff
@@ -16,11 +16,33 @@ package metric // import "go.opentelemetry.io/otel/sdk/export/metric"
...
 	"context"
+	"sync/atomic"
 
 	"go.opentelemetry.io/otel/api/core"
 	"go.opentelemetry.io/otel/api/metric"
 )
 
+const (
+	// reserved ID for the noop label exporter
+	noopLabelExporterID int64 = 1 + iota
```
Comment (MrAlias) [inline sdk/export/metric/metric.go]: This is probably my fault, but do we want to call these encoder IDs instead of exporter IDs?

Comment (krnowak) [reply sdk/export/metric/metric.go]: Nah, not your fault. I also tend to type label exporter all the time. :) Will fix.

Comment (krnowak) [reply sdk/export/metric/metric.go]: Looks like I have made this mistake like everywhere. Bonus points for me for consistency, I guess…

Comment (krnowak) [reply sdk/export/metric/metric.go]: See it yourself - https://github.com/open-telemetry/opentelemetry-go/pull/574/commits/4d88d811b807ab23521cab602a7726948e328f62.
