### PR TITLE
Safely truncate over-length string attributes

### LINKED ISSUE #3021: Invalid UTF-8 causes export failure while marshaling
```log
otel@v1.7.0/handler.go:44       otel err: rpc error: code = Internal desc = grpc: error while marshaling: string field contains invalid UTF-8
go.opentelemetry.io/otel.(*delegator).Handle
        /go/pkg/mod/go.opentelemetry.io/otel@v1.7.0/handler.go:44
go.opentelemetry.io/otel.Handle
        /go/pkg/mod/go.opentelemetry.io/otel@v1.7.0/handler.go:97
go.opentelemetry.io/otel/sdk/trace.(*batchSpanProcessor).processQueue
        /go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.7.0/trace/batch_span_processor.go:299
go.opentelemetry.io/otel/sdk/trace.NewBatchSpanProcessor.func1
        /go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.7.0/trace/batch_span_processor.go:125
```

According to #2314 ，truncation of multibyte UTF-8 strings configured via AttributeValueLengthLimit can cause this error.

eg:
```go
s := "你好"
fmt.Println(len(s)) // output: 6
fmt.Println(utf8.ValidString(s[:5])) // output: false
```

Looks like there are no plans to change string to byte in proto in the near future.

Checking each span may have performance loss, so is it possible to logging the span info or invalid string related to the error?

We can only fix manually now like this:
```go
func TruncateAttr(s string) string {
	if len(s) < 1000 {
		return s
	}
	return truncateAttr(s, 200, "...")
}

func truncateAttr(s string, limit int, add string) string {
	rn := []rune(s)
	if len(rn) > limit {
		rn = rn[:limit]
		return string(rn) + add
	}
	return s
}
```

### PR DESCRIPTION
**Pull request by jmacd**
This fixes invalid UTF-8 introduced by our truncation logic.
This does not address the problem of invalid UTF-8 being passed in by users, but it does at least ensure the SDK is not responsible for invalid UTF-8 itself.

Fixes #3021

### CODE REVIEW

**Review by dashpole — APPROVED** [review]

**Review by dmathieu — APPROVED** [review]

**Comment by jmacd** [comment]
This needs at least one more test. ;)

**Comment by jmacd** [comment]
PTAL. I had to rewrite the fallback case; when there is invalid UTF-8 it calls strings.ToValidUTF8 and then re-applies the same (safe) truncation logic.

**Comment by MadVikingGod** [comment]
The costly operation in this call is the ToValidUTF8, because it has to iterate over the entire string.  So this means how you have it now we iterate over the string once, try to apply the limit, and iterate a second time.

I think an alternative but still valid interpretation would be to apply the limit, and then filter bad unicode.  This would mean that if there bad points in the beginning of the string they would count toward the limit, even if they aren't in the output string.

**Comment by jmacd** [comment]
The way the code is organized, `strings.ToValidUTF8()` (which copies the data) will only be called when the user has supplied invalid code points. This seems like a good compromise, although I think OTel may have to address the problem of users supplying invalid UTF8 anyway.

File: sdk/trace/span.go [hunk 1]
```diff
@@ -324,14 +326,38 @@ func truncateAttr(limit int, attr attribute.KeyValue) attribute.KeyValue {
...
+// safeTruncate truncates the string and guarantees valid UTF-8 is returned.
+func safeTruncate(input string, limit int) string {
+	if trunc, ok := safeTruncateValidUTF8(input, limit); ok {
+		return trunc
+	}
+	trunc, _ := safeTruncateValidUTF8(strings.ToValidUTF8(input, ""), limit)
+	return trunc
+}
+
+func safeTruncateValidUTF8(input string, limit int) (string, bool) {
```
Comment (MrAlias) [inline sdk/trace/span.go:346]:
```suggestion
// safeTruncateValidUTF8 returns a copy of the input string safely truncated to
// limit. The truncation is ensured to occur at the bounds of complete UTF-8
// characters. If invalid encoding of UTF-8 is encountered, input is returned
// with false, otherwise, the truncated input will be returned with true.
func safeTruncateValidUTF8(input string, limit int) (string, bool) {
```

**Review by MrAlias — APPROVED** [review]

File: sdk/trace/span.go [hunk 2]
```diff
@@ -324,14 +326,38 @@ func truncateAttr(limit int, attr attribute.KeyValue) attribute.KeyValue {
...
 	}
 	return attr
 }
 
+// safeTruncate truncates the string and guarantees valid UTF-8 is returned.
+func safeTruncate(input string, limit int) string {
+	if trunc, ok := safeTruncateValidUTF8(input, limit); ok {
+		return trunc
+	}
+	trunc, _ := safeTruncateValidUTF8(strings.ToValidUTF8(input, ""), limit)
```
[the remark this answers is not in the document]
Comment (jmacd) [reply sdk/trace/span.go:342]: Not sure this is specified. It is somewhat common to use "�" to mark invalid code points. However, we're not marking the truncation itself either, so I wasn't sure this detailed mattered.

[the remark this answers is not in the document]
Comment (MrAlias) [reply sdk/trace/span.go:342]: Agreed I wasn't sure either. The truncation algo is under-specified in the spec so I think dropping invalid is an acceptable first pass approach here.

File: sdk/trace/span.go [hunk 3]
```diff
@@ -324,14 +326,42 @@ func truncateAttr(limit int, attr attribute.KeyValue) attribute.KeyValue {
...
+// characters. If invalid encoding of UTF-8 is encountered, input is returned
+// with false, otherwise, the truncated input will be returned with true.
+func safeTruncateValidUTF8(input string, limit int) (string, bool) {
+	for cnt := 0; cnt <= limit; {
+		r, size := utf8.DecodeRuneInString(input[cnt:])
+		if r == utf8.RuneError {
+			return input, false
+		}
+
+		if cnt+size > limit {
```
Comment (MrAlias) [inline sdk/trace/span.go:357]: One thing I noted [from the spec](https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification/common#attribute-limits) is that the limit is defined by characters not bits. I think we may need to keep a separate count of runes here, right?

Comment (MrAlias) [reply sdk/trace/span.go:357]: Don't think this is blocking, as we currently do not do this either. :shrug:

Comment (jmacd) [reply sdk/trace/span.go:357]: Since this issue has popped up in a lot of places, I'd like to see a quick fix put in place while this gets debated. I'd prefer to see "bytes" be the definition, but I agree it's ill-specified.

Comment (jmacd) [reply sdk/trace/span.go:357]: I would add that UTF-8 is documented as "self-synchronizing", which means we can implement an O(1) test for a valid UTF-8 boundary, if we want to, which may address part of our problem in a better way, but only part of the problem.

Given the discussion in https://github.com/open-telemetry/opentelemetry-proto/issues/426, I'm inclined to suggest that we: (1) not go after the O(1) test, (2) release this fix quickly, (3) debate for the next release what other UTF-8 sanitization should be done.

From anecdotal evidence, it's only the Golang protobuf library that's acting this way. We have seen C++ OTel clients sending invalid UTF-8 that we suspect also results from truncation, but in that case we see it when deserializing the data on our Go servers.

**Review by Aneurysm9 — APPROVED** [review]

File: sdk/trace/span.go (hunk 3 above)
Comment (MrAlias) [reply sdk/trace/span.go:357]: @jmacd can you create an issue to track this in the next release?

**Comment by jmacd** [comment]
Personally, I consider this an urgent matter and I would be willing to waive our ordinary wait period for PRs to merge after approvals. I suggest this because it's been about 4 weeks since the last release, and if we don't include this fix there will be immediate pressure to make another release. @open-telemetry/go-maintainers what do you think?

File: sdk/trace/span.go (hunk 3 above)
Comment (jmacd) [reply sdk/trace/span.go:357]: https://github.com/open-telemetry/opentelemetry-go/issues/3160

**Comment by MrAlias** [comment]
> Personally, I consider this an urgent matter and I would be willing to waive our ordinary wait period for PRs to merge after approvals. I suggest this because it's been about 4 weeks since the last release, and if we don't include this fix there will be immediate pressure to make another release. @open-telemetry/go-maintainers what do you think?

I'm fine merging this early. That said, @MadVikingGod has decided to hold off the release until Monday to make sure this is included.

**Review by hanyuancheung — APPROVED** [review]
