### PR TITLE
fix wrong representation of status value in zipkin exporter

### LINKED ISSUE #3287: Zipkin exporter and collector do not agree on wire representation of status codes
### Description
The Zipkin exporter and collector do not agree on wire representation of status codes. Please let me know if this issue should be filed in open-telemetry/opentelemetry-collector-contrib instead.

The Zipkin exporter serializes status codes as `Unset`, `Error`, and `Ok`:

https://github.com/open-telemetry/opentelemetry-go/blob/5568a3072367bb8ac4d2d9e759e7deb5a975b9f5/exporters/zipkin/model.go#L211-L213

https://github.com/open-telemetry/opentelemetry-go/blob/d616df61f5d163589228c5ff3be4aa5415f5a884/codes/codes.go#L38-L42

However, the collector expects `STATUS_CODE_UNSET`, `STATUS_CODE_OK`, or `STATUS_CODE_ERROR`, see [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/54c0a2e13f6d2e168804212d288cb808f179683e/pkg/translator/zipkin/zipkinv2/to_translator.go#L160).

### Environment
opentelemetry-go v1.11.0
opentelemetry-collector-contrib v0.62.0

### Steps To Reproduce
Using Grafana Tempo's [local example](https://github.com/grafana/tempo/tree/main/example/docker-compose/local):

```go
package main

import (
	"context"
	"log"

	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/exporters/zipkin"
	sdktrace "go.opentelemetry.io/otel/sdk/trace"
)

func main() {
	ctx := context.Background()

	exporter, err := zipkin.New("")
	if err != nil {
		log.Fatalf("creating exporter: %s", err)
	}

	tp := sdktrace.NewTracerProvider(
		sdktrace.WithSampler(sdktrace.AlwaysSample()),
		sdktrace.WithBatcher(exporter),
	)
	defer tp.Shutdown(ctx)
	otel.SetTracerProvider(tp)

	_, span := otel.Tracer("foo").Start(ctx, "foo")
	log.Printf("trace ID: %s", span.SpanContext().TraceID())
	span.SetStatus(codes.Error, "something went wrong")
	span.End()
}
```

image

### Expected behavior
Status is correctly passed between exporter and collector.

### PR DESCRIPTION
**Pull request by NewReStarter**
fix #3287 
Set the name of span status code to upper case, from`Unset`, `Ok`, `Error` to `UNSET`, `OK`, `ERROR` without making breaking changes. Previous version of code names can still be parsed.

### CODE REVIEW

**Comment by dmathieu** [comment]
I'm not sure this is the proper fix. Even though `UnmarshalJSON` remains the same here, the code actually changes, and the specification does require those codes to be capitalized, but not upper-case.
See https://github.com/open-telemetry/opentelemetry-specification/blob/fa36d43c4fe19207e653470d4efb13ff4361f711/specification/trace/api.md#set-status

I think the uppercasing should happen within the zipkin exporter, not for all codes.

**Comment by NewReStarter** [comment]
> > I think the uppercasing should happen within the zipkin exporter, not for all codes.
> 
> Agreed

Thx, I didn't notice the side effect. New version of this fix has been submitted, please help do the further review.

File: exporters/zipkin/model_test.go [hunk 1]
```diff
@@ -409,7 +410,7 @@ func TestModelConversion(t *testing.T) {
 				"attr1":            "42",
 				"attr2":            "bar",
 				"attr3":            "[0,1,2]",
-				"otel.status_code": "Error",
+				"otel.status_code": "ERROR",
```
Comment (dmathieu) [inline exporters/zipkin/model_test.go:413]: We only ever have tests where the status code is `ERROR`. How about adding two, for `OK` and `UNSET`?

Comment (NewReStarter) [reply exporters/zipkin/model_test.go:413]: for sure, will add corresponding test cases.

Comment (NewReStarter) [reply exporters/zipkin/model_test.go:576]: added

**Review by dmathieu — APPROVED** [review]

File: CHANGELOG.md [hunk 2]
```diff
@@ -22,6 +22,7 @@ This project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.htm
 - Slice attributes of `attribute` package are now comparable based on their value, not instance. (#3108 #3252)
 - Prometheus exporter will now cumulatively sum histogram buckets. (#3281)
 - Export the sum of each histogram datapoint uniquely with the `go.opentelemetry.io/otel/exporters/otlpmetric` exporters. (#3284, #3293)
+- Exported `Status` codes in `zipkin` exporter are now upper case. (#3340)
```
Comment (MrAlias) [inline CHANGELOG.md:25]:
```suggestion
- Exported `Status` codes in the `go.opentelemetry.io/otel/exporters/zipkin` exporter are now exported as all upper case values. (#3340)
```

File: exporters/zipkin/model.go [hunk 3]
```diff
@@ -209,7 +210,9 @@ func toZipkinTags(data tracesdk.ReadOnlySpan) map[string]string {
 	}
 
 	if data.Status().Code != codes.Unset {
-		m["otel.status_code"] = data.Status().Code.String()
+		// zipkin expect to receive upper case STATUS values
```
Comment (MrAlias) [inline exporters/zipkin/model.go:213]:
```suggestion
		// Zipkin expect to receive uppercase status values
```

File: exporters/zipkin/model_test.go [hunk 4]
```diff
@@ -809,7 +973,40 @@ func TestTagsTransformation(t *testing.T) {
...
+				},
+				Status: tracesdk.Status{
+					Code:        codes.Ok,
+					Description: "",
+				},
+			},
+			want: map[string]string{
+				"key":              keyValue,
+				"ok":               "true",
+				"otel.status_code": strings.ToUpper(codes.Ok.String()),
```
[the remark this answers is not in the document]
Comment (NewReStarter) [reply exporters/zipkin/model_test.go:1005]: Although I understand the specification for trace is stable now, still are there any chances of changing `codes.Ok.String()` in the future? That's the reason I use upper case method instead of using `"OK"` and `"ERROR"` string.

[the remark this answers is not in the document]
Comment (MrAlias) [reply exporters/zipkin/model_test.go:1005]: The specification is [stable](https://github.com/open-telemetry/opentelemetry-specification/blob/5edc08b671db33a57bbb4901593c2bbf71c89fa9/specification/trace/sdk_exporters/zipkin.md) for the zipkin exporter and it requires these status to be `OK` and `ERROR` respectively. If the values change to something other than this we would not comply with the specification. Therefore, defined the tests to test this exact behavior.

**Review by hanyuancheung — APPROVED** [review]

File: CHANGELOG.md [hunk 5]
```diff
@@ -36,6 +36,7 @@ This project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.htm
 - The `Shutdown` and `ForceFlush` methods of the `"go.opentelemetry.io/otel/sdk/trace".TraceProvider` no longer return an error when no processor is registered. (#3268)
 - The Prometheus exporter in `go.opentelemetry.io/otel/exporters/prometheus` cumulatively sums histogram buckets. (#3281)
 - The sum of each histogram data point is now uniquely exported by the `go.opentelemetry.io/otel/exporters/otlpmetric` exporters. (#3284, #3293)
+- Exported `Status` codes in the `go.opentelemetry.io/otel/exporters/zipkin` exporter are now exported as all upper case values. (#3340)
```
Comment (MrAlias) [inline CHANGELOG.md:39]: Please move this to the unreleased section.

**Review by MrAlias — APPROVED** [review]
