### PR TITLE
Handle duplicate Aggregators and log instrument conflicts

### LINKED ISSUE #3229: Duplicate instrument registration generates an error instead of a valid instrument
### Description

[Spec says](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#instrument-type-conflict-detection):
> When more than one Instrument of the same name is created for identical Meters, denoted duplicate instrument registration, the implementation MUST create a valid Instrument in every case.

The loop in the following code creates a duplicate instrument. An error is generated and the instrument is not valid.

### Steps To Reproduce

```go
module main

go 1.19

require (
	go.opentelemetry.io/otel v1.10.0
	go.opentelemetry.io/otel/exporters/stdout/stdoutmetric v0.32.1
	go.opentelemetry.io/otel/sdk v1.10.0
	go.opentelemetry.io/otel/sdk/metric v0.32.1
)

require (
	github.com/go-logr/logr v1.2.3 // indirect
	github.com/go-logr/stdr v1.2.2 // indirect
	go.opentelemetry.io/otel/metric v0.32.1 // indirect
	go.opentelemetry.io/otel/trace v1.10.0 // indirect
	golang.org/x/sys v0.0.0-20210510120138-977fb7262007 // indirect
)
```

```go
package main

import (
	"context"
	"log"
	"time"

	"go.opentelemetry.io/otel/exporters/stdout/stdoutmetric"
	"go.opentelemetry.io/otel/sdk/metric"
)

func main() {
	ctx := context.Background()

	exporter, _ := stdoutmetric.New()

	reader := metric.NewPeriodicReader(
		exporter,
		metric.WithInterval(time.Second),
	)

	meterProvider := metric.NewMeterProvider(
		metric.WithReader(reader),
	)

	meter := meterProvider.Meter("my-meter")

	for i := 0; i < 10; i++ {
		counter, err := meter.SyncFloat64().Counter("my-counter")

		if err != nil {
			// Shouldn't get here.
			// Identical instrument registration should be allowed.
			// https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#instrument-type-conflict-detection
			log.Fatalf("failed to initialize instrument: %v", err)
		}

		counter.Add(ctx, 12.0)
		time.Sleep(500 * time.Millisecond)
	}

	meterProvider.Shutdown(ctx)
}
```

### LINKED ISSUE #3240: Compatible aggregators should not error instrument creation
The [OTel spec](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.13.0/specification/metrics/sdk.md#view) says:

> - For each View, if the Instrument could match the instrument selection criteria:
>    - Try to apply the View configuration. If applying the View results in conflicting metric identities the implementation SHOULD apply the View and emit a warning. If it is not possible to apply the View without producing semantic errors (e.g. the View sets an asynchronous instrument to use the Explicit bucket histogram aggregation) the implementation SHOULD emit a warning and proceed as if the View did not exist.

If a view translates an instrument into the exact same as another instrument the same aggregators from the already registered instrument should be updated and pulled from.

Currently, we do not check compatibility:

https://github.com/open-telemetry/opentelemetry-go/blob/aca054b07588d85cd974b041b4e6688eff918a38/sdk/metric/pipeline.go#L107-L109

Instead, we just return an error saying the instrument was already registered.

To make matters worse, with the error we return an `internal.Aggregator` that will never be pulled from:

https://github.com/open-telemetry/opentelemetry-go/blob/aca054b07588d85cd974b041b4e6688eff918a38/sdk/metric/pipeline.go#L229-L238

### Environment

- opentelemetry-go version: aca054b07588d85cd974b041b4e6688eff918a38

### Steps To Reproduce

Change this line to check for `NoError`

https://github.com/open-telemetry/opentelemetry-go/blob/aca054b07588d85cd974b041b4e6688eff918a38/sdk/metric/pipeline_registry_test.go#L415

Run the tests

```terminal
$ go test .
--- FAIL: TestPipelineRegistryCreateAggregatorsDuplicateErrors (0.00s)
    pipeline_registry_test.go:415:
        	Error Trace:	pipeline_registry_test.go:415
        	Error:      	Received unexpected error:
        	            	%!w(<nil>): could not create all aggregators: instrument already registered: name foo, scope: {  }
        	Test:       	TestPipelineRegistryCreateAggregatorsDuplicateErrors
FAIL
FAIL	go.opentelemetry.io/otel/sdk/metric	0.010s
FAIL
```

### Expected behavior

Test should pass with that modification and the returned `internal.Aggregator` should update the existing registered on.e

### PR DESCRIPTION
**Pull request by MrAlias**
When a `Meter` is asked to create an instrument that already exists...

- If it is the exact same instrument, it should return the same instance and update the already created `Aggregator`s.
- If it is not the exact same, but does share a name, it should return a new instrument with new `Aggregator`s but log the collision as a warning.

This PR updates the metric SDK to achieve these things. It does this with the following.

- Add the `cache` type described in #3245 
- Add an `instrumentCache` that wraps two `cache`s. One to cache instrument aggregations and ensure they are unique. The other to cache resolved view `instrumentID`s so any conflicting creations are logged (something [recommended by the spec](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.13.0/specification/metrics/sdk.md#view)).
- Maintain caches at a `Meter` level. This ensures that no duplicate instruments are issued per instrumentation scope. It also ensures that instrument conflicts are appropriately logged as such per instrumentation scope.
- Refactor the pipeline data storage. Instruments are de-duplicated prior to being passed to the pipeline, stop checking for duplicates when added to the pipeline.
   - This allows for the storage type to drop one level of `map`s.

Part of #3245 
Fix #3240 
Fix #3229

### CODE REVIEW

File: sdk/metric/meter.go [hunk 1]
```diff
@@ -83,6 +83,19 @@ func (r *meterRegistry) Get(s instrumentation.Scope) *meter {
...
+	//
+	// Duplicate instrument creations for different number types are identified
+	// in the viewCache. Since the conflict is "resolvable", a valid aggregator
+	// still needs to be returned when this occurs. Therefore, instruments of
+	// different numbers are not tracked with the same cache.
+	aggregatorCacheInt64   cache[instrumentID, aggVal[int64]]
+	aggregatorCacheFloat64 cache[instrumentID, aggVal[float64]]
+	// viewCache ensures instrument conflicts this meter is asked to create are
+	// logged to the user.
+	viewCache cache[string, instrumentID]
```
Comment (MadVikingGod) [inline sdk/metric/meter.go:97]: Is there a reason to have these as the raw aggregatorsCache and view caches, which we use to create InstrumentChaches in the sync/async methods, over just storing the instrument caches here?

File: sdk/metric/pipeline.go [hunk 2]
```diff
@@ -178,96 +157,181 @@ func (p *pipeline) produce(ctx context.Context) (metricdata.ResourceMetrics, err
...
+//
+// If an instrument is determined to use a Drop aggregation, that instrument is
+// not inserted nor returned.
 func (i *inserter[N]) Instrument(inst view.Instrument, instUnit unit.Unit) ([]internal.Aggregator[N], error) {
-	seen := map[instrumentID]struct{}{}
 	var aggs []internal.Aggregator[N]
 	errs := &multierror{wrapped: errCreatingAggregators}
+	// The cache will return the same Aggregator instance. Use this fact to
+	// compare pointer addresses to deduplicate Aggregators.
+	seen := make(map[internal.Aggregator[N]]struct{})
```
Comment (MadVikingGod) [inline sdk/metric/pipeline.go:194]: This means we are relying on the (somewhat) unstated idea that `internal.Aggregator`s are going to be references.  I'm ok with that assumption, as I think it will be almost universal, but we should probably document that with the interface for those who come after.

**Review by MadVikingGod — APPROVED** [review]
Only minor nits.

File: sdk/metric/meter.go (hunk 1 above)
Comment (MrAlias) [reply sdk/metric/meter.go:97]: Yeah, I was thinking how to stage this change with the follow on ones related to caching that would unify this. Given you're asking, it make sense that I should include the field differently here. I'll update.

File: sdk/metric/pipeline.go (hunk 2 above)
Comment (MrAlias) [reply sdk/metric/pipeline.go:194]: Given this is a type from an internal package it seemed like something we could indeed guarantee.

Where were you thinking of adding documentation for this?

Comment (MrAlias) [reply sdk/metric/pipeline.go:194]: @MadVikingGod I added https://github.com/open-telemetry/opentelemetry-go/pull/3251/commits/1f836588b9d8ba37638e255f270b86085b485aed, does that address this?

Comment (MadVikingGod) [reply sdk/metric/pipeline.go:194]: I was thinking more a comment around https://github.com/open-telemetry/opentelemetry-go/blob/main/sdk/metric/internal/aggregator.go#L28-L29. But tests don't hurt.

Comment (MrAlias) [reply sdk/metric/pipeline.go:194]: Updated.

File: sdk/metric/meter.go [hunk 3]
```diff
@@ -55,10 +55,7 @@ func (r *meterRegistry) Get(s instrumentation.Scope) *meter {
 	defer r.Unlock()
 
 	if r.meters == nil {
-		m := &meter{
-			Scope: s,
-			pipes: r.pipes,
-		}
+		m := newMeter(s, r.pipes)
```
[the remark this answers is not in the document]
Comment (MrAlias) [reply sdk/metric/meter.go:58]: Indeed. I've handled this in https://github.com/open-telemetry/opentelemetry-go/pull/3255. I want to limit the scope of this to address delicate instruments and spec compliance as best as possible.

**Review by Aneurysm9 — APPROVED** [review]
