### PR TITLE
fix: lock accesses to encoder in json stdout exporter to prevent crash

### LINKED ISSUE #2264: [crash] stdout json exporter crashes when many spans generated at once
### Description

Crash due to insufficient locking in #2196 which switched from a thread-safe JSON package method to a non-thread-safe JSON exporter object that uses a single buffer

### Environment

- OS: Linux
- Architecture: amd64
- Go Version: 1.17.1
- opentelemetry-go version: v1.0.0

### Steps To Reproduce

Generate many spans at once, with JSON and pretty-printing on, and simplespanexporter used as the export method e.g. https://glitch.com/edit/#!/intro-to-o11y-go?path=src%2Fmain.go%3A85%3A37

### Expected behavior

No crash, all spans exported successfully and in sequence

### Observed behavior

```
goroutine 71 [running]:
bytes.(*Buffer).WriteByte(0xc000172cb0, 0xc0)
	/tmp/go/src/bytes/buffer.go:269 +0x85
encoding/json.newline(0xc0004c4340, {0x0, 0x0}, {0xa199c0, 0x1}, 0x3)
	/tmp/go/src/encoding/json/indent.go:63 +0x45
encoding/json.Indent(0xc0005de330, {0xc00048e000, 0x439, 0x0}, {0x0, 0x0}, {0xa199c0, 0x1})
	/tmp/go/src/encoding/json/indent.go:118 +0x245
encoding/json.(*Encoder).Encode(0xc0000889b0, {0x935fe0, 0xc000142300})
	/tmp/go/src/encoding/json/stream.go:225 +0x18b
go.opentelemetry.io/otel/exporters/stdout/stdouttrace.(*Exporter).ExportSpans(0xc0003250b0, {0x98ef9b6c6f889cc8, 0xe096794a2d1d49d}, {0xc0005e1760, 0x0, 0x1})
	/app/pkg/mod/go.opentelemetry.io/otel/exporters/stdout/stdouttrace@v1.0.0/trace.go:86 +0x1dc
go.opentelemetry.io/otel/sdk/trace.(*simpleSpanProcessor).OnEnd(0xc00007d580, {0xac0df8, 0xc000142180})
	/app/pkg/mod/go.opentelemetry.io/otel/sdk@v1.0.0/trace/simple_span_processor.go:58 +0x1e6
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0xc000142000, {0x0, 0x0, 0x0})
	/app/pkg/mod/go.opentelemetry.io/otel/sdk@v1.0.0/trace/span.go:280 +0x9e2
go.opentelemetry.io/contrib/instrumentation/net/http/httptrace/otelhttptrace.(*clientTracer).end(0xc0004a45a0, {0xc0005f2fc0, 0xc00014b4d8}, {0x0, 0x0}, {0xc0005a3600, 0x2, 0x2})
	/app/pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/httptrace/otelhttptrace@v0.24.0/clienttrace.go:224 +0x46d
```

### PR DESCRIPTION
**Pull request by lizthegrey**
## Which problem is this PR solving?

- locks accesses to encoder. fixes #2264

verified that https://github.com/open-telemetry/opentelemetry-go/blob/79df6ec38f378a9a25715d7976f5beb57997dfbf/exporters/stdout/stdoutmetric/metric.go#L162 does not suffer from this problem and thus doesn't also need to be fixed.

## Short description of the changes

- locks accesses to encoder. fixes #2264

### CODE REVIEW

File: exporters/stdout/stdouttrace/trace.go [hunk 1]
```diff
@@ -83,6 +84,8 @@ func (e *Exporter) ExportSpans(ctx context.Context, spans []trace.ReadOnlySpan)
 		}
 
 		// Encode span stubs, one by one
+		e.encoderMu.Lock()
```
Comment (Aneurysm9) [inline exporters/stdout/stdouttrace/trace.go:87]: I think this needs to move outside the loop at 74.  This will work fine with the simple span processor, which only sends `spans` with length 1, but will deadlock with the batch span processor when it tries to take a lock when processing the second span.

Comment (lizthegrey) [reply exporters/stdout/stdouttrace/trace.go:87]: will fix!

Comment (lizthegrey) [reply exporters/stdout/stdouttrace/trace.go:87]: I'll fix!

**Review by pellared — APPROVED** [review]

**Comment by MadVikingGod** [comment]
Are we sure the problem is caused by concurrent access to the exporter's
buffer? If it is we need to make sure all of our exporters are reentrant,
because one of our assumptions of the Export() function is that the
processor won't call it concurrently.

The panic, that your example cuts off, is index out of range of the backing
buffer. Specifically, it happens when the buffer inside the json encoder
reslices it's buffer when it can't.  I think we need to explore a bit more
into what is causing this issue.

**Comment by Aneurysm9** [comment]
That's a good point @MadVikingGod.  It looks like the `SimpleSpanProcessor` is [only taking a read lock](https://github.com/open-telemetry/opentelemetry-go/blob/main/sdk/trace/simple_span_processor.go#L54-L55) on the exporter mutex, which wouldn't serialize access.  See [this discussion](https://github.com/open-telemetry/opentelemetry-go/pull/1612#discussion_r583942311) on its addition for more context.

I think that it should be safe to change that to an exclusive lock given that the `SimpleSpanProcessor` is expected to be synchronous.  I don't think it hurts to also add the mutex around the `stdouttrace` exporter's use of the JSON encoder.

**Comment by lizthegrey** [comment]
> That's a good point @MadVikingGod. It looks like the `SimpleSpanProcessor` is [only taking a read lock](https://github.com/open-telemetry/opentelemetry-go/blob/main/sdk/trace/simple_span_processor.go?rgh-link-date=2021-09-28T15%3A05%3A47Z#L54-L55) on the exporter mutex, which wouldn't serialize access. See [this discussion](https://github.com/open-telemetry/opentelemetry-go/pull/1612#discussion_r583942311) on its addition for more context.
> 
> I think that it should be safe to change that to an exclusive lock given that the `SimpleSpanProcessor` is expected to be synchronous. I don't think it hurts to also add the mutex around the `stdouttrace` exporter's use of the JSON encoder.

I fingered the change to the json encoder as the proximal change, because this is a regression from 0.20.0, and the simplespanprocessor hadn't changed since then. But I'm flexible as to how we fix this.

**Comment by evantorrie** [comment]
Root cause of the problem does appear to be that Go standard library's `json.Encoder` is *not* thread safe when using non-empty `indentPrefix` and/or `indentValue`.

It reuses the same `indentBuf` inside the `Encoder` struct rather than creating a new buffer each invocation to handle the pretty-printed JSON output.

**Comment by lizthegrey** [comment]
> Root cause of the problem does appear to be that Go standard library's `json.Encoder` is _not_ thread safe when using non-empty `indentPrefix` and/or `indentValue`.
> 
> It reuses the same [`indentBuf` inside the `Encoder`](https://github.com/golang/go/blob/04242ac88fc16aca0353ed37a5eacef86a2eba98/src/encoding/json/stream.go#L219-L230) struct rather than creating a new buffer each invocation to handle the pretty-printed JSON output.
Yeah, this is documented here: https://github.com/golang/go/issues/32957

> @lizthegrey Does it work if you remove the pretty-printing option from the the `stdouttrace` exporter?
I'm sure it would, but Go gives guidance that you should not assume stdlib objects are thread-safe unless documented otherwise.

**Comment by Aneurysm9** [comment]
@lizthegrey can you merge in `main` and I'll get this merged?  We can evaluate separately whether the simple span processor should be blocking as well.

**Comment by lizthegrey** [comment]
branch updated
