### PR TITLE
Fix span IsRecording when not sampling

### LINKED ISSUE #1664: span.IsRecording() returns true even when Sampler indicates it should be DROPPED
Currently the Go code for `span.IsRecording()` returns true if `s.endTime.IsZero() == true`.

But the default SDK's span creation function will return a span with `span.endTime.IsZero()` (default initialized)  even if the associated `Sampler.ShouldSample()` function [returns `DROP`](https://github.com/open-telemetry/opentelemetry-go/blob/37688ef67616aa5a99e27fb03320fd0dc87e590e/sdk/trace/span.go#L545-L550). 

Based on the [current specification](https://github.com/open-telemetry/opentelemetry-specification/blob/6a44c1964baa63c3baeaa530846233cca6c7312e/specification/trace/sdk.md#sampler), `DROP` should result in `IsRecording() == false`

> DROP - IsRecording() == false, span will not be recorded and all events and attributes will be dropped.

Possibly related issue in opentelemetry-specification: https://github.com/open-telemetry/opentelemetry-specification/issues/1507

### PR DESCRIPTION
**Pull request by bryan-aguilar**
The `span.IsRecording()` call would incorrectly return true even if the `Sampler.ShouldSample() == DROP`. 

An issue also arose in `TestSampling` test case after the original issue was resolved. The test case checked that all three `executionTracerTaskEnd` functions would be executed instead of just one. These function calls are never executed if the span was not recorded. 

Fixes #1664

### CODE REVIEW

File: sdk/trace/trace_test.go [hunk 1]
```diff
@@ -1094,7 +1117,8 @@ func TestExecutionTracerTaskEnd(t *testing.T) {
 	for _, span := range spans {
 		span.End()
 	}
-	if got, want := n, uint64(len(spans)); got != want {
+	//Only one span should execute TracerTaskEnd
```
Comment (MrAlias) [inline sdk/trace/trace_test.go:1120]:
```suggestion
	// Only one span should be sampled meaning only one execution of
	// executionTracerTaskEnd.
```

**Review by MrAlias — APPROVED** [review]

**Review by Aneurysm9 — APPROVED** [review]

**Review by XSAM — APPROVED** [review]

**Comment by MrAlias** [comment]
@bryan-aguilar updates from maintainer are off for this PR so I'm not able to merge in main. Can you do this so we can merge this PR?

**Comment by bryan-aguilar** [comment]
@MrAlias Updated, sorry about that.
