### PR TITLE
fix data race in BatchedSpanProcessor

### LINKED ISSUE #517: data race in BatchedSpanProcessor
==================
WARNING: DATA RACE
Read at 0x00c0004ecb78 by goroutine 64:
  go.opentelemetry.io/otel/sdk/trace.(*BatchSpanProcessor).enqueue()
      /Users/rahulpa/rghetia/go/src/go.opentelemetry.io/otel/sdk/trace/batch_span_processor.go:210 +0xe4
  go.opentelemetry.io/otel/sdk/trace.(*BatchSpanProcessor).OnEnd()
      /Users/rahulpa/rghetia/go/src/go.opentelemetry.io/otel/sdk/trace/batch_span_processor.go:133 +0x42
  go.opentelemetry.io/otel/sdk/trace.(*span).End.func1()
      /Users/rahulpa/rghetia/go/src/go.opentelemetry.io/otel/sdk/trace/span.go:128 +0x2af
  sync.(*Once).doSlow()
      /usr/local/go/src/sync/once.go:66 +0x100
  sync.(*Once).Do()
      /usr/local/go/src/sync/once.go:57 +0x68
  go.opentelemetry.io/otel/sdk/trace.(*span).End()
      /Users/rahulpa/rghetia/go/src/go.opentelemetry.io/otel/sdk/trace/span.go:117 +0x154
  go.opentelemetry.io/otel/sdk/trace_test.generateSpan.func1()
      /Users/rahulpa/rghetia/go/src/go.opentelemetry.io/otel/sdk/trace/batch_span_processor_test.go:196 +0x15b

Previous write at 0x00c0004ecb78 by goroutine 60:
  go.opentelemetry.io/otel/sdk/trace.(*BatchSpanProcessor).enqueue()
      /Users/rahulpa/rghetia/go/src/go.opentelemetry.io/otel/sdk/trace/batch_span_processor.go:210 +0xfe
  go.opentelemetry.io/otel/sdk/trace.(*BatchSpanProcessor).OnEnd()
      /Users/rahulpa/rghetia/go/src/go.opentelemetry.io/otel/sdk/trace/batch_span_processor.go:133 +0x42
  go.opentelemetry.io/otel/sdk/trace.(*span).End.func1()
      /Users/rahulpa/rghetia/go/src/go.opentelemetry.io/otel/sdk/trace/span.go:128 +0x2af
  sync.(*Once).doSlow()
      /usr/local/go/src/sync/once.go:66 +0x100
  sync.(*Once).Do()
      /usr/local/go/src/sync/once.go:57 +0x68
  go.opentelemetry.io/otel/sdk/trace.(*span).End()
      /Users/rahulpa/rghetia/go/src/go.opentelemetry.io/otel/sdk/trace/span.go:117 +0x154
  go.opentelemetry.io/otel/sdk/trace_test.generateSpan.func1()
      /Users/rahulpa/rghetia/go/src/go.opentelemetry.io/otel/sdk/trace/batch_span_processor_test.go:196 +0x15b

### PR DESCRIPTION
**Pull request by rghetia**
- fixes #517

### CODE REVIEW

File: sdk/trace/batch_span_processor_test.go [hunk 1]
```diff
@@ -136,18 +131,32 @@ func TestNewBatchSpanProcessorWithOptions(t *testing.T) {
...
 		ssp := createAndRegisterBatchSP(t, option, &te)
 		if ssp == nil {
-			t.Errorf("%s: Error creating new instance of BatchSpanProcessor\n", option.name)
+			t.Fatalf("%s: Error creating new instance of BatchSpanProcessor\n", option.name)
 		}
 		tp.RegisterSpanProcessor(ssp)
 		tr := tp.Tracer("BatchSpanProcessorWithOptions")
 
-		generateSpan(t, tr, option)
+		wg := &sync.WaitGroup{}
```
Comment (MrAlias) [inline sdk/trace/batch_span_processor_test.go]: Is there a reason the WaitGroup isn't created and handled in `generateSpan` itself?

Comment (rghetia) [reply sdk/trace/batch_span_processor_test.go]: there is no reason. Moved it to generateSpan.
