### PR TITLE
Empty queued spans when ForceFlush called

### LINKED ISSUE #2080: Guarantee ForceFlush of BatchSpanProcessor will export all ended spans
### Problem Statement

Currently calling ForceFlush on a BatchSpanProcessor will export all spans which have been ended AND consumed into the BSP's batch. However, spans which have been ended before a call to ForceFlush are not guaranteed to be consumed into the batch and therefore may or may not be exported by ForceFlush as desired.

### Proposed Solution

I would like ForceFlush to ensure any ended spans are indeed exported following a call to ForceFlush. 

I have attempted to modify ForceFlush myself to process the queue before exporting but have achieved only mixed results.

#### Prior Art

Using runtime.Gosched() either within ForceFlush or in user code before calling ForceFlush to yield execution and allow consumption to occur naturally is very likely to populate the batch with any ended spans, but is not guaranteed to do so.

### Additional Context
A simple test case which would pass after such a change is as follows:

```
// Sometimes passes
func TestBSPForce(t *testing.T) {
	ctx := context.Background()

	exp := tracetest.NewInMemoryExporter()

	tp := sdktrace.NewTracerProvider(
		sdktrace.WithBatcher(exp),
	)

	tracer := tp.Tracer("tracer")

	_, span := tracer.Start(ctx, "span")
	span.End()
	
	// runtime.Gosched() - with this uncommented I have yet to see this test fail but would like a stronger guarantee
	err := tp.ForceFlush(ctx)
	assert.NoError(t, err)

	// Expect well defined behavior due to calling ForceFlush
	assert.Len(t, exp.GetSpans(), 1)
}
```

Intuitively I would already expect this test case to pass, however, current behavior of the BatchSpanProcessor causes the result of this test case to be inconsistent.

### PR DESCRIPTION
**Pull request by pkwarren**
Update the implementation of ForceFlush() to first ensure that all spans
which are queued are added to the batch before calling export spans.
Create a small ReadOnlySpan implementation which can be used as a marker
that ForceFlush has been invoked and used to notify when all spans are
ready to be exported.

Fixes #2080.

### CODE REVIEW

File: sdk/trace/batch_span_processor.go [hunk 1]
```diff
@@ -153,10 +154,29 @@ func (bsp *batchSpanProcessor) Shutdown(ctx context.Context) error {
 	return err
 }
 
+type forceFlushSpan struct {
+	ReadOnlySpan
+	flushed chan struct{}
+}
+
+func (f forceFlushSpan) SpanContext() trace.SpanContext {
+	return trace.NewSpanContext(trace.SpanContextConfig{TraceFlags: trace.FlagsSampled})
```
Comment (pkwarren) [inline sdk/trace/batch_span_processor.go:163]: Using enqueue requires that the span being queued is marked as sampled.

File: sdk/trace/batch_span_processor.go [hunk 2]
```diff
@@ -153,10 +154,29 @@ func (bsp *batchSpanProcessor) Shutdown(ctx context.Context) error {
...
+}
+
 // ForceFlush exports all ended spans that have not yet been exported.
 func (bsp *batchSpanProcessor) ForceFlush(ctx context.Context) error {
 	var err error
 	if bsp.e != nil {
+		flushCh := make(chan struct{})
+		bsp.enqueueBlockOnQueueFull(ctx, forceFlushSpan{flushed: flushCh}, true)
```
Comment (pkwarren) [inline sdk/trace/batch_span_processor.go:171]: Pass true as the last argument here since we want to block for this span to be queued.

File: sdk/trace/batch_span_processor.go [hunk 3]
```diff
@@ -296,6 +320,10 @@ func (bsp *batchSpanProcessor) drainQueue() {
 }
 
 func (bsp *batchSpanProcessor) enqueue(sd ReadOnlySpan) {
+	bsp.enqueueBlockOnQueueFull(context.TODO(), sd, bsp.o.BlockOnQueueFull)
```
Comment (pkwarren) [inline sdk/trace/batch_span_processor.go:323]: In order to work in the ForceFlush method, it was needed to pass a context (to allow cancellation).

**Review by seanschade — APPROVED** [review]

**Review by Aneurysm9 — APPROVED** [review]

**Comment by pkwarren** [comment]
Sorry for delay on CLA - that is now approved. Does this need a CI build to be approved now?

**Comment by pkwarren** [comment]
There is a test `TestNew_collectorConnectionDiesThenReconnects` failing with this PR when running the tests with the race detector in exporters/otlp/otlptrace/otlptracegrpc. I'm able to reproduce the same failure locally on the main branch with this command:

```
$ cd exporters/otlp/otlptrace/otlptracegrpc
$ for in in `seq 1 100`; do go test ./... -run '^\QTestNew_collectorConnectionDiesThenReconnects\E$' -count 1 -race -v; done
```

Is this a known flaky test? I also saw it referenced in #2285.

**Comment by Aneurysm9** [comment]
I think there have been a couple attempts to address that flake test, but it has thus far eluded correction.

**Review by jmacd — APPROVED** [review]
