### PR TITLE
sdk/resource: honor OTEL_SERVICE_NAME in fromEnv resource detector

### LINKED ISSUE #1968: Enable Resource `service.name` detection from `OTEL_SERVICE_NAME` environment variable
### Description

Recent [change in the specification](https://github.com/open-telemetry/opentelemetry-specification/pull/1677) has added a way to explicitly set the `service.name` attribute of the `Resource` via the `OTEL_SERVICE_NAME` environment variable. This should override any `service.name` attribute in `OTEL_RESOURCE_ATTRIBUTES`.

### Environment

- OS: All
- Architecture: All
- Go Version: All
- opentelemetry-go version: v0.20.0

### Steps To Reproduce

1. Set the environment variable `OTEL_SERVICE_NAME` to `foo`
2. Start an OpenTelemetry enabled process which outputs the `Resource` attributes.

### Expected behavior

The `Resource`'s `service.name` attribute should be `foo` rather than `unknown_service`.

### PR DESCRIPTION
**Pull request by Aneurysm9**
Fixes #1968

### CODE REVIEW

**Review by MrAlias — APPROVED** [review]

**Review by dashpole — APPROVED** [review]

File: sdk/resource/env.go [hunk 1]
```diff
@@ -17,14 +17,20 @@ package resource // import "go.opentelemetry.io/otel/sdk/resource"
 import (
 	"context"
 	"fmt"
+	"go.opentelemetry.io/otel/semconv"
```
Comment (MrAlias) [inline sdk/resource/env.go:20]: Looks like gofmt doesn't like this in this location.

Comment (Aneurysm9) [reply sdk/resource/env.go]: GoLand does some things well, but collapsing the import stanza by default is really annoying...

**Review by evantorrie — APPROVED** [review]
