### PR TITLE
Removed different types of Detectors for Resources.

### LINKED ISSUE #1813: `resource.WithoutBuiltin()` is ineffective if used by itself within `resource.New()`
### Description

`resource.WithoutBuiltin()` is ineffective if used by itself within `resource.New()`
`resource.New()` will return nil, which downstream code treats as "no config, give me the defaults".

For example, `prometheus.InstallNewPipeline()`, will in turn call `controller.New()`. If the resource passed to `controller.New()` is nil, then `controller.New()` will assume that you want the defaults. AKA, all the things we wanted to remove with `resource.WithoutBuiltin()`

### Environment

- OS: Linux (but shouldn't matter)
- Architecture: x64 (but shouldn't matter)
- Go Version: 1.16
- opentelemetry-go version: v0.19.0

### Steps To Reproduce

Example code:
```golang
res, err := resource.New(
	context.Background(),
	resource.WithoutBuiltin(),
)
if err != nil {
	return nil, fmt.Errorf("Failed to initialize Prometheus exporter - %w", err)
}

// Create the metrics route
metricsHandler, err := prometheus.InstallNewPipeline(prometheus.Config{}, controller.WithResource(res))
if err != nil {
	return nil, fmt.Errorf("Failed to initialize Prometheus exporter - %w", err)
}
```

All prometheus metrics created will have all the built-in labels added. (Service, sdk, etc.)

### Workaround

```golang
type NullDetector struct{}

// Detect implements Detector
func (NullDetector) Detect(ctx context.Context) (*resource.Resource, error) {
	return nil, nil
}
```

```golang
res, err := resource.New(
	context.Background(),
	resource.WithoutBuiltin(),
	resource.WithDetectors(&telemetry.NullDetector{}),
)
if err != nil {
	return nil, fmt.Errorf("Failed to initialize Prometheus exporter - %w", err)
}

// Create the metrics route
metricsHandler, err := prometheus.InstallNewPipeline(prometheus.Config{}, controller.WithResource(res))
if err != nil {
	return nil, fmt.Errorf("Failed to initialize Prometheus exporter - %w", err)
}
```

### Expected behavior

Passing `resource.WithoutBuiltin()` to `resource.New()`, should result in no built-in labels being added.

### Possible solution

`resource.WithoutBuiltin()` should both nil out all the built-in detectors, but also add a NullDetector, so that we're guaranteed to have a single "valid" detector on return.

### PR DESCRIPTION
**Pull request by MadVikingGod**
This change simplifies different types of collectors into one list. The order of this list determines how they are applied.  Defaults are applied when the user does not supply any detectors.  To achieve default behavior and additional behavior a DefaultDetectors struct has been created.

This addresses usability concerns from #1690 

Feedback request:
Does this simplify things too much?
Is this better than what we have?

Closes #1813

### CODE REVIEW

File: sdk/resource/builtin.go [hunk 1]
```diff
@@ -46,6 +46,10 @@ type (
 	}
 
 	defaultServiceNameDetector struct{}
+
+	// NoOp is a Detector that only provides an empty resource.  Used
```
Comment (seh) [inline sdk/resource/builtin.go:50]: Perhaps consider the name "Empty" instead of "NoOp" here, though if "Empty" came after some other `Detector`s, it might sound as though it's going to clear the set and start again from nothing for any `Detector`s that follow.

_[Time passes ...]_

Oh, but then reading the documentation at line 109 below, it sounds like this _does_ clear any preceding `Resource`s. Or, a different reading, perhaps it offers an empty `Resource` to be merged, which would still count as a "no-op." I'll need to keep reading further to understand how we use the output of each `Detector`.

File: sdk/resource/builtin.go [hunk 2]
```diff
@@ -101,3 +105,9 @@ func (defaultServiceNameDetector) Detect(ctx context.Context) (*Resource, error)
 		},
 	).Detect(ctx)
 }
+
+// Detector that does nothing. Used to disable other builtin Detectors.
+// Detect implements Detector
```
Comment (seh) [inline sdk/resource/builtin.go:110]:
```suggestion
```

File: sdk/resource/config.go [hunk 3]
```diff
@@ -67,6 +55,8 @@ func (d detectAttributes) Detect(context.Context) (*Resource, error) {
 }
 
 // WithDetectors adds detectors to be evaluated for the configured resource.
+// If no detectors are passed, a resource will default to use BuiltinDetectors.
+// To disable this behavior use a NoOp Detector
```
Comment (seh) [inline sdk/resource/config.go:59]:
```suggestion
// If no detectors are passed, construct the resource using BuiltinDetectors.
// To disable this behavior, use a NoOp Detector.
```
This still seems odd. If one skips using `WithDetectors`, what happens? Does the provider use `BuiltinDetectors`? The comment at line 81 below suggests that it does. If one decides to use `WithDetectors`, but with an empty sequence, it seems that that should mean something different than not having used `WithDetectors` at all. I interpret that instinctively to mean "with no `Detector`s." Restating:
- `New(ctx)`: Use builtin `Detector`s.
- `New(ctx, WithDetectors())`: Use no `Detector`s.
- `New(ctx, WithDetectors(d1, d2))`: Use `Detector` "d1," then overlay `Detector` "d2"'s findings.

Another approach to consider is changing the signature of `WithDetectors` to mandate at least one `Detector`: `WithDetectors(first Detector, rest ...Detector)`. However, we're then back to the problem of being able to indicate that we want no `Detectors`, which could lead to another function like `WithoutDetectors()`. If someone passes both `WithDetectors` and `WithoutDetectors`, we could either say that the latter would have no effect, or we could attempt to catch the conflict and return an error from `New`.

File: sdk/resource/builtin.go (hunk 1 above)
Comment (MadVikingGod) [reply sdk/resource/builtin.go:50]: Point taken, I did think of Empty but came to the same conclusion.  Because the detectors are overlays, later detectors will overwrite keys from earlier ones, I decided not to have any name that would imply that it erases any previous detector work.

If this attempt at cleaning up the API around resources is more useable we can have a discussion about what to call the `Detector` that doesn't detect anything before the merge.

File: sdk/resource/config.go (hunk 3 above)
Comment (MadVikingGod) [reply sdk/resource/config.go]: That is a good point.  I updated `WithDetectors` to handle that case, it should now disable the defaults if you pass no Detectors.   

I think that approach will put us effectively in the same position.  We would also have to handle the special case when someone uses `WithDetectors(nil)`.

File: sdk/resource/builtin.go [hunk 4]
```diff
@@ -101,3 +105,8 @@ func (defaultServiceNameDetector) Detect(ctx context.Context) (*Resource, error)
 		},
 	).Detect(ctx)
 }
+
+// Detector that does nothing. Used to disable default Detector behavior.
```
Comment (Aneurysm9) [inline sdk/resource/builtin.go:109]:
```suggestion
// Detect does nothing. Used to disable default Detector behavior.
```

The linter will yell at you if the first word of the godoc isn't the method name.

File: sdk/resource/config.go [hunk 5]
```diff
@@ -67,7 +55,24 @@ func (d detectAttributes) Detect(context.Context) (*Resource, error) {
...
+// ```
+// New(ctx,
+//      WithDetectors(BuiltinDetectors...),
+//      WithDetectors(d1),
+// )
+// ```
+// Use The `BuiltinDetectors`, then overlay Detector `d1`
 func WithDetectors(detectors ...Detector) Option {
+	if len(detectors) == 0 {
+		return detectorsOption{detectors: []Detector{NoOp{}}}
```
Comment (Aneurysm9) [inline sdk/resource/config.go:74]:
```suggestion
		detectors = []Detector{NoOp{}}
```

Unless there's a reason to not change `detectors` here I have a slight preference for a single return.

File: sdk/resource/config.go [hunk 6]
```diff
@@ -67,7 +55,24 @@ func (d detectAttributes) Detect(context.Context) (*Resource, error) {
 }
 
 // WithDetectors adds detectors to be evaluated for the configured resource.
+// Any use of WithDetectors disabled the default behavior, to reenable this
+// inlcude a WithDetectors(BuiltinDetectors...),
+// Examples:
+// `New(ctx)`: Use builtin `Detector`s.
+// `New(ctx, WithDetectors())`: Use no `Detector`s
+// `New(ctx, WithDetectors(NoOp{}))`: Use no `Detector`s
+// `New(ctx, WithDetectors(d1, d2))`: Use Detector `d1`, then overlay Detector `d2`
```
Comment (seh) [inline sdk/resource/config.go:64]:
```suggestion
// `New(ctx, WithDetectors())`: Use no `Detector`s.
// `New(ctx, WithDetectors(NoOp{}))`: Use no `Detector`s.
// `New(ctx, WithDetectors(d1, d2))`: Use Detector `d1`, then overlay Detector `d2`.
```
If `WithDetectors` with no arguments does the same thing as passing `NoOp`, do we still need to export `NoOp`?

**Review by Aneurysm9 — APPROVED** [review]

File: CHANGELOG.md [hunk 7]
```diff
@@ -89,6 +90,8 @@ This project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.htm
 - The `trace.FlagsDebug` and `trace.FlagsDeferred` constants have been removed and will be localized to the B3 propagator. (#1770)
 - Remove `Process` configuration, `WithProcessFromEnv` and `ProcessFromEnv`, from the Jaeger exporter package.
   The information that could be configured in the `Process` struct should be configured in a `Resource` instead. (#1776)
+- Remove `resource.WithoutBuiltin()`.  Any use of `resource.WithDetecors()` will have the same effect (#1810)
```
Comment (evantorrie) [inline CHANGELOG.md:93]:
```suggestion
- Remove `resource.WithoutBuiltin()`.  Any use of `resource.WithDetectors()` will have the same effect (#1810)
```

File: sdk/resource/config.go [hunk 8]
```diff
@@ -67,7 +55,24 @@ func (d detectAttributes) Detect(context.Context) (*Resource, error) {
 }
 
 // WithDetectors adds detectors to be evaluated for the configured resource.
+// Any use of WithDetectors disabled the default behavior, to reenable this
+// inlcude a WithDetectors(BuiltinDetectors...),
```
Comment (evantorrie) [inline sdk/resource/config.go:59]:
```suggestion
// Any use of WithDetectors disables the default detectors. Use
// WithDetectors(BuiltinDetectors...) to reenable the default detectors.
```

File: sdk/resource/config_test.go [hunk 9]
```diff
@@ -23,103 +23,117 @@ import (
...
-	})
-	require.NoError(t, err)
-	defer func() { require.NoError(t, store.Restore()) }()
+func TestConfig(t *testing.T) {
+	tc := []struct {
+		name      string
+		envars    string
+		detectors []resource.Detector
+
+		resouceValues map[string]string
```
Comment (evantorrie) [inline sdk/resource/config_test.go:38]: `resourceValues` instead of `resouceValues`?

Comment (MadVikingGod) [reply sdk/resource/config_test.go]: Thanks for those.  Look like I didn't even realize that spellcheck wasn't installed in codespaces.

File: sdk/resource/config.go [hunk 10]
```diff
@@ -67,7 +55,24 @@ func (d detectAttributes) Detect(context.Context) (*Resource, error) {
...
+// Examples:
+// `New(ctx)`: Use builtin `Detector`s.
+// `New(ctx, WithDetectors())`: Use no `Detector`s.
```
[the remark this answers is not in the document]
Comment (MadVikingGod) [reply sdk/resource/config.go]: You are absolutely right two, really three including `WithAttributes`, makes more sense.  I couldn't see that when I started and was gummed up with the special place that different `Detectors` had.  

I choose EmptyResouce, but I'm open to changing the name if a better one is found.  

In my reading of above `New(ctx, WithDetectors(d1))` === `NewRawResource(ctx, WithBuiltins(), WithDetectors(d1))`.  Is that what you would intend?

File: sdk/resource/config.go [hunk 11]
```diff
@@ -81,85 +86,23 @@ func (o detectorsOption) Apply(cfg *config) {
...
-type noBuiltinOption struct {
-	option
-}
-
-// Apply implements Option.
-func (o noBuiltinOption) Apply(cfg *config) {
-	cfg.host = nil
-	cfg.telemetrySDK = nil
-	cfg.fromEnv = nil
+var BuiltinDetectors = []Detector{
```
[the remark this answers is not in the document]
Comment (MadVikingGod) [reply sdk/resource/config.go]: So this is a much more substantial trimming down of the API than originally intended, but I think it has made it better for it.  

I have updated the PR to reflect that these should be not exported, and the tests now work without them.

[the remark this answers is not in the document]
Comment (seh) [reply sdk/resource/config.go]: Also, with an exported slice, callers can mutate it in place, which is probably not something we should encourage. Granted, they're more likely to break their own program by doing so, but it's better if we can preclude it altogether.

File: sdk/resource/config.go (hunk 10 above)
[the remark this answers is not in the document]
Comment (seh) [reply sdk/resource/config.go]: Would a "raw resource" need a `context.Context`? I thought that `Context` was used by some of the builtin detectors.

[the remark this answers is not in the document]
Comment (MadVikingGod) [reply sdk/resource/config.go]: You would need it if you passed in any detectors, as Detector interface is `Detect(ctx context.Context) (*Resource, error)`

[the remark this answers is not in the document]
Comment (seh) [reply sdk/resource/config.go]: Ah, thank you for clarifying. Given that, I agree that we need that parameter.

File: CHANGELOG.md [hunk 12]
```diff
@@ -37,6 +37,7 @@ This project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.htm
 - The `Event` and `Link` struct types from the `go.opentelemetry.io/otel` package now include a `DroppedAttributeCount` field to record the number of attributes that were not recorded due to configured limits being reached. (#1771)
 - The Jaeger exporter now reports dropped attributes for a Span event in the exported log. (#1771)
 - Adds `k8s.node.name` and `k8s.node.uid` attribute keys to the `semconv` package. (#1789)
+- Adds `resource.NewEmptyResouce()` for creating a Resouce without builtin detectors (#1810)
```
Comment (XSAM) [inline CHANGELOG.md:40]:
```suggestion
- Adds `resource.NewEmptyResource()` for creating a Resource without builtin detectors (#1810)
```

`NewEmptyResource` instead of `NewEmptyResouce`?

File: CHANGELOG.md [hunk 13]
```diff
@@ -105,6 +106,8 @@ This project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.htm
   The information that could be configured in the `Process` struct should be configured in a `Resource` instead. (#1776, #1804)
 - Remove the `WithDisabled` option from the Jaeger exporter.
   To disable the exporter unregister it from the `TracerProvider` or use a no-operation `TracerProvider`. (#1806)
+- Remove `resource.WithoutBuiltin()`. Use `resource.NewEmptyResource()`. (#1810)
+- Unexported types `resouce.FromEnv`, `resource.Host`, and `resource.TelemetrySDK`, Use the corresponding `With*()` to use individually. (#1810)
```
Comment (XSAM) [inline CHANGELOG.md:110]:
```suggestion
- Unexported types `resource.FromEnv`, `resource.Host`, and `resource.TelemetrySDK`, Use the corresponding `With*()` to use individually. (#1810)
```

File: sdk/resource/resource.go [hunk 14]
```diff
@@ -40,9 +40,25 @@ var (
...
 		}
 		return r
-	}(Detect(context.Background(), defaultServiceNameDetector{}, FromEnv{}, TelemetrySDK{}))
+	}(Detect(context.Background(), defaultServiceNameDetector{}, fromEnv{}, telemetrySDK{}))
 )
 
+// New returns a Resource combined from the builtin detectors and user-provided detectors.
+func New(ctx context.Context, opts ...Option) (*Resource, error) {
+	opts = append([]Option{WithBuiltinDetectors()}, opts...)
+	return NewEmptyResouce(ctx, opts...)
```
Comment (XSAM) [inline sdk/resource/resource.go:49]:
```suggestion
	return NewEmptyResource(ctx, opts...)
```

File: CHANGELOG.md [hunk 15]
```diff
@@ -37,6 +37,7 @@ This project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.htm
 - The `Event` and `Link` struct types from the `go.opentelemetry.io/otel` package now include a `DroppedAttributeCount` field to record the number of attributes that were not recorded due to configured limits being reached. (#1771)
 - The Jaeger exporter now reports dropped attributes for a Span event in the exported log. (#1771)
 - Adds `k8s.node.name` and `k8s.node.uid` attribute keys to the `semconv` package. (#1789)
+- Adds `resource.NewEmptyResource()` for creating a Resource without builtin detectors (#1810)
```
Comment (MrAlias) [inline CHANGELOG.md:40]:
```suggestion
- Adds `resource.NewEmptyResource()` for creating a Resource without builtin detectors. (#1810)
```

File: sdk/resource/config.go [hunk 16]
```diff
@@ -81,85 +69,24 @@ func (o detectorsOption) Apply(cfg *config) {
...
-	}
-	for _, opt := range opts {
-		opt.Apply(&cfg)
-	}
-	detectors := append(
-		[]Detector{cfg.telemetrySDK, cfg.host, cfg.fromEnv},
-		cfg.detectors...,
-	)
-	return Detect(ctx, detectors...)
+// WithTelemetrySDK adds TelemetrySDK version info to the configured resoruce.
```
Comment (MrAlias) [inline sdk/resource/config.go:89]:
```suggestion
// WithTelemetrySDK adds TelemetrySDK version info to the configured resource.
```

File: sdk/resource/resource_test.go [hunk 17]
```diff
@@ -260,3 +265,174 @@ func TestMarshalJSON(t *testing.T) {
 		`[{"Key":"A","Value":{"Type":"INT64","Value":1}},{"Key":"C","Value":{"Type":"STRING","Value":"D"}}]`,
 		string(data))
 }
+
+func TestNewRawResource(t *testing.T) {
```
Comment (MrAlias) [inline sdk/resource/resource_test.go:269]: nit, but it sounds like we switched from `Raw` to `Empty`.

```suggestion
func TestNewEmptyResource(t *testing.T) {
```

**Review by MrAlias — APPROVED** [review]

**Review by XSAM — APPROVED** [review]

**Review by seh — COMMENTED** [review]
I still find it strange that the function name `New` means "pre-populated," and `NewEmptyResource` means "empty," but has to stutter to get there. This seems like a too-literal reading of the specification's prescription for certain detectors being built in.

I don't take that to mean that every resource needs to enjoy these detectors unless told otherwise. Instead, I take that to mean that every SDK has to include these detectors at minimum, so that they're available for use.

I'd prefer that `resource.New` start with an empty resource, and that we provide a `WithBuiltins` or `WithBuiltinDetectors` option to allow the caller to include those built-in detectors. If a caller forgets to use `WithBuiltins` or `WithBuiltinDetectors`, that's not a failure of the library.

**Comment by MrAlias** [comment]
> I still find it strange that the function name `New` means "pre-populated," and `NewEmptyResource` means "empty," but has to stutter to get there. This seems like a too-literal reading of the specification's prescription for certain detectors being built in.
> 
> I don't take that to mean that every resource needs to enjoy these detectors unless told otherwise. Instead, I take that to mean that every SDK has to include these detectors at minimum, so that they're available for use.
> 
> I'd prefer that `resource.New` start with an empty resource, and that we provide a `WithBuiltins` or `WithBuiltinDetectors` option to allow the caller to include those built-in detectors. If a caller forgets to use `WithBuiltins` or `WithBuiltinDetectors`, that's not a failure of the library.

I see your point, and overall share your view on this naming strategy. It is hard to say definitively one way or another without user research what our users will want in the end. But, I think you are right that having `New` perform the way you describe it will match common Go practices and might be less foreign to other users. I'm find with switching to this.

I would like to know what @jmacd thinks?

**Comment by MadVikingGod** [comment]
>> I still find it strange that the function name New means "pre-populated," and NewEmptyResource means "empty," but has to stutter to get there. This seems like a too-literal reading of the specification's prescription for certain detectors being built in.
>>
>> I don't take that to mean that every resource needs to enjoy these detectors unless told otherwise. Instead, I take that to mean that every SDK has to include these detectors at minimum, so that they're available for use.
>>
>> I'd prefer that resource.New start with an empty resource, and that we provide a WithBuiltins or WithBuiltinDetectors option to allow the caller to include those built-in detectors. If a caller forgets to use WithBuiltins or WithBuiltinDetectors, that's not a failure of the library.
>
> I see your point, and overall share your view on this naming strategy. It is hard to say definitively one way or another without user research what our users will want in the end. But, I think you are right that having New perform the way you describe it will match common Go practices and might be less foreign to other users. I'm find with switching to this.
>
> I would like to know what @jmacd thinks?

I think this is the wrong approach.  I would expect that most uses of a resource would be likely to include the built-in detectors.  But, without any user stories (or probably more likely instrumentation libraries) I am willing to accept this.

**Comment by seh** [comment]
> I would expect that most uses of a resource would be likely to include the built-in detectors. But, without any user stories (or probably more likely instrumentation libraries) I am willing to accept this.

Let's not give up on reaching accord. We have been through quite a journey on this topic.

Was there an earlier version where `resource.New` included the built-in detectors, but we had a `WithoutBuiltins` (`WithoutBuiltinDetectors`?) or similar functional option that could clear them? I proposed that in https://github.com/open-telemetry/opentelemetry-go/issues/1690#issuecomment-796243419. I apologize if I've since argued against that same idea.

File: CHANGELOG.md [hunk 18]
```diff
@@ -10,15 +10,18 @@ This project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.htm
 
 ### Added
 
+
```
Comment (MrAlias) [inline CHANGELOG.md:13]:
```suggestion
```

File: CHANGELOG.md [hunk 19]
```diff
@@ -10,15 +10,18 @@ This project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.htm
...
   `NewSplitDriver` now automically implements an internal `noopDriver` for `SplitConfig` fields that are not initialized. (#1798)
+- `resource.New()` now creates a Resource without builtin detectors. Previous behavior is now achieved by using `WithBuiltinDetectors` Option. (#1810)
 
 ### Deprecated
 
 ### Removed
-
+- Remove `resource.WithoutBuiltin()`. Use `resource.New()`. (#1810)
+- Unexported types `resource.FromEnv`, `resource.Host`, and `resource.TelemetrySDK`, Use the corresponding `With*()` to use individually. (#1810)
 ### Fixed
```
Comment (MrAlias) [inline CHANGELOG.md:25]:
```suggestion

- Remove `resource.WithoutBuiltin()`. Use `resource.New()`. (#1810)
- Unexported types `resource.FromEnv`, `resource.Host`, and `resource.TelemetrySDK`, Use the corresponding `With*()` to use individually. (#1810)

### Fixed
```

File: sdk/resource/resource_test.go [hunk 20]
```diff
@@ -260,3 +265,175 @@ func TestMarshalJSON(t *testing.T) {
...
+			ctx := context.Background()
+			res, err := resource.New(ctx, tt.options...)
+
+			require.NoError(t, err)
+			require.EqualValues(t, tt.resourceValues, toMap(res))
+		})
+	}
+}
+
+func TestNew_WithBuiltinDetectors(t *testing.T) {
```
Comment (MrAlias) [inline sdk/resource/resource_test.go:368]:
```suggestion
func TestNewWithBuiltinDetectors(t *testing.T) {
```

**Comment by MadVikingGod** [comment]
> Let's not give up on reaching accord. We have been through quite a journey on this topic.

I think we have reached an accord, just not a unamious one.  We have two different paths one `New()` returns the empty resource, and the other `New()` returns a filled-out version.  Both are valid ways for an "object" to be constructed in go.  

The former is probably more common, but _I think_ less useful in this case.
The latter is more useful _I think_ because most use cases, instrumentation and client applications, will want to have the default detectors with maybe additional ones.

The problem is that without any use-case data it is just what I think.

If 3 out of the 4 people, including myself, who have commented so far came to the same conclusion then I am willing to commit to the majority decision.  I don't think we can change this behavior after 1.0, but I think the worst thing that comes out of the current configuration is there is a lot of missing resource descriptions, and a lot of extra `WithBuiltins()` written.

**Review by Aneurysm9 — APPROVED** [review]
