### PR TITLE
Fix Windows build of Jaeger tests

### LINKED ISSUE #1576: exporters/trace/jaeger test compilation error
Testing on [Windows (Go 1.15 arch=amd64)](https://github.com/open-telemetry/opentelemetry-go/runs/1964472382?check_suite_focus=true):

```
# go.opentelemetry.io/otel/exporters/trace/jaeger [go.opentelemetry.io/otel/exporters/trace/jaeger.test]
Error: .\reconnecting_udp_client_test.go:87:45: cannot use int(fd.Fd()) (type int) as type syscall.Handle in argument to syscall.GetsockoptInt
FAIL	go.opentelemetry.io/otel/exporters/trace/jaeger [build failed]
```

I am able to reproduce this locally on a linux system:

```
$ cd exporters/trace/jaeger
$ GOOS=windows go test .
# go.opentelemetry.io/otel/exporters/trace/jaeger [go.opentelemetry.io/otel/exporters/trace/jaeger.test]
./reconnecting_udp_client_test.go:87:45: cannot use int(fd.Fd()) (type int) as type syscall.Handle in argument to syscall.GetsockoptInt
FAIL	go.opentelemetry.io/otel/exporters/trace/jaeger [build failed]
FAIL
```

It looks like we use the low level `syscall` package with a unix specific calling signature:

https://github.com/open-telemetry/opentelemetry-go/blob/4a163beaa103fd57b4cf6e07dc19781ab2fda4a9/exporters/trace/jaeger/reconnecting_udp_client_test.go#L87

The unix function signature for `syscall.GetsockoptInt`:

```
func GetsockoptInt(fd, level, opt int) (value int, err error)
```

Where the windows signature is:

```
func GetsockoptInt(fd Handle, level, opt int) (int, error)
```

### PR DESCRIPTION
**Pull request by MrAlias**
The Jaeger tests use the low-level syscall package. The Windows specific function called in that package has a different function signature than the unix version. Add a windows specific file using the build flags to isolate this OS specific functionality.

I'm able to verify this fixes the compilation of the testing package and the test failure on a Windows system:

```
go test -timeout 30s -short ./exporters/trace/jaeger/...
ok  	go.opentelemetry.io/otel/exporters/trace/jaeger	2.906s
?   	go.opentelemetry.io/otel/exporters/trace/jaeger/internal/gen-go/jaeger	[no test files]
?   	go.opentelemetry.io/otel/exporters/trace/jaeger/internal/gen-go/jaeger/collector-remote	[no test files]
```

Resolves #1576

### CODE REVIEW

**Review by Aneurysm9 — APPROVED** [review]

**Comment by MrAlias** [comment]
Looking further into the error message from the actual test run, it looks like this will always fail on Windows. The network file descriptor is not available from the connection on Windows. A `dup` method still needs to be implemented for the netFD on Windows.

https://github.com/golang/go/blob/6cc8aa7ece96aca282db19f08aa5c98ed13695d9/src/net/fd_windows.go#L175-L178

I'm going to updated this to return just return `true` and add a comment.

File: exporters/trace/jaeger/assertsocketbuffersize_windows.go [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+func assertSockBufferSize(t *testing.T, expectedBytes int, conn *net.UDPConn) bool {
+	// The Windows implementation of the net.UDPConn does not implement the
+	// functionality to return a file handle, instead a "not supported" error
+	// is returned:
+	//
+	// https://github.com/golang/go/blob/6cc8aa7ece96aca282db19f08aa5c98ed13695d9/src/net/fd_windows.go#L175-L178
+	//
+	// This means we are not able to pass the connection to a syscall and
+	// determine the buffer size.
+	return true
```
Comment (Aneurysm9) [inline exporters/trace/jaeger/assertsocketbuffersize_windows.go:33]: Should we maybe just remove this file entirely and put a comment in the one guarded by `+build !windows` explaining why?

Comment (MrAlias) [reply exporters/trace/jaeger/assertsocketbuffersize_windows.go:33]: I'm not sure I follow. If we remove this file and keep `assertsocketbuffersize.go` the same the tests will continue to fail to build on windows.

Comment (Aneurysm9) [reply exporters/trace/jaeger/assertsocketbuffersize_windows.go:33]: yup, you're right.  I saw the `testing.T` as the first parameter and thought it was the test itself, but the function name doesn't start with `test`, so obviously it isn't.  Carry on!

**Review by Aneurysm9 — APPROVED** [review]

**Review by XSAM — APPROVED** [review]
