### PR TITLE
Fix delegation for global MeterProviders

### LINKED ISSUE #5827: Regression: Delegation broken for global meterproviders
From https://github.com/open-telemetry/opentelemetry-go/issues/5753#issuecomment-2354164595 reported by @Jesse-Bonfire

> It appears that this change has broken metrics that are registered before otel.SetMeterProvider is called. We are getting into a spot where the delegate on the siUpDownCounter isn't getting set as it looks like with the new map we are creating new ones and throwing away the old. But the old counter has been registered with meter.RegisterCallback
https://github.com/open-telemetry/opentelemetry-go/blob/42fd8fe325c125a40a21796c3f14b599e5e5f586/internal/global/meter.go#L175C8-L175C9

> I am pretty new to Otel and Go but this change seems to break the connection pools convention outlined here.
https://github.com/open-telemetry/semantic-conventions/blob/422eeb71f40c73d1b195723cc1cffeb09abf2391/docs/database/database-metrics.md#connection-pools

> Currently I am seeing this when instrumenting a Redis Cluster as it creates instrumentation for the connection pool to each node in the cluster. https://github.com/redis/go-redis/blob/233f97accde15bcb2e3d86ee744109b4dce34171/extra/redisotel/metrics.go#L85

> This problem is removed if we apply the instrumentation after we call otel.SetMeterProvider because the delegate just creates the counter. Not sure the best way to proceed.

> I am able to reproduce the exception with the following test case

```golang
package bench

import (
	"context"
	"testing"

	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/metric"
	sdkmetric "go.opentelemetry.io/otel/sdk/metric"
)

const (
	meterName  = "foo"
	metricName = "bar"
)

func BenchmarkSimple(b *testing.B) {
	b.ReportAllocs()
	meter := otel.Meter(meterName)
	for i := 0; i < 5; i++ {
		m, _ := meter.Int64ObservableUpDownCounter(metricName)
		meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
			o.ObserveInt64(m, int64(10))
			return nil
		}, m)
	}
	p1 := sdkmetric.NewMeterProvider()
	otel.SetMeterProvider(p1)
}
```

### LINKED ISSUE #5852: Bug: panic on SetMeterProvider
### Description
Panic on setting [SetMeterProvider](https://pkg.go.dev/go.opentelemetry.io/otel#SetMeterProvider)

```sh
Starting: /home/sarath/gopath/bin/dlv dap --listen=127.0.0.1:37125 --log-dest=3 from /home/sarath/projects/messageplusio/be/cmd/rest
DAP server listening at: 127.0.0.1:37125
Type 'dlv help' for list of commands.
2024/09/28 08:22:32 goose: no migrations to run. current version: 20240906210523
2024/09/28 08:22:32 goose: no migrations to run. current version: 20230711140249
2024/09/28 08:22:32 invalid observable: from different implementation
2024/09/28 08:24:41 failed to upload metrics: context deadline exceeded
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb6295c]

goroutine 1 [running]:
go.opentelemetry.io/otel/internal/global.(*registration).setDelegate(0xc000450900, {0x1d97308, 0xc000494160})
	/home/sarath/gopath/pkg/mod/go.opentelemetry.io/otel@v1.30.0/internal/global/meter.go:492 +0x25c
go.opentelemetry.io/otel/internal/global.(*meter).setDelegate(0xc00019e090, {0x1d7c830, 0xc00011c960})
	/home/sarath/gopath/pkg/mod/go.opentelemetry.io/otel@v1.30.0/internal/global/meter.go:138 +0x2bc
go.opentelemetry.io/otel/internal/global.(*meterProvider).setDelegate(0xc0003ff080, {0x1d7c830, 0xc00011c960})
	/home/sarath/gopath/pkg/mod/go.opentelemetry.io/otel@v1.30.0/internal/global/meter.go:47 +0x1d4
go.opentelemetry.io/otel/internal/global.SetMeterProvider.func1()
	/home/sarath/gopath/pkg/mod/go.opentelemetry.io/otel@v1.30.0/internal/global/state.go:171 +0xad
sync.(*Once).doSlow(0x26a0d80, 0xc00059f1a0)
	/home/sarath/go/src/sync/once.go:76 +0x168
sync.(*Once).Do(0x26a0d80, 0xc00059f1a0)
	/home/sarath/go/src/sync/once.go:67 +0x3e
go.opentelemetry.io/otel/internal/global.SetMeterProvider({0x1d7c830, 0xc00011c960})
	/home/sarath/gopath/pkg/mod/go.opentelemetry.io/otel@v1.30.0/internal/global/state.go:169 +0x22d
go.opentelemetry.io/otel.SetMeterProvider({0x1d7c830, 0xc00011c960})
	/home/sarath/gopath/pkg/mod/go.opentelemetry.io/otel@v1.30.0/metric.go:41 +0x1d
github.com/messageplusio/be/pkg/telemetry.InitMeterProvider({0x1d85558, 0x26a06c0})
	/home/sarath/projects/messageplusio/be/pkg/telemetry/telemetry.go:63 +0x2e5
main.main()
	/home/sarath/projects/messageplusio/be/cmd/rest/main.go:86 +0xb59
Process 249736 has exited with status 2
Detaching
```

### Explanation
If RegisterCallback fails with an error then reg would be nil and unusable. Trying derefer reg for reg.Unregister would panic

Fix : #5851 

### Environment
Applicable on any env

- OS: Fedora
- Architecture:  x86 
- Go Version: 1.23.1
- opentelemetry-go version: v1.30.0

### Expected behavior

No panic

### PR DESCRIPTION
**Pull request by Jesse-Bonfire**
Fixes #5827
Fixes #5852

### CODE REVIEW

**Comment by dashpole** [comment]
Can you add a unit test that fails before the fix, and passes after?

**Comment by dmathieu** [comment]
You will also need to sign the CLA.

**Comment by Jesse-Bonfire** [comment]
Working with my company to get CLA approval. Also where should I put the unit test? internal/global/meter_test.go or is there a better spot?

**Comment by dashpole** [comment]
internal/global/meter_test.go is great

**Comment by blkt** [comment]
Hello folks, sorry to jump in, @MrAlias kindly pointed me to this PR while discussing a problem I had with the recent release of opentelemetry.

While this fix indeed solves the broken delegation problem in our case, the setup we have had the system panicking because it went through [this line](https://github.com/open-telemetry/opentelemetry-go/blob/main/internal/global/meter.go#L489) of code which is not followed by a `return` like similar occurrences, like [this](https://github.com/open-telemetry/opentelemetry-go/blob/7bd1c85f990510890beb7ee0bd14bc172ebf53ea/internal/global/instruments.go#L220) and [this](https://github.com/open-telemetry/opentelemetry-go/blob/7bd1c85f990510890beb7ee0bd14bc172ebf53ea/internal/global/instruments.go#L246).
As a result, it ran `reg.Unregister` with a null pointer.

Since the code has been there for a while I assume this is the desired behavior, but it does look suspicious to me, so I wanted to put this on your radar.

**Comment by Jesse-Bonfire** [comment]
@dashpole @dmathieu what do you folks think? I can add the return in the error case so we don't get null pointers

**Comment by Jesse-Bonfire** [comment]
I had to add the unit test to sdk/metric/meter_test.go to have enough context to repro the issue in the unit test.

File: sdk/metric/meter_test.go [hunk 1]
```diff
@@ -2427,3 +2427,16 @@ func TestDuplicateInstrumentCreation(t *testing.T) {
 		})
 	}
 }
+
+func TestMeterProviderDelegation(t *testing.T) {
```
Comment (dashpole) [inline sdk/metric/meter_test.go:2431]: how does this fail before your fix?  I don't see any checks

Comment (Jesse-Bonfire) [reply sdk/metric/meter_test.go:2431]: it panics due to null pointer

Comment (Jesse-Bonfire) [reply sdk/metric/meter_test.go:2431]: If we had the return suggested by @blkt then I think it would correctly return an error instead of panicking

Comment (Jesse-Bonfire) [reply sdk/metric/meter_test.go:2431]: yea it won't panic but I will need to register a global error handler in that case

Comment (Jesse-Bonfire) [reply sdk/metric/meter_test.go:2431]: I have added the return to remove the panic, added some additional error checks and added a global error handler to the unit test. Let me know if I am missing anything else.

Comment (dashpole) [reply sdk/metric/meter_test.go:2431]: great, thanks!

File: sdk/metric/meter_test.go [hunk 2]
```diff
@@ -2427,3 +2427,19 @@ func TestDuplicateInstrumentCreation(t *testing.T) {
...
```
Comment (dashpole) [inline sdk/metric/meter_test.go:2431]: Actually, can you move this to internal/global/meter_test.go?  And use the functions in global (global.MeterProvider, globlal.SetErrorHandler instead of the "otel" import.

Comment (Jesse-Bonfire) [reply sdk/metric/meter_test.go:2431]: I tried moving it but my test is dependent on the NewMeterProvider() that is in the sdk/metric/provider.go to show the issue that we were seeing. Is there another meterprovider that would work from global?

Comment (dashpole) [reply sdk/metric/meter_test.go:2431]: Are you able to use noop.NewMeterProvider() without pulling in any additional dependencies?

Comment (dashpole) [reply sdk/metric/meter_test.go:2431]: `go.opentelemetry.io/otel/metric/noop`

Comment (Jesse-Bonfire) [reply sdk/metric/meter_test.go:2431]: the noop.NewMetrerProvider doesn't have a delegate and skips over the original bug

**Comment by jmacd** [comment]
I can confirm that this fixes a regression related to #5754 #5758 #5780 in https://github.com/lightstep/otel-launcher-go.

Without this fix, SetMeterProvider() would reach a panic, e.g.,
```
=== RUN   TestSecureMetricsAltSDK
2024/09/27 10:14:42 asynchronous instrument does not belong to this SDK: *global.aiUpDownCounter
--- FAIL: TestSecureMetricsAltSDK (0.01s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x102ab40cc]

goroutine 36 [running]:
testing.tRunner.func1.2({0x1030e8ba0, 0x103b5d330})
	/opt/homebrew/Cellar/go/1.23.1/libexec/src/testing/testing.go:1632 +0x1bc
testing.tRunner.func1()
	/opt/homebrew/Cellar/go/1.23.1/libexec/src/testing/testing.go:1635 +0x334
panic({0x1030e8ba0?, 0x103b5d330?})
	/opt/homebrew/Cellar/go/1.23.1/libexec/src/runtime/panic.go:785 +0x124
go.opentelemetry.io/otel/internal/global.(*registration).setDelegate(0x1400071c100, {0x1032b4058, 0x140003ce540})
	/Users/josh.macdonald/src/lightstep/go/pkg/mod/go.opentelemetry.io/otel@v1.30.0/internal/global/meter.go:492 +0x19c
go.opentelemetry.io/otel/internal/global.(*meter).setDelegate(0x1400070a120, {0x1032999c0?, 0x14000445040?})
	/Users/josh.macdonald/src/lightstep/go/pkg/mod/go.opentelemetry.io/otel@v1.30.0/internal/global/meter.go:138 +0x1d8
go.opentelemetry.io/otel/internal/global.(*meterProvider).setDelegate(0x14000437230, {0x1032999c0, 0x14000445040})
	/Users/josh.macdonald/src/lightstep/go/pkg/mod/go.opentelemetry.io/otel@v1.30.0/internal/global/meter.go:47 +0x168
go.opentelemetry.io/otel/internal/global.SetMeterProvider.func1()
	/Users/josh.macdonald/src/lightstep/go/pkg/mod/go.opentelemetry.io/otel@v1.30.0/internal/global/state.go:171 +0x3c
sync.(*Once).doSlow(0x140000b45e0?, 0x140000b45c0?)
	/opt/homebrew/Cellar/go/1.23.1/libexec/src/sync/once.go:76 +0xf8
sync.(*Once).Do(...)
```
and with this PR, the issue is resolved.

File: sdk/metric/meter_test.go (hunk 2 above)
Comment (dashpole) [reply sdk/metric/meter_test.go:2431]: ok, lets keep it here.

**Review by dashpole — APPROVED** [review]

File: CHANGELOG.md [hunk 3]
```diff
@@ -7,6 +7,7 @@ The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/).
 This project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).
 
 ## [Unreleased]
+- Fixed broken delegation for global meter providers. Changed the reflect.TypeOf() to use an empty stack allocation so we aren't allocating on the heap unless we need to (#5827)
```
Comment (dashpole) [inline CHANGELOG.md:10]:
```suggestion

- Fixed broken delegation for global meter providers. Changed the reflect.TypeOf() to use an empty stack allocation so we aren't allocating on the heap unless we need to (#5827)
```

**Review by jmacd — APPROVED** [review]

**Comment by Jesse-Bonfire** [comment]
This is my first time contributing, should I update the branch locally and push or do it in github?

File: CHANGELOG.md (hunk 3 above)
Comment (dashpole) [reply CHANGELOG.md:10]: looks like the markdown linter is still complaining about the missing new line here

**Comment by dashpole** [comment]
Either is fine.  Pushing the update branch button on github is usually less work, but can't resolve conflicts if there are any

File: CHANGELOG.md (hunk 3 above)
Comment (Jesse-Bonfire) [reply CHANGELOG.md:11]: Ok I think that I fixed it. Will wait and see

File: CHANGELOG.md [hunk 4]
```diff
@@ -8,6 +8,8 @@ This project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.htm
 
 ## [Unreleased]
 
+- Fixed broken delegation for global meter providers. Changed the reflect.TypeOf() to use an empty stack allocation so we aren't allocating on the heap unless we need to (#5827)
```
Comment (MrAlias) [inline CHANGELOG.md:11]:
```suggestion
- Fixed broken delegation for global meter providers.
  Changed the `reflect.TypeOf()` to use an empty stack allocation so we aren't allocating on the heap unless we need to. (#5827)
```

File: sdk/metric/meter_test.go [hunk 5]
```diff
@@ -2427,3 +2427,19 @@ func TestDuplicateInstrumentCreation(t *testing.T) {
...
+	meter := otel.Meter("go.opentelemetry.io/otel/metric/internal/global/meter_test")
+	otel.SetErrorHandler(otel.ErrorHandlerFunc(func(err error) { require.NoError(t, err) }))
+	for i := 0; i < 5; i++ {
+		m, err := meter.Int64ObservableUpDownCounter("observable.int64.up.down.counter")
```
Comment (MrAlias) [inline sdk/metric/meter_test.go:2435]: This is only testing an `Int64ObservableUpDownCounter`. Can we test all the instruments that are being fixed in the PR?

Comment (MrAlias) [reply sdk/metric/meter_test.go:2435]: Can you wrap this in [`assert.NotPanics`](https://pkg.go.dev/github.com/stretchr/testify/assert#NotPanics) to indicate what this is testing?

**Review by sarathsp06 — APPROVED** [review]

File: internal/global/meter.go [hunk 6]
```diff
@@ -152,14 +152,17 @@ func (m *meter) Int64Counter(name string, options ...metric.Int64CounterOption)
 		return m.delegate.Int64Counter(name, options...)
 	}
 
-	i := &siCounter{name: name, opts: options}
 	cfg := metric.NewInt64CounterConfig(options...)
 	id := instID{
 		name:        name,
-		kind:        reflect.TypeOf(i),
+		kind:        reflect.TypeOf(siCounter{}),
```
Comment (sarathsp06) [inline internal/global/meter.go:158]: nitpick: There would be a slight difference here as the previous implementation had pointer type in kind. You could use the following to ensure no changes. 
```suggestion
		kind:        reflect.TypeOf((*siCounter)(nil)),
```

File: CHANGELOG.md [hunk 7]
```diff
@@ -8,6 +8,9 @@ This project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.htm
 
 ## [Unreleased]
 
+- Fixed broken delegation for global meter providers. (#5827)
+  Changed the reflect.TypeOf() to use a nil pointer so we aren't allocating on the heap unless we need to.
```
Comment (pellared) [inline CHANGELOG.md:12]: Please move it to `Fixed` section.

Comment (pellared) [reply CHANGELOG.md]: https://github.com/open-telemetry/opentelemetry-go/pull/5828/commits/8b2c127853258cc3c988fc07529b839e919e89ff

File: internal/global/meter.go [hunk 8]
```diff
@@ -487,6 +529,7 @@ func (c *registration) setDelegate(m metric.Meter) {
 	reg, err := m.RegisterCallback(c.function, insts...)
 	if err != nil {
 		GetErrorHandler().Handle(err)
+		return
```
Comment (dmathieu) [inline internal/global/meter.go:532]: Could we test this?

**Comment by sarathsp06** [comment]
> @sarathsp06, can you please confirm if it is also fixing #5852?

It does

**Review by sarathsp06 — APPROVED** [review]
LGTM

**Review by MrAlias — APPROVED** [review]

File: internal/global/meter.go (hunk 8 above)
Comment (jmacd) [reply internal/global/meter.go:532]: https://github.com/open-telemetry/opentelemetry-go/pull/5828#issuecomment-2379804915

Comment (dmathieu) [reply internal/global/meter.go:532]: Yes, but as far as I can see, there's no automated test for this case. The test you mention in your comment is within the lifghtstep launcher.

Comment (Jesse-Bonfire) [reply internal/global/meter.go:532]: Is there anything to do here? I can't think of anything

Comment (dmathieu) [reply internal/global/meter.go:532]: The idea is a test that fails before this change, but passes afterwards. Something like this diff:

```diff
diff --git a/internal/global/meter_test.go b/internal/global/meter_test.go
index aec31e1e..ed90939b 100644
--- a/internal/global/meter_test.go
+++ b/internal/global/meter_test.go
@@ -5,6 +5,7 @@ package global // import "go.opentelemetry.io/otel/internal/global"
 
 import (
 	"context"
+	"errors"
 	"fmt"
 	"sync"
 	"testing"
@@ -395,6 +396,23 @@ func TestRegistrationDelegation(t *testing.T) {
 	})
 }
 
+type failingRegisterCallbackMeter struct {
+	noop.Meter
+}
+
+func (m *failingRegisterCallbackMeter) RegisterCallback(metric.Callback, ...metric.Observable) (metric.Registration, error) {
+	return nil, errors.New("an error occurred")
+}
+
+func TestRegistrationDelegateFailingCallback(t *testing.T) {
+	r := &registration{
+		unreg: func() error { return nil },
+	}
+	m := &failingRegisterCallbackMeter{}
+
+	r.setDelegate(m)
+}
+
 func TestMeterIdentity(t *testing.T) {
 	type id struct{ name, ver, url string }
 ```

Comment (Jesse-Bonfire) [reply internal/global/meter.go:532]: Ok makes sense. Thanks for the code :)

**Review by dmathieu — APPROVED** [review]

**Comment by krak3n** [comment]
ETA on a hot fix release? This regression has impact on your users upgrading to the current released version.
